- app/src/main/java/com/techcourse/config/JdbcTemplateConfig.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/SqlParameterValue.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/RowMapperTest.java
- jdbc/src/test/java/nextstep/jdbc/fixture/DataSourceConfig.java
- jdbc/src/test/java/nextstep/jdbc/fixture/DatabasePopulatorUtils.java
- jdbc/src/test/java/nextstep/jdbc/fixture/User.java
- jdbc/src/test/resources/schema.sql
안녕하세요 인비 🙂
옛날에 진행했던 JDBC 학습 테스트를 참고하면서 이번 미션을 구현해봤어요!
pstmt에 매개변수를 설정하기 위해서 PreparedStatementSetter를 구현했었는데요. 
매번 람다식을 작성하는게 번거로워서 가변인자로 대체했습니다.
그리고 한가지 질문이 있습니다!
JdbcTemplate의 queryForObject에도 try-with-resources를 적용하는 방법이 있을까요?
리뷰 감사합니다. 👍
> [JDBC 라이브러리 구현하기 - 1, 2단계] 에드(박성진) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세융~~
구현 하긴 했는데... 정말 이걸로 되는건지.....
리뷰 잘 부탁 드립니다...!?
> [JDBC 라이브러리 구현하기 - 1, 2단계] 손너잘(손민성) 미션 제출합니다.

- app/src/main/java/com/techcourse/JwpApplication.java
- app/src/main/java/com/techcourse/ManualHandlerMapping.java
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/controller/UserSession.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/main/java/com/techcourse/repository/UserDaoRepository.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java
- app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcCallback.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- learning/src/main/java/annotation/AliasFor.java
- learning/src/main/java/annotation/Component.java
- learning/src/main/java/annotation/Controller.java
- learning/src/main/java/annotation/Repository.java
- learning/src/test/java/reflection/Junit3TestRunner.java
- learning/src/test/java/reflection/Junit4TestRunner.java
- learning/src/test/java/reflection/ReflectionsTest.java
안녕하세요 조엘! 🥺
이렇게 또 만나게 되다니 너무 반갑네요. ㅎㅎ 😊
RowMapper, Callback 개념이 상당히 어렵게 다가와서 이해하는데 어려웠습니다. (사실 아직 제대로 이해하지 못한 것 같아요.. 🥲)
특히 JdbcTemplate 구현 과정에서 이것저것 시도해 보고 롤백시키는 작업을 하다보니 JdbcTemplate 기능 구현이 하나의 커밋으로 묶여서 리뷰하실 때 복잡해 보일 수도 있겠네요? 😔
제가 놓치거나 부족한 부분이 있다면 따끔한 충고 부탁드리겠습니다! 😀
> [JDBC 라이브러리 구현하기 - 1, 2단계] 와일더(강규한) 미션 제출합니다.

- app/build.gradle
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultSetDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSetSizeDataAccessException.java
안녕하세요 제리 ㅎ..ㅎ 삭정입니다.
요새 할게 너무 많아서... 좀 미션에 신경을 덜 쓴 감이 있지만 잘 부탁드립니다 ㅎㅎㅎㅎㅎㅎㅎㅎ
> [JDBC 라이브러리 구현하기 - 1, 2단계] 삭정(성정석) 미션 제출합니다.

- app/build.gradle
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/webapp/WEB-INF/web.xml
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/ActionTemplate.java
- jdbc/src/main/java/nextstep/jdbc/JdbcCustomException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 바다~~~~ 🌊🧜‍♀️🐋
맨날 코드리뷰 보내다가 이렇게 만나니 색다르네요? ? ? ? 파하하핫
try catch 부분이 중복되는게 맘에 안들어서 인터페이스로 분리를 했는데 가독성이 더 떨어진 것 같기도 하고...
테스트 코드 짜고 싶었는데 아름다운 방법을 찾지 못해 미루겠읍니다...
리뷰 한번 받고 inmemory->dao 로 바꾸는거랑 테스트 구현하는 거 도전해보겠습니다!!!!
리뷰 잘 부탁드려요~~~~~ 🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 1, 2단계] 샐리(조연우) 미션 제출합니다.

- app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/Query.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/JdbcTemplateException.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/RepositoryScanner.java
- mvc/src/main/java/nextstep/web/annotation/Repository.java
안녕하세요 알리입니다!
동작 별로 다른 작업을 하도록 함수형 인터페이스를 사용해봤습니다!
감사합니다!
> [JDBC 라이브러리 구현하기 - 1, 2단계] 알리(허진호) 미션 제출합니다.

- app/build.gradle
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/exception/ObjectCreationException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/RowMapperExtractor.java
웨지 정말 오랜만이예요~~~ 
미션을 통해 만나는 건 처음이라 많이 설레네요 ㅎㅎㅎ 
실제 JDBCTemplate를 많이 참고해서 구현해보았어요!
이번 미션 잘 부탁드립니다~ 😃
> [JDBC 라이브러리 구현하기 - 1, 2단계] 아론(장세환) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
안녕하세요 피케이, 맨날 디코에 같이 상주하지만 형식적으로 만나서 반갑다라는 메시지를 남깁니다 하하.
토비 보고 하려고 했다가, 그냥 공식문서 보면서 헤딩했습니다.
구현할때, Row Mapper 부분은 감이 잘안와서, 실제로 구현되어있는 [공식문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/RowMapper.html) 를 참고해서 구현했구요.
하다가 막히는 부분(query)들은 [JdbcTemplate 공식문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#query-org.springframework.jdbc.core.PreparedStatementCreator-org.springframework.jdbc.core.PreparedStatementSetter-org.springframework.jdbc.core.ResultSetExtractor-)를 참고하면서 구현해봤습니다.
부담없이 편하게 리뷰해주세요 ~
> [JDBC 라이브러리 구현하기 - 1, 2단계] 포츈(정윤성) 미션 제출합니다. 

- README.md
- app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ObjectMapper.java
- jdbc/src/main/java/nextstep/jdbc/PrepareStatementAction.java
- jdbc/src/main/java/nextstep/jdbc/PrepareStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/QueryException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/DBConnector.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/RepositoryScanner.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/ServiceScanner.java
- mvc/src/main/java/nextstep/web/annotation/ConnectingDB.java
- mvc/src/main/java/nextstep/web/annotation/DBConnection.java
- mvc/src/main/java/nextstep/web/annotation/Repository.java
- mvc/src/main/java/nextstep/web/annotation/Service.java
안녕하세요! 아마찌
리뷰이로 오랜만에 뵙게 되었습니다.
이번 미션은 앞선 두 미션에 비해 난이도가 상당히 높았던 것 같습니다.
추석 기간 내내 지속적으로 조금씩 조금씩 공부하면서 진행하게 되었어요.
특히나 프레임워크가 알아야할 범위는 어디까지인가?를 많이 고민해볼 수 있었던 것 같습니다.
가이드라인을 따라가다보니 궁금한 점이 생겨서 같이 질문으로 남기겠습니다.
1) JDBCTemplate Test
jdbctemplate은 라이브러리에 속해져있습니다. 때문에 외부의 구조를 알면 안되는데요.
이 때문에 테스트 코드를 진행할 때, verify를 통해서 해당 구성요소들이 동작을 하느냐 안하느냐 정도만 알 수 있었던 것 같습니다.
컴포넌트로 하나의 요소이며, 어떤 값을 반환할지 모른다는 점에서 이정도면 충분한 테스트라고 추론을 하고 있는데 아마찌의 의견이 궁금합니다.
2) PreparedStatementSetter
값을 삽입하는 insert 로직은 PreparedStatement에서 setValue를 해줄 필요가 없습니다.
이 때문에 따로 인터페이스로 분리를 하면 좋겠다고 가이드라인에 나와있었는데요.
하지만 setValue를 어떻게 분리하면 좋을지, 더 나아가 가변인자로 인해서 자동으로 생략이 될 것 같은데 분리 필요성이 큰지 궁금해서 질문을 남기게 되었습니다.
감사합니다!
> [JDBC 라이브러리 구현하기 - 1, 2단계] 와이비(허영범) 미션 제출합니다. 

- .gitignore
- app/build.gradle
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSizeDataAccessException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- learning/src/test/java/callback/CallbackTest.java
- learning/src/test/java/reflection/ReflectionsTest.java
- mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
- mvc/src/main/java/nextstep/web/annotation/InjectDao.java
- mvc/src/main/java/nextstep/web/annotation/Repository.java
안녕하세요 루트~~ 요즘 대화를 거의 못해본 거 같은데 리뷰어로 만나게 되어서 너무 반갑네요!!!! 잘 부탁드립니다!!!
요구사항은 며칠 전에 끝냈는데... 테스트도 열심히 짰는데...!!
~어플리케이션을 실행하니까 (제 추측으로는) userDao가 자동주입이 안 되어서 에러가 나는 것 같더라구요 🥲~
~야심차게 어노테이션을 만들어가지고 해결하려다... 잘 안 되어서 제출 먼저 해봅니당 흑흑~
~계속 건드리는 중인데 해결된다면 커밋하고 디엠 드릴게요 😇~
멍토와 영이의 도움으로 해결했습니다 하핳
피드백은 환영이에요!!!!
> [JDBC 라이브러리 구현하기 - 1, 2단계] 춘식(안예장) 미션 제출합니다.

- app/build.gradle
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/context/ContextLoaderListener.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ResultSetExtractor.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/StatementCallback.java
오랜만에 뵙게 되어 반가워요 🙌
기존 Dao 코드를 `JdbcTemplate` 내부로 옮기고, `JdbcTemplate#execute()`에 코드를 모아서 
최대한 중복 코드를 제거하려고 노력해봤어요. 그 과정에서 구구의 학습 테스트에 있는 Callback 클래스를 따라서 써봤는데 제대로 적용했는지 잘 모르겠네요. 보시면서 어색한 부분이 있다면 알려주세요!!
리뷰는 추석 끝나고 천천히 해주셔도 괜찮습니다!!
즐거운 추석 보내시고, 리뷰 잘 부탁드립니다 😄
> [JDBC 라이브러리 구현하기 - 1, 2단계] 시드(김현식) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCreator.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultDataAccessException.java
안녕하세요! 시드! 이번에 코드리뷰를 받게 될 수리입니다.
스프링의 JdbcTemplate를 참고해서
PreparedStatementCreator, PreparedStatementCallback을 통해
다양한 처리를 할 수 있도록 구현해 보았습니다!!
아직 템플릿 메소드 패턴과 콜백 개념이 익숙치 않아 어려웠습니다!!
그럼 코드리뷰 부탁 드릴게요!!
감사합니다 시드!
> [JDBC 라이브러리 구현하기 - 1, 2단계] 수리(이다원) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ParameterSource.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
달이 아름답네요.
JdbcTemplate을 테스트하기 위해 DataSource, Connection, PreparedStatement의 목 객체를 만들었는데, 뭔가 아닌것 같아서 일단은 롤백했습니다.
> [JDBC 라이브러리 구현하기 - 1단계] 정(정진우) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/ResultSetExtractor.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세요 토르! 
미션에서 요구하는 내용은 어느정도 구현한 것 같아서 리뷰 요청드립니다!
반복되는 Connection과 PreparedStatement 만드는 부분의 경우에는 콜백 함수로 묶어서 처리하고자 하였습니다.
바쁘신 와중에 리뷰 감사합니다~!!👍👍
> [JDBC 라이브러리 구현하기 - 1단계] 루나(남민정) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/core/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/DummyUser.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
차리 안녕하세요 ~ 
1단계 미션 제출합니다!! 
마음에 안드는 부분이 있긴 하지만 2단계가 리펙터링이더라구요. 그래서 우선 제출하겠습니당 
리뷰 잘부탁드립니다~.~
>  [JDBC 라이브러리 구현하기 - 1단계] 기론(김규철) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ResultSetWrapper.java
- jdbc/src/main/java/nextstep/jdbc/util/DataConverter.java
- jdbc/src/main/java/nextstep/jdbc/util/SqlArgumentConverter.java
> [JDBC 라이브러리 구현하기 - 1단계] 스컬(김윤기) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/resources/cleanup.sql
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/support/DataAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/support/StatementUtils.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 열음 😄 리뷰어와 리뷰이로 만나보기는 처음이네요!
나노단위 리뷰를 해주겠다고 하셨는데 열음의 리뷰를 기대해보도록 하겠습니다 👀 
나만의 JdbcTemplate을 만드는 미션이긴 하지만 메서드의 입출력 부분은 실제 JdbcTemplate 클래스의 메서드 시그니처를 따오고, 구현만 제 마음대로 해보았습니다 :) 그래서 예외 처리나 이런 부분도 최대한 스프링을 따라가려고는 했는데요, 실제 스프링은 DataAccessException 하위에 여러 계층구조로 예외를 관리하는데 저는 그 정도 까지는 무리라고 생각해서 SQLException을 전부 DataAccessException으로 퉁치는 정도로 만족했습니다 :)
리뷰 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 1단계] 오찌(오지훈) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/UserRowMapper.java
- jdbc/src/main/java/nextstep/jdbc/Connector.java
- jdbc/src/main/java/nextstep/jdbc/DataAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/FindExecutor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcConnector.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/UpdateExecutor.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultException.java
- jdbc/src/main/java/nextstep/jdbc/exception/ImpossibleSQLExecutionException.java
- jdbc/src/main/java/nextstep/jdbc/exception/InvalidResultSizeException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 제로! 에덴입니다 😄 
잠실에서 자주 만났는데 이렇게 또 만나게 되네요!
1단계 기능 구현만 호다닥 해서 리뷰 요청 드립니다.
연휴 즐겁게 보내시고, 따끔한 리뷰 기다리겠습니다 🙇
> [JDBC 라이브러리 구현하기 - 1단계] 에덴(김성산) 미션 제출합니다.

- README.md
- app/build.gradle
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/resources/schema.sql
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/support/Crew.java
- jdbc/src/test/java/nextstep/support/DataSourceConfig.java
- jdbc/src/test/java/nextstep/support/DatabasePopulatorUtils.java
안녕하세요 클레이!
승팡입니다 😄  좋은 월요일 보내고 계신가요?
전략패턴으로 구현해보려다 템플릿 콜백 패턴을 알게되어서
템플릿 콜백 패턴으로 구현해봤습니다!
리뷰 잘 부탁드립니다 :)
> [JDBC 라이브러리 구현하기 - 1단계] 승팡(김승래) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserMapper.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/config/DataSourceConfig.java
- jdbc/src/test/java/nextstep/config/DatabasePopulatorUtils.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/User.java
- jdbc/src/test/java/nextstep/jdbc/UserMapper.java
- jdbc/src/test/resources/schema.sql
안녕하세요 필즈~ 반갑습니다!!
미션 요구사항 만족하여 PR 보냅니다.
`JdbcTemplate`의 try-catch 중복 제거 및 리팩터링 부분은 2단계여서 2단계에 반영하려고 합니다. ㅎㅎ!
리뷰 잘 부탁드립니다. 🙇
> [JDBC 라이브러리 구현하기 - 1단계] 애쉬(김동호) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStater.java
- jdbc/src/main/java/nextstep/jdbc/ResultSetExtractor.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> [JDBC 라이브러리 구현하기 - 1단계] 제로(공재호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCreator.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> [JDBC 라이브러리 구현하기 - 1단계] 베루스(정진혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> [JDBC 라이브러리 구현하기 - 1단계] 케이(김태현) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/utils/DataAccessUtils.java
티키 안녕하세요! 우선 요구사항 만족하는걸 최우선으로 코드 작성해봤어요. 리뷰 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 1단계] 찬(김찬) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/DataSourceConfigForTest.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestDataSourceConfig.java
- jdbc/src/test/resources/schema.sql
- jdbc/src/test/resources/truncate.sql
안녕하세요 오리! 아리입니다👋
꽤 오랫동안 뵙지 못한 것 같은데 잘 지내고계시죠?
저는.. 나름... 잘지내고있습니다.. 아마도요..ㅎㅎㅎ
구현하고나니 코드도 많이 더럽고 중복 코드도 많지만...! 2단계가 리팩토링이니 미래의 저를 믿고 제출해봅니다! 
잘부탁드립니다🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 1단계] 아리(양유림) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ObjectMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요, 더즈~👋 
리뷰이로 오랜만에 만나게 되어서 반갑습니다 ㅎㅎ 
요구사항은 일단 다 충족시켰습니다  
이번 미션동안 잘부탁드려요!!
> [JDBC 라이브러리 구현하기 - 1단계] 써머(최혜원) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestDataSourceConfig.java
- jdbc/src/test/java/nextstep/jdbc/TestDatabasePopulatorUtils.java
- jdbc/src/test/java/nextstep/jdbc/TestUser.java
- jdbc/src/test/resources/schema.sql
안녕하세요 크리스!
jdbc 미션 1단계를 아래와 같이 구현하여 제출합니다. 
jdbcTemplate 테스트를 진행하기 위해 app 모듈을 import 했더니 순환 참조 문제가 터져서, 테스트용 클래스들을 몇 가지 작성했습니다. 
깔끔하게 코드를 짜려다 보니, 의도치 않게 2단계 리팩토링 부분과 겹치는 부분이 존재하는 것 같습니다. 양해 부탁드립니다. 감사합니다!
> [JDBC 라이브러리 구현하기 - 1단계] 판다(김건웅) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/Parameters.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
포키포키포항항 안녕하세용~~ 주디입니당 😆 
리뷰어로 만나는건 처음이라 신기하네요!
바쁘신 와중에 제 코드리뷰를 해주셔서 감사해요!!! 행포키하세요~
> [JDBC 라이브러리 구현하기 - 1단계] 주디(윤주리) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
바니 잘부탁드립니다~!~! 혹시 JdbcTemplate 테스트 진행하셨다면 어떻게 진행하셨는지 공유해주시면 감사하겠습니다!
>  [JDBC 라이브러리 구현하기 - 1단계] 크리스(공병주) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 디우!
왜이리 오랜만인거죠,,,🥲 이렇게 코드리뷰로 다시 만나게 되어서 정말 반갑네요,,🌟🌟
이번 미션에서는 1단계 기능 요구사항에 맞춰 JdbcTemplate 라이브러리를 만들고, 이를 app 모듈에서 사용할 수 있도록 변경하였습니다.
현재 컨트롤러의 책임이 매우 의심되지만, 1단계 체크리스트에서는 따로 명시하지 않아 app 모듈 내의 코드 변경은 최소화하였어요. 
2단계가 리팩터링인 만큼 그때 해도 된다고 생각했고, 디우 리뷰어님이 리뷰로 남겨준다면 함께 개선해나가고 싶습니다🙇‍♀️🙇‍♀️
데이터의 저장을 `InMemoryUserRepository`가 아닌 H2에 저장하도록 변경했는데요. 
결국 in-memory DB라서 `UserDaoTest`의 각 테스트마다 데이터가 롤백되지 않아 유저 정보를 다 삭제하고 있습니다...ㅎㅎ
과연 좋은 테스트인지 의심이 드네요🧐🧐..(🆘)
그럼 이번 미션 리뷰 잘 부탁드리겠습니다!!
코드에 대해 의문점이나 이상한 점이 있다면 언제든지 편하게 DM 주세요〰️
그럼 디우도 화이팅 하세요!!!🔥
> [JDBC 라이브러리 구현하기 - 1단계] 페퍼(최수연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestUser.java
안녕하세요 배카라~!
미션에서 뵙는건 처음이네요.
`JdbcTemplate`으로 분리해서 구현했더니, try-catch문이 중복되는게 거슬려서 `FunctionalInterface`를 이용해 분리해봤습니다~!
그럼 저를 따끔하게 혼내주세요.
> [JDBC 라이브러리 구현하기 - 1단계] 썬(윤선용) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세요 파랑 :)
오랜만에 미션으로 만나는 것 같네요 😄 
잘부탁드립니다 🙇‍♂️
> [JDBC 라이브러리 구현하기 - 1단계] 오리(최진영) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/Executable.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세요 호호✋🏻 
제네릭과 함수형 인터페이스를 잘 몰라서 고생많이한 미션이였네요🥲
잘부탁드립니다🙏🏻
> [JDBC 라이브러리 구현하기 - 1단계] 잉(유영우) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세요 렉스! 🦖🦖🦖🦖
1단계 요구사항은 만족하여 PR 제출합니다!
JdbcTemplateTest를 작성해보려했는데, 어떤 것을 어떻게 테스트해야할지 감이 안잡히네요ㅠㅠ 렉스는 어떻게 테스트하셨는지 궁금해요.
잘 부탁드립니다! 🌱 🙇‍♀️
> [JDBC 라이브러리 구현하기 - 1단계] 봄(장보미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/resources/schema.sql
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcCallback.java
- jdbc/src/main/java/nextstep/jdbc/JdbcExecutor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> [JDBC 라이브러리 구현하기 - 1단계] 이브(이유정) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/context/ContextLoaderListener.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/resources/clear.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/mock/MockObject.java
- jdbc/src/test/java/nextstep/jdbc/support/DataSourceConfig.java
- jdbc/src/test/java/nextstep/jdbc/support/DatabasePopulatorUtils.java
- jdbc/src/test/resources/clear.sql
- jdbc/src/test/resources/schema.sql
안녕하세요 아스피
우테코 마지막 미션 코드리뷰 잘 부탁드립니다 😊
- UserDaoTest의 모든 테스트 케이스가 통과한다.
- UserDao가 아닌 JdbcTemplate 클래스에서 JDBC와 관련된 처리를 담당하고 있다.
> [JDBC 라이브러리 구현하기 - 1단계] 유콩(김유빈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/RowMapperResultSetExtractor.java
안녕하세요 쿼리치~ 마루입니다! 오랜만이네요!😊
리뷰 잘부탁드립니다!🙇‍♀️
> [JDBC 라이브러리 구현하기 - 1단계] 마루(송채원) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/support/DataSourceConfig.java
- jdbc/src/test/java/nextstep/support/DataSourceConfigForTest.java
- jdbc/src/test/java/nextstep/support/TestUser.java
안녕하세요 그린론💚 파랑입니다💙
JDBC 미션 잘 부탁드립니다ㅎㅎㅎ 호되게 리뷰해주세요!
> [JDBC 라이브러리 구현하기 - 1단계] 파랑(이하은) 미션 제출합니다. 

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/ResultSetCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
페퍼 안녕하세요~! 마지막 미션의 리뷰어로 페퍼를 만나서 영광입니다 🙇‍♀️
이번 미션은 JDBC 처리에서 반복적으로 수행되는 로직들을 분리하는 것에 중점을 두고 진행해보았어요.
method를 구성하는 데에 있어서는 [Spring의 JdbcTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html)을 많이 참고했습니다.
의견 편하게 남겨주시면 열심히 고민하고 반영해보겠습니다! 잘부탁드려요 페퍼 ❤️‍🔥
> [JDBC 라이브러리 구현하기 - 1단계] 포키(권예진) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestUser.java
안녕하세요 알파 매우 반갑네요 잘부탁드려요
1단계 미션 요구사항 맞추면서 미션 진행했습니다!
JdbcTemplate을 구현해보면서 테스트에 대한 부분이 걱정이 많았는데, 지금은 mocking을 통해서 하고 있지만, 실제로는 H2 DB를 연결해서 테스트를 할 수 있었다면 더 좋았을 것이란 생각이 들기도 합니다.
그런데 그렇게 된다면, DAO 테스트와 다를 것이 없을 것으로 보이기도 하고요.
이에 대해서 어떻게 생각하시는지 궁금합니다
> [JDBC 라이브러리 구현하기 - 1단계] 티키(방영호) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/Application.java
- app/src/main/java/com/techcourse/ManualHandlerMapping.java
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/controller/UserSession.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java
- app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/config/DataSourceConfig.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 소주캉 
체크리스트를 구현하면서 처음에는 RowMapper가 아니라 Class를 받는 식으로 구현했었는데 (update(sql, User.class) 처럼요!) 
제 나름대로 만들어보니 리플렉션을 사용해야하고 기본 생성자도 필요하고 그래서 RowMapper를 사용하는 식으로 수정했습니다.
리펙터링은 2단계를 하면서 수정해볼게요!
잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 1단계] 알린(장원영) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/ExecuteStrategy.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/exception/SQLAccessException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 엔지~
미션 요구 사항 2개를 만족했습니다. 근데 테스트 코드를 어떻게 짜야할지 감이 잘안오네요..
스프링 JdbcTemplate 코드를 까봤는데 생각보다 더 복잡해서 약식으로 비슷하게 만들어 봤습니다.
리뷰 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 1단계] 토르(손인준) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/DataAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/Executor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 정!!
이번 2단계가 리팩터링인데 크게 어떤 부분을 개선해야할지 감이 잡히지 않았습니다..ㅠ.ㅠ
Statement Setting하는 부분을 `PreparedStatementSetter` 라는 유틸 클래스로 분리해내어 JdbcTemplate 은 `query()` 와 `update()` 에만 집중할 수 있도록 구현하였습니다.
추가적으로 리뷰이 테스트 코드 참고하여서 JdbcTemplateTest 에서 ResultSet을 mocking해 결과에 대해서도 함께 테스트해볼 수 있도록 개선해보았습니다..!!
혹시 추가적으로 개선해볼만한 점 있다면 편하게 의견주시면 감사하겠습니다..!!
---
잘 부탁드립니다!!
> [JDBC 라이브러리 구현하기 - 2단계] 디우(김동규) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/Callback.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/util/DataConverter.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> [JDBC 라이브러리 구현하기 - 2단계] 스컬(김윤기) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/nextstep/jdbc/DatabasePopulatorUtils.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ResultDataExtractor.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataTypeNotSupportedException.java
- jdbc/src/main/resources/schema.sql
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/User.java
안녕하세요 쿤~ 이스트입니다😄
spring 을 가급적 참고하지 않고 개발하려다가 뭔가 멋대로 해버린 느낌이네요ㅎㅎ
이번 미션 잘 부탁드립니다~~
> [JDBC 라이브러리 구현하기 - 1단계] 이스트(신동훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/repository/UserMapper.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcMapper.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 루키! 알파입니다
부족하지만 리뷰 잘 부탁드리겠습니다
이번에 저는 쿼리별로 처리를 하기 보다는 하나의 메소드로
처리하도록 설계하였는데 루키는 어떤식으로 하셨는지 궁금하네요
> [JDBC 라이브러리 구현하기 - 1단계] 알파(배철환) 미션 제출합니다

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 기론!
이번 미션 잘 부탁드리겠습니다 🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 1단계] 쿼리치(정석윤) 미션 제출합니다.

- README.md
- jdbc/src/main/java/nextstep/jdbc/FindExecutor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcConnector.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementStarter.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
- jdbc/src/main/java/nextstep/jdbc/SimplePreparedStatementStarter.java
- jdbc/src/main/java/nextstep/jdbc/UpdateExecutor.java
- jdbc/src/test/java/nextstep/jdbc/FindExecutorTest.java
- jdbc/src/test/java/nextstep/jdbc/SimplePreparedStatementStarterTest.java
- jdbc/src/test/java/nextstep/jdbc/UpdateExecutorTest.java
안녕하세요 제로! 에덴입니다. 
2단계의 요구사항인 리팩토링 중에서 PreparedStatement 관련하여 value 를 setting 하는 로직과 execute 하는 로직을 묶어 한 단계 더 추상화를 진행하였고, 테스트 케이스도 추가하였습니다!
이번 2단계 코드 리뷰도 잘 부탁드리겠습니다 🙇
> [JDBC 라이브러리 구현하기 - 2단계] 에덴(김성산) 미션 제출합니다.

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/RowMapperCallback.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
매트 안녕하세요~~ 2단계에서 또만나네요ㅎㅎ
이번 미션에서는 다음 사항에 중점을 맞추어서 구현하였습니다!
1. ResultSet에 대한 close 처리가 되어있지 않는 문제점 해결
2. UserDao 테스트 격리 해결
3. queryForObject에 대해서 예외사항에 대한 처리
이번 미션도 잘부탁드립니다 😇
> [JDBC 라이브러리 구현하기 - 2단계] 라쿤(이병훈) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
라쿤 안녕하세요! 주말에 쉬고 공휴일에 하는 미션은 생각보다 재밌네요. 난이도가 할 만해서 실제 JdbcTemplate 만 보면서 구현해보았습니다. 잘 부탁 드립니다🙏
> [JDBC 라이브러리 구현하기 - 1단계] 레오(남궁현) 미션 제출합니다.

- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 봄!!
지난 1단계 미션에 남겨주신 리뷰에 답변남겨두었어요~ 2단계도 잘 부탁드려요~!!!
1단계에서 이미 리팩터링을 진행했기 때문에 이번 2단계에서는 JdbcTemplateTest 하나 추가했습니다~
> [JDBC 라이브러리 구현하기 - 2단계] 이프(송인봉) 미션 제출합니다.

- app/src/main/resources/schema.sql
- jdbc/src/main/java/nextstep/jdbc/Executor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
> [JDBC 라이브러리 구현하기 - 2단계] 파랑(이하은) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
안녕하세요 후디! 
마지막 미션 리뷰어로 뵙게되서 반갑습니다!! 
이번 미션 잘 부탁드립니다! 😃
> [JDBC 라이브러리 구현하기 - 1단계] 쿤(홍동건) 미션 제출합니다.

- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/ResultDataExtractor.java
안녕하세요 쿤!
코드 변화가 많지 않네요...!
2단계도 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 2단계] 이스트(신동훈) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/ThrowingBiFunction.java
아서 안녕하세요~!
2단계로 찾아왔습니다!ㅎ
2단계에는 체크리스트가 존재하지 않고, 리팩터링 방향성에 대한 힌트만 주어졌습니다.
step1 에서 대부분 적용이 되어 있어서 추가작업이 많진 않았습니다.
그래서 이번 step2에서는 JdbcTemplate 내 `command`, `queryForList` 메서드에 대한 중복을 제거하고자 노력해봤습니다.
<br><br>
> `try-with-resources`, `log.debug`, `setParams` 가 중복되고 있었습니다.
달라지는 부분은 setParams 이후 한 문장이었는데요,
CUD의 경우 pstmt.executeUpdate();가 수행되어야했고,
R의 경우 `mapRows(rowMapper, pstmt)`가 수행되어야 했습니다.
<br><br>
- 달라지는 부분만 템플릿화 하는 방법 중 가장 쉬운 선택은 추상 클래스입니다.
- 달라지는 부분만 추상 메서드를 남겨두는 형태입니다.
- 그러나 그 중복을 제거하기 위해 구현체가 여럿 나오는 것은 사용성 측면에서 득 보다 실이 크다고 판단했습니다.
- 그래서 가급적 사용하는 입장에선 변화가 없도록 유지하면서, 내부적으로 코드만 변경해보고자 노력했습니다.
<br><br>
- CUD는 매개변수 하나만 받아서 실행하면 되고, R은 매개변수 둘을 받아서 다른 메서드로 전달해야 했습니다.
- 예외도 감싸줘야 하고, 매개변수의 갯수도 달라지는 지점까지 템플릿화 하는 것이 맞을까 고민이 됐습니다.
- 가령 현재는 2개로 커버가 됐지만, 3개가 필요하면? 4개가 필요하면? 그때마다 인터페이스 수정되고, 코어 코드도 …
> [JDBC 라이브러리 구현하기 - 2단계] 리차드(전형중) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/RowMapperResultSetExtractor.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/PreparedStatementSetterTest.java
- jdbc/src/test/java/nextstep/jdbc/RowMapperTest.java
리버 안녕하세요 ~
2단계에서는 RowMapper와 PreparedStatementSetter 함수형 인터페이스 생성해 보았어요!
이번 리뷰도 잘 부탁드려요! 😃
> [JDBC 라이브러리 구현하기 - 2단계] 그린론(유재서) 미션 제출합니다.

- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcAction.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세용 슬로,,,
리팩토링 해야할 부분이 많아보이지는 않아 살짝만 바꿨어요!
그리고 테스트 격리를 다른 방식으로 구현해봤어요!
부족한 부분 지적해주시면 감사하겠습니다~
> [JDBC 라이브러리 구현하기 - 2단계] 클레이(양동주) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요. 이종석 닮은꼴 조시 ~
지난번에 주고 받은 내용 토대로, 구현 위주로 PR 보내요 !
그때 테스트 코드와 내용 보강해서 고민했던 점 함께 적어두겠습니다.
목요일날 내용 보충해서 다시 리뷰 요청하겠습니다. ☺️
이해주셔서 감사합니다.
> [JDBC 라이브러리 구현하기 - 1단계] 수달(허수진) 미션 제출합니다. 

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapperResultSetExtractor.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSizeDataAccessException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
쿼리치 안녕하세요! 마루입니다😀
1단계에서 이미 많이 리팩터링을 해버린 상태였던 거 같아서😅 좀 더 고쳐야하는 부분들만 리팩터링을 해보았습니다!
- PreparedStatementSetter를 함수형 인터페이스로 선언하고 JdbcTemplate 안에서 구현을 해주었는데요, 따로 구현 클래스를 만들수도 있었지만 그정도까지 하기에 복잡한 로직은 아니라고 생각해서 그렇게 하지 않았습니다!
- RowMapperResultSetExtractor에서 메서드를 리턴 개수에 따라 나누고 예외 상황에 대해서 커스텀 예외를 적용했습니다~
리뷰 잘부탁드립니다🙇‍♂️
+) 깜빡하고 리뷰 요청을 안보냈나봐요,, 늦게 요청 드립니다.. 주륵
> [JDBC 라이브러리 구현하기 - 2단계] 마루(송채원) 미션 제출합니다.

- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/java/com/techcourse/support/jdbc/init/ResourceNotFoundException.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultException.java
- jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSizeException.java
- jdbc/src/main/java/nextstep/jdbc/exception/InvalidStatementException.java
- jdbc/src/main/java/nextstep/jdbc/exception/ParameterBindingException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 배카라~!
1 단계 때 이미 함수형 인터페이스로 추출했었어서 2단계 때 별로 적용할게 없네요 😢
사소한 변경점만 적용했습니다~! 매의 눈으로 확인 부탁드려요
저를 혼내주세요.
>  [JDBC 라이브러리 구현하기 - 2단계] 썬(윤선용) 미션 제출합니다.

- README.md
- app/src/test/java/com/techcourse/support/jdbc/DatabaseTruncateUtils.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
안녕하세요 범고래!! 아스핍니다 :)
1단계 피드백 감사했습니다!!ㅎㅎ
이번에도 잘 부탁드릴게요!!
> [JDBC 라이브러리 구현하기 - 2단계] 아스피(신동석) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
앤지 안녕하세요!
1단계 때 템플릿 패턴을 적용했더니 크게 변경할 부분이 없어보이네요. 힌트 부분을 봤는데 1단계 때 제 코드랑 달라서 따라가는 것도 조금 안맞는 것 같다는 생각을 했습니다. 구조 바꿀 부분 알려주시면 바로 반영해볼게요!
> [JDBC 라이브러리 구현하기 - 2단계] 토르(손인준) 미션 제출합니다. 

- README.md
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- jdbc/src/main/java/nextstep/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/core/JdbcTemplateTest.java
안녕하세요 릭! 매트입니다 😃
2단계 요구사항을 확인해보니 대부분 1단계에서 진행한 부분이 많아 크게 수정할 부분이 없네요.. 🥲 이번에는 무언가 코드를 추가하기 보다 `JdbcTemplate` 라이브러리를 만드는 개발자의 입장에서 적절한 책임과 기능을 가지고 있는지 고민하였습니다.
우선 직접 만든 JdbcTemplate에서 의존하는 객체에 대해 살펴보았습니다. 거의 대부분 같은 패키지에 소속되어 있거나 `JDBC API 표준에 명세된 클래스`를 사용한 것 같아서 외부와의 의존성을 최소화 했다고 판단합니다.
릭이 저번에 H2 DB 의존성을 활용한 테스트 작성을 추천해주셨는데요, 저는 JdbcTemplate 입장에서 특정 DB에 대한 의존성이 없이 범용적으로 사용될 것을 고려하여 mocking 하는 방식을 유지하였습니다! 추가적으로 자원이 정상적으로 해제되었는지에 대한 여부까지 추가하였습니다.
실제 Spring에 JdbcTemplate 테스트 코드를 살펴보면 전반적으로 mocking을 활용한 것을 확인할 수 있었습니다.
[JdbcTemplateTests](https://github.com/spring-projects/spring-framework/blob/main/spring-jdbc/src/test/java/org/springframework/jdbc/core/JdbcTemplateTests.java)
이번 리뷰도 잘 부탁드립니다! 감사합니다 🙇‍♂️
> [JDBC 라이브러리 구현하기 - 2단계] 매트(최기현) 미션 제출합니다.

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/element/JdbcExecutor.java
- jdbc/src/main/java/nextstep/jdbc/element/PreparedStatementCallBack.java
- jdbc/src/main/java/nextstep/jdbc/element/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/element/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/element/ResultSetCallback.java
안녕하세요, 레넌!
2단계 리팩토링 구현했습니다.
이번에도 잘 부탁드려요!
> [JDBC 라이브러리 구현하기 - 2단계] 헌치(박지우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 렉스 🦖 
2단계 리팩토링 및 JdbcTemplate 테스트 추가, 1단계에 남겨주신 리뷰 반영하여 PR 제출합니다.
이번 단계도 잘 부탁드려요 🙇‍♀️
> [JDBC 라이브러리 구현하기 - 2단계] 봄(장보미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcExecutor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 토닉!
2단계에서는 이전 단계에서 주신 피드백 위주로 리팩토링하다 보니 코드 변경이 많지 않네요.
피드백 받고 남은 단계도 진행하면서 계속 리팩토링해 나가겠습니다😀
[1단계 PR](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/106)에서 질문 주셨던 부분들은 코멘트로 답변 남겨놨어요!
이번에도 잘 부탁드립니다😄
> [JDBC 라이브러리 구현하기 - 2단계] 이브(이유정) 미션 제출합니다. 

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 에덴! 앤지입니다! 2단계에서 다시 만나뵙게 되었네요 😄 
이번 미션에서는 크게 두가지를 구현했어요!
1. 1단계 때 리뷰주신 query() 와 queryForObject() 중복 줄이기
2. PreparedStatementSetter 구현
특히 리뷰주셨던 1번을 제가 에덴이 말씀해주신 방향처럼 반영했는지 궁금해요!
또한 2번 PreparedStatementSetter도 구현방향이 맞는지 궁금하네요.
그럼 이번 미션도 잘 부탁드려요 😄  감사합니다 🙇
> [JDBC 라이브러리 구현하기 - 2단계] 앤지(손수민) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/Executor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
- jdbc/src/test/java/nextstep/jdbc/TestDataSourceConfig.java
안녕하세요 오리! 아리입니다👋
2단계 에서는 1단계에서 추가로 남겨주셨던 피드백을 적용하고, Executor 인터페이스를 통해 중복 로직을 제거했습니다!
천천히 시간 되실때 리뷰 부탁드립니다~
감사합니다🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 2단계] 아리(양유림) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/support/DataAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/support/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/support/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/support/DataAccessUtilsTest.java
안녕하세요 칙촉!
2단계 리팩터링에서는 요구사항이 없고 리팩터링에 대한 힌트만 제공되었는데요.
템플릿 콜백 패턴을 활용해서 try-with-resources 의 중복을 최대한 제거해봤습니다.
스프링에서 제공하는 JdbcTemplate을 참고하기에는 너무 범용적인 것 같아서 목적에 맞는 선에서만 리팩터링을 진행했습니다.
편하게 리뷰해주시고 궁금한 사항이 있으면 커멘트 혹은 DM으로 알려주세요
> [JDBC 라이브러리 구현하기 - 2단계] 아서(김현태) 미션 제출합니다.

- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- jdbc/src/main/java/nextstep/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/exception/ConnectionOccupationException.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/MultipleRowException.java
- jdbc/src/main/java/nextstep/jdbc/exception/ParameterSettingException.java
안녕하세요 베루스! 2단계 미션 제출합니다.
1단계 때 템플릿 콜백 패턴을 이미 적용해 버려서 변경사항이 많지 않습니다..
커스텀 예외 생성하고 조금의 코드 리팩터링만 하였습니다!
많은 지적 부탁드립니다 🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 2단계] 코린(유현지) 미션 제출합니다. 

- README.md
- jdbc/src/main/java/nextstep/jdbc/DataAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/DataAccessUtilsTest.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요. 클레이!
저번 미션에서 적용한것들이 많아서 크게 변경된 것은 없습니다.
클레이가 리뷰 남겨주신 내용을 답변하다가 iterator().next() 부분을 좀더 확장성있게
DataAccessUtils클래스로 분리하여서 Collections로 받게 변경했습니다.
그리고 final 키워드 빠진것들 수정한게 전부같네요!
3단계를 같이 하는것보다 제가 놓친게 있는지 없는지 체크하는게 좋을 것 같아서 2단계만 따로 보냅니다
잘부탁드립니다!
> [JDBC 라이브러리 구현하기 - 2단계] 승팡(김승래) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/nextstep/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/dao/DataAccessUtilsTest.java
- jdbc/src/test/java/nextstep/jdbc/core/ArgPreparedStatementSetterTest.java
- jdbc/src/test/java/nextstep/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/core/SimplePreparedStatementCreatorTest.java
스컬 안녕하세요~!
1단계에서 객체 분리를 해놔서 크게 달라진점이 없네요ㅜㅜ
1단계 리뷰내용 반영했어요 ㅎㅎ
이번 리뷰도 잘 부탁드려용 ☠️☠️☠️
> [JDBC 라이브러리 구현하기 - 2단계] 라라(박세은) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- jdbc/src/main/java/nextstep/jdbc/Executor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 알린~
리팩터링을 진행해보았습니다~!
궁금하신 부분이나 개선해야할 부분이 있으면 리뷰남겨주세요~
> [JDBC 라이브러리 구현하기 - 2단계] 레넌(조형래) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/Executor.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
- jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/exception/InvalidDataSizeException.java
- jdbc/src/main/java/nextstep/jdbc/exception/InvalidSqlException.java
- jdbc/src/main/java/nextstep/jdbc/exception/NoSuchDataException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 더즈 🙇 엄청 오랜만에 리뷰 요청드리네요
저번에 2단계를 어느정도 진행해 둔 상태였어서, 
- 중첩되는 `try~catch` 문과 예외 변환을 `탬플릿 콜백 패턴`을 이용해 간소화
- 적절한 커스텀 예외 선언 
위 두 사안을 중점으로 진행했습니다    
이번에도 잘부탁드려요!
> [JDBC 라이브러리 구현하기 - 2단계] 써머(최혜원) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/MethodInvoker.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 제로! 에덴입니다 😄 
3단계를 구구가 잘 설명해주셔서 따라가면서 하니 조금 일찍 구현하게 됐어요!
근로때문에 바쁘실텐데 코드 리뷰 여유롭게 해주셔도 됩니다!! 
그럼 이번에도 따끔한 리뷰 부탁드리겠습니다 🙇
> [JDBC 라이브러리 구현하기 - 3단계] 에덴(김성산) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- app/src/test/resources/schema.sql
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 배카라~!
3단계를 끝마치고 PR 보냅니다!
저를 혼내주세요.
> [JDBC 라이브러리 구현하기 - 3단계] 썬(윤선용) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 차리~
3단계 요구사항 충족시킨거 같아서 제출합니다
리뷰 잘부탁드립니다~
> [JDBC 라이브러리 구현하기 - 3단계] 기론(김규철) 미션 제출합니다.

- JdbcTemplate-Study.md
- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementExecutor.java
- jdbc/src/main/resources/logback.xml
- jdbc/src/main/resources/schema.sql
아서 안녕하세요~! 🎶
마지막 미션의 마지막 step이네요..!!
이번 단계에서는 JdbcTemplate의 실제 구현을 분석해보았습니다.
분석 결과는 [여기](https://github.com/HJ-Rich/jwp-dashboard-jdbc/blob/step3/JdbcTemplate-Study.md)에 작성해두었습니다.
참고한 내용을 토대로 이전 단계에서 피드백주셨던 내용도 개선하여 반영해두었습니다.
체크리스트는 아래와 같습니다.
잘부탁드립니다, 감사합니다 아서! 😃
> [JDBC 라이브러리 구현하기 - 3단계] 리차드(전형중) 미션 제출합니다

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 오리! 
2단계 리뷰요청을 보낸줄 알고 기다리고 있었는데 제가 보내지 않았네요..ㅎㅎㅎ
뒤늦게 확인했는데도 빠르게 머지해주셔서 감사합니다~
기다리는 사이에 3단계를 구현하고 있어서 빠르게 리뷰요청 보내요!
이렇게 하는 것이 맞나 싶지만... 틀린 부분이 있으면 오리가 지적해주실거라 믿고 제출해봅니다!
그럼 마지막 단계도 잘부탁드려요🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 3단계] 아리(양유림) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 루나!
2단계는 코드 수정이 크게 없어서, 3단계와 묶어서 제출합니다!
이번 단계도 잘 부탁드립니다🙆‍♂️
> [JDBC 라이브러리 구현하기 - 2, 3단계] 아키(허영운) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcSupporter.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/support/TransactionInvoker.java
- jdbc/src/main/java/nextstep/jdbc/support/TransactionTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 필즈~
3단계 미션을 단계별로 음미하며 따라가려고 했는데 저한테는 좀 어렵다고 느껴졌네요 ㅎㅎ;
이번에도 좋은리뷰 부탁드립니다! 🙇
> [JDBC 라이브러리 구현하기 - 3단계] 애쉬(김동호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/Executor.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
> [JDBC 라이브러리 구현하기 - 2, 3단계] 크리스(공병주) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 연로그~
3단계 구현을 마쳐서 PR보냅니다!
이번에도 잘 부탁드립니다!!
> [JDBC 라이브러리 구현하기 - 3단계] 렉스(오성원) 미션 제출합니다.

- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserDao.java
- app/src/test/java/com/techcourse/service/TransactionUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- app/src/test/java/com/techcourse/support/DatabaseCleanUp.java
- jdbc/src/main/java/nextstep/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/support/TransactionService.java
- jdbc/src/test/java/nextstep/jdbc/support/TransactionServiceTest.java
베루스 안녕하세요~~ 3단계 구현해서 PR 보냅니다 :)
이번에도 좋은 리뷰 부탁드립니다~!! 🙇🏻‍♀️
> [JDBC 라이브러리 구현하기 - 3단계] 코린(유현지) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcExecuteException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/KeyHolder.java
- jdbc/src/main/java/nextstep/jdbc/KeyHose.java
- jdbc/src/main/java/nextstep/jdbc/ObjectFactory.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/main/java/nextstep/jdbc/SqlExecutor.java
- jdbc/src/main/java/nextstep/jdbc/SqlPreProcessor.java
- jdbc/src/main/java/nextstep/jdbc/SqlResultProcessor.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
유콩 안녕하세요!! 늦게 제출해서 죄송합니다!! 겨우 시간 맞췄네요..
생각보다 많이 해매서 늦어졌습니다.. 기능은 돌아가는데 코드도 정리가 안됐네요..
코드보시면서 궁금하신점 dm주세요!! 감사합니다!!
> [JDBC 라이브러리 구현하기 - 2,3단계] 조시(조현근) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/DatabaseAccessUtils.java
- jdbc/src/main/java/nextstep/jdbc/EmptyResultDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/ArgumentPreparedStatementSetterTest.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestUser.java
안녕하세요 호호✋🏻 2단계로 다시 찾아 뵙게 돼서 영광입니다. 
날씨가 쌀쌀해졌는데 감기 조심하세요🙏🏻
> [JDBC 라이브러리 구현하기 - 2, 3단계] 잉(유영우) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
렉스 안녕하세요! 🦖 
2단계 PR을 새벽에 올려서 다음날 아침에 리뷰요청해야지! 하고 까먹었는데 리뷰해주셔서 감사해요 ㅠㅠ 
마지막 단계도 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 3단계] 봄(장보미) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 기론! 저번에 말씀드린대로 2, 3단계 함께 구현하여 제출합니다!
이번 미션도 잘 부탁드리겠습니다 🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 2, 3단계] 쿼리치(정석윤) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
쿼리치 안녕하세요~! 3단계도 리뷰 잘 부탁드립니다😀
2단계 리뷰에 대한 수정은 차차 채워보도록 하겠습니다!
> [JDBC 라이브러리 구현하기 - 3단계] 마루(송채원) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementFactory.java
- jdbc/src/main/java/nextstep/transaction/TransactionTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> [JDBC 라이브러리 구현하기 - 2, 3단계] 조조그린(조한석) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 후디! 
지금까지 꼼꼼하게 리뷰를 주셔서 감사합니다!
3단계도 잘 부탁드립니다.
> [JDBC 라이브러리 구현하기 - 3단계] 쿤(홍동건) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/KeyHolder.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementCreator.java
- jdbc/src/main/java/nextstep/jdbc/PreparedStatementExecutor.java
오찌 ㅎㅎ
마감 직전에 PR 보냅니다
2단계는 특별히 할게 없는 것 같아서 3단계를 집중적으로 했습니다~
> [JDBC 라이브러리 구현하기 - 2,3단계] 베루스(정진혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/core/JdbcTemplateTest.java
안녕하세요 릭! 매트입니다 😃
3단계 잘 부탁드려요!!
> [JDBC 라이브러리 구현하기 - 3단계] 매트(최기현) 미션 제출합니다. 

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 썬!
2단계만 구현하고 PR 날리려다 너무 조금 변경된 것 같아서 3단계랑 함께 보내게 되었습니다..! 🙇‍♂️
잘부탁드립니다! :)
> [JDBC 라이브러리 구현하기 - 2, 3단계] 범고래(조충범) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/DefaultStatementSetter.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/element/JdbcExecutor.java
- jdbc/src/test/java/nextstep/jdbc/DefaultStatementSetterTest.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/Wrapper.java
> [JDBC 라이브러리 구현하기 - 3단계] 헌치(박지우) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/service/ApplicationUserService.java
- app/src/main/java/com/techcourse/service/TransactionUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/ApplicationUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/DataAccessException.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 알파 이번에 트랜잭션 미션을 구현해봤습니다.
내용적으로 어렵고 기술적으로 까다로운 내용이 있었지만, 최대한 공부해보고 간단하게 구현해봤습니다
마지막 미션 힘내세요
> [JDBC 라이브러리 구현하기 - 3단계] 티키(방영호) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 케케케!
저 짱군데요!
하다보니 2, 3단계를 한번에 했네요...
트랜잭션 부분 항상 궁금했는데 직접 구현해보니 재밌었습니다!
> [JDBC 라이브러리 구현하기 - 3단계] 짱구(신승철) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> [JDBC 라이브러리 구현하기 - 3단계] 정(정진우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 엔지~
지난 번 리뷰 남겨주신것 이번 단계에서 반영해봤습니다ㅎㅎ
이번 리뷰도 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 3단계] 토르(손인준) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 야호!
제출이 많이 늦어졌네요..ㅠㅠ
사실 오늘이 막 PR 마감인줄 몰랐습니다..
급하게 숙제식으로 미션을 하느라 신경을 많이 못썼는데요,
남은 시간동안 추가적인 학습 해보면서 미션에 아는 만큼 반영해보겠습니다!
그럼 이번에도 잘 부탁드려요!
> [JDBC 라이브러리 구현하기 - 2,3단계] 알렉스(이영환) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
안녕하세요 이프! 열음입니다ㅎㅎ
3단계 구현을 모두 마쳐서 제출합니다:)
사실 금요일이 마감인줄 알았는데.. 오늘이라고 하더라구요...?  호다닥 진행해보았습니다ㅎ.. 
2단계는 하려고 했는데 도저히 뭘 해야할지 생각이 안나서 그냥 3단계랑 같이 해버렸어요'-'..
금요일까지 좀 더 학습해보고 도입할 만한 부분들 도입하고 있겠습니다:)
이번에도 잘 부탁드립니다! 감사합니다~
> [JDBC 라이브러리 구현하기 - 2,3단계] 열음(이주형) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/TransactionSupplier.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionalUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 봄~~~~ 3단계 미션 제출합니다~!!! 잘 부탁드려요~
> [JDBC 라이브러리 구현하기 - 3단계] 이프(송인봉) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
- jdbc/src/main/java/nextstep/jdbc/transaction/TransactionConsumer.java
- jdbc/src/main/java/nextstep/jdbc/transaction/TransactionContext.java
- jdbc/src/main/java/nextstep/jdbc/transaction/TransactionFunction.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/transaction/TransactionContextTest.java
안녕하세요 슬로!
3단계 트랜잭션을 적용해봤어요!
템플릿 콜백 패턴을 이번 트랜잭션 컨텍스트에 적용해봤어요.
이번에도 잘 부탁드립니다.
> [JDBC 라이브러리 구현하기 - 3단계] 클레이(양동주) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/main/java/org/springframework/jdbc/core/exception/JdbcTemplateException.java
안녕하세요 오리! 
반갑습니다 
미션을 처음 봤을땐 이게 뭔가 싶었는데 보다보니 이전 레벨에서 써먹었던 RowMapper나 그런 것들이 떠올라서 생각보다는 간단하게 진행할 수 있었던 것 같습니다 
그래서 사실 별 내용은 없는 것 같습니다
미션 1단계 진행하면서 가장 오래 고민한게 RowMapper의 rowNum인데...이걸 어따쓰는지 상상이 안되서 코드를 까보니 그냥 반복문에서 rs.next() 호출 시마다 그냥 1씩 늘린 값을 지정해줄 분이더라고요..?
이게 필요한가 싶어서 일단 제거했습니다
리뷰 잘 부탁드립니다
> [JDBC 라이브러리 구현하기 - 1단계] 지토(김지민) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/main/java/org/springframework/jdbc/exception/IncorrectResultSizeDataAccessException.java
- study/src/main/java/aop/config/DataSourceConfig.java
- study/src/main/resources/application.yml
안녕하세요 모디!
이번 미션이 4단계까지 있어서 빠르게(?) 제출했습니다.
일단 돌아가게 만들고 JdbcTemplate의 중복 코드를 없애는 방식으로 구현했습니다.
리뷰 잘 부탁드립니다~ [리뷰 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/276/files/06379e5dfc39fca37fa096cc17bb04273303e594..343b1f91a61938673701d342dd9f27e90b45b360)
> [JDBC 라이브러리 구현하기 - 1단계] 엔초(권예진) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 오도 반갑습니다 !
예전에 3인 페어로 봤었는데 또 뵈어서 반가워요 ~~
이번에 jdbctemplate 구현을 해보았는데요 !
많이 써보긴 했지만 이걸 구현하는 건 또 다른영역이라 어렵네요.
Jdbctemplate을 써본지도 쫌 되었고요..ㅋㅋㅋㅋ
이번에 구현하면서 왜 `rowMapper`가 필요했는지 생각해보는 시간을 가졌어서 좋았습니다.
리뷰 잘 부탁드려요 !
> [JDBC 라이브러리 구현하기 - 1단계] 하디(전동혁) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 애쉬! 연휴를 앞둔 설레는 하루네요 하하
rowMapper 를 이용해 미션 진행했습니다!
jdbcTemplate 에서 2중 try 문이 있는데, 이를 개선할 필요가 있어보이네요.
resource close 를 편하게 하기 위해 try with resources 를 사용했습니다!!
그럼 즐거운 연휴 보내십셔🫡
> [JDBC 라이브러리 구현하기 - 1단계] 레오(차영호) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 히이로 
코드로 만나뵙게 되서 반갑습니다!!
step1은 최대한 LMS에 있는 요구사항만을 지키려고 했어요
그래서 코드를 보시면서 "이건 왜 그랬지?" 라는 부분이 많으실 것 같아요.
step2에서 리팩토링하면서 어떤 점이 불편해서 이렇게 만들었다를 느껴보고 싶어서 이번 미션은 이렇게 진행했습니다.
이번 리뷰 감사히 잘 받겠습니다 !
> [JDBC 라이브러리 구현하기 - 1단계] 우르(김현우) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 리뷰어 채채~
jdbcTemplate을 다 까먹어버려서 메서드 시그니처가 어떻게 생겼는지좀 보고 만들어보았습니다~
리뷰 잘 부탁드립니다~
> [JDBC 라이브러리 구현하기 - 1단계] 이리내(성채연) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 지토, 저문입니다 :)
리뷰어로 지토를 만나뵙게 되어 영광이네요 ㅎㅎ
많이 배우는 시간이 되도록 최선을 다해보겠습니다!
먼저 1단계는 구현하면서 큰 고민을 하지않고 요구사항을 충족하는 방향으로 진행했습니다.
UserDaoTest를 통과시키는데 목적을 두고 진행했는데, 추상화가 잘 이루어졌는지 모르겠네요..ㅎㅎ
구현하는 와중에 질문이 있어서 남겨두겠습니다!
추상화를 하는 과정에서 try-with-resources로 변경했는데, 구조 상 ResultSet을 깔끔하게 처리하는 방법이 생각나지 않더라구요...
JdbcTemplate에 있는 ResultSet에 대한 자원을 깔끔하게 처리할 수 있는 방법이 없을지 고민입니다!
추석 잘 보내고 계신가요? 배부르고 든든한 추석 보내시길 바랍니다🌝
1단계 리뷰 잘 부탁드립니다🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 1단계] 저문(유정훈) 미션 제출합니다.

- .gitignore
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecution.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- study/build.gradle
- study/src/main/java/aop/config/DataSourceConfig.java
- study/src/main/java/connectionpool/DataSourceConfig.java
- study/src/main/resources/application.yml
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
안녕하세요 도기!!
잠실에서는 잘 지내시나요?? 
오랜만입니다😃
**JDBC Template** 구현을 했습니다.
- `executeUpdate`: INSERT, UPDATE, DELETE 때 사용
- `queryForObject`: SELECT 때 사용
- `T` 타입의 `RowMapper`를 파라미터로 받아서 `T` 타입을 리턴합니다
많이 배우겠습니다!!
> [JDBC 라이브러리 구현하기 - 1단계] 연어(황재현) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 우르!
JdbcTemplate 을 열심히 구현해봤습니다 😊
리뷰 잘 부탁드립니다 😁
> [JDBC 라이브러리 구현하기 - 1단계] 오도(문민혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/ResultSetMapper.java
포이 안녕하세요~! 레벨 3 이후로 한번도 못뵈었네요 잘지내시나요?ㅎㅎ
리뷰어로 뵙게되어 방갑네요~!
이번 미션 잘부탁드립니다~!
> [JDBC 라이브러리 구현하기 - 1단계] 채채(신채원) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- study/src/main/java/aop/config/DataSourceConfig.java
- study/src/main/resources/application.yml
안녕하세요, 오션 🌊
코드로 인사드리는건 오랜만이네요 ^^;
이렇게 보니 되게 되게 반갑네요 ㅋㅋ 🙃
근로 페어하던게 엊그제 같은데 벌써 레벨4 막바지에 다다르고 있어요 ㅠㅠ 
1단계는 2단계의 리팩토링 여지를 조금 남기고 구현했어요! 
함수형 인터페이스와 제네릭이 너무 어렵네요 전 😭 
리뷰는 당연히 천천히 여유롭게 하셔도 됩니다 ㅎㅎ 
추석 연휴 잘 보내시고 🍁🌕 
맛있는 것도 많이 드시고 오십쇼 🍚🥘
> [JDBC 라이브러리 구현하기 - 1단계] 라온(문채원) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 썬샷~
이렇게 썬샷의 리뷰를 받을 수 있게 되어서 영광입니다!
이번 미션 잘부탁드립니다~
> [JDBC 라이브러리 구현하기 - 1단계] 필립(양재필) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/resources/schema.sql
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
- jdbc/src/main/java/org/springframework/jdbc/core/SingleResult.java
- jdbc/src/main/java/org/springframework/jdbc/core/SqlExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/test/java/config/DataSourceConfig.java
- jdbc/src/test/java/init/DatabasePopulatorUtils.java
- jdbc/src/test/java/org/springframework/jdbc/core/PreparedStatementCreatorTest.java
- jdbc/src/test/java/org/springframework/jdbc/core/SingleResultTest.java
- jdbc/src/test/resources/schema.sql
안녕하세요 허브, 허브입니다. 추석 연휴 시작과 함께 상쾌한 리뷰 요청 드려요. 
이번 단계에서는 1단계 리뷰 반영, try-with-resources 활용, 트랜잭션 관리에 중점을 두고 진행했습니다.
특히 트랜잭션은 나름 찾아보며 진행했는데, JDBC로 트랜잭션을 관리한 경험이 없어서 제대로 한 건지 의문이 있네요 ㅎㅎ;;
1단계 리뷰 덕분에 놓치고 있던 지식들에 대해서 학습할 수 있었습니다. 감사합니다👍
허브의 생각보다 많이 부족하기 때문에 '이거 알고 있으려나?' 싶은 것도 다 짚어 주셔도 좋습니다.
이번 리뷰도 잘 부탁드려요 허브~ 즐거운 추석 보내셔요!
> [JDBC 2단계] 민트(유재민) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/main/java/aop/config/DataSourceConfig.java
- study/src/main/resources/application.yml
안녕하세여 민트 ! 케로입니다 🐸
리뷰 잘 부탁드리고 남은 연휴 잘보내세영 ㅎㅎㅎㅎ
이번 1단계에서는 Db Connection과 관련된 내용을 JdbcTemplate으로 옮기고, JdbcTemplate을 재사용 가능하도록 만드는 것에 집중했습니다 !
그럼에도 JdbcTemplate에 반복되는 구문들과 try블럭들이 많아서 좀 더 리팩터링 하고 싶었는데 방법을 모루겠습니다...,,
조언 부탁드립니다 !!!!
> [JDBC 라이브러리 구현하기 - 1단계] 케로(김지현) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 다즐!
미션 제출이 좀 늦었습니다ㅠ
남은 연휴 잘 보내시고 편하실 때 리뷰 부탁드리겠습니다!
감사합니다!
> [JDBC 구현 / 1단계] 로이(김덕우) 미션 제출합니다.

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/IncorrectRowSizeException.java
- jdbc/src/main/java/org/springframework/jdbc/RowNotFoundException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
글렌 덕분에 코드뿐 만 아니라 생활건강 상식까지 배워가네요. 
실무에서도 이렇게 성장을 도와주는 동료를 만나고싶네요.
그리고 코드는 바뀐게 거의 없네요. 많이 바뀔줄 알았는데.. 그래도 생각 정도는 별도 코멘트를 남겼어요.
> [jdbc 미션 2단계] 오리(오현서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/jdbc/exception/CannotGetJdbcConnectionException.java
- jdbc/src/main/java/org/springframework/jdbc/exception/DatabaseExecuteException.java
- jdbc/src/main/java/org/springframework/jdbc/exception/EmptyResultException.java
- jdbc/src/main/java/org/springframework/jdbc/exception/NotSingleResultException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 우가~~ 연휴는 잘 보내고 계신가요 ?!
저는 오늘 부산에서 올라왔습니다 😁
2단계는 1단계를 진행할 때 꼼꼼하게? 하려고 해서 그런지 변동사항이 크게 많지 않았어요.
CustomException을 추가했고 JdbcTemplate 테스트를 작성해보았습니다 !
제가 놓친 부분이나 개선할 점이 있으면 가감없이 말씀해주세요 ㅎㅎ
이번 단계도 잘 부탁드립니당 ~
> [JDBC 라이브러리 구현하기 - 2단계] 그레이(김동욱) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 히이로 !!
이전 단계에서의 리뷰 잘 봤습니다
제가 생각과 비슷하셔서 코멘트 읽는데 재밌었습니다.
저는 그냥 `이 부분 힘들겠다`라며 마음 속으로만 생각하고 지나갔는데, 코멘트를 통하여 작성된 글을 보니 또 다르더라구요,,
그 불편한 부분이 대부분 객체 반환 부분이었는데, LMS에 있는 힌트를 보고 재밌게 구현해보았습니다.
이번 미션도 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 2단계] 우르(김현우) 미션 제출합니다. 

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 코코닥! 👃👃🐔
2단계 미션 완료하고 제출합니다!
추석 잘 보내셨나요??
전 간만에 고향 내려가서 친구들 만나고 왔네요. 😁
이번 미션이 리팩터링이던데, 1단계에서 힘을 너무 줘서 그런가, 크게 변경할 점이 없었네요. 😂
따라서 클래스명, 변수명을 실제 스프링에서 사용하는 이름으로 바꾸고 가변 인자를 지원하는 메서드를 추가했습니다.
JdbcTemplate 테스트 코드 또한 작성했는데, Mock을 덕지덕지 사용해서 그런가 테스트를 위한 테스트가 된 느낌이 강하네요. 😂
리뷰 기다리겠습니다!
감사합니다!
---
1단계 PR에 남겨주신 커멘트에 답글 남겨뒀으니 확인하시면 될 것 같네요!
> [JDBC 라이브러리 구현하기 - 2단계] 글렌(전석진) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/support/context/ContextLoaderListener.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/main/resources/drop.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 아마란스 미션을 천천히 하다보니 이제 1단계 리뷰요청을 드리게 되었습니다.
미션은 UserDaoTest가 전부 통과하도록 UserDao를 구현하는데 목표로 뒀는데요, 이때 JdbcTemplate를 이용하면서 구현했습니다.
궁금하거나, 이상한점 등이 있으시면, 제가 확인하고 반영하도록 하겠습니다!
> [JDBC 라이브러리 구현하기 - 1단계] 엔델(김민준) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
안녕하세요 이오
step2에서 중복코드들을 최대한 줄이려고 했습니다.
남은 연휴도 잘 보내시고 이번 리뷰도 잘부탁드립니다 🙂
> [JDBC 라이브러리 구현하기 - 2단계] 파워(송재백) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
마! 규성씨...
2단계 리뷰요청 드립니다!
마! 규성씨께서 주신 피드백을 적용하고나니, 더 할 게 없더군요...
제가 미션을 잘못 이해하고 있는 것은 아닌지, 조금 당황스럽네요...
그렇기에, 만일 틀린점이 있다면 기무사 출신 스파이의 날카로운 눈썰미로 따끔한 피드백 부탁드릴게요!
이번에도 잘 부탁드립니다! 마! 규성씨
> [JDBC 라이브러리 구현하기 - 2단계] 매튜(김재연) 미션 제출합니다.

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapperResultsetExtractor.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/config/TestDataSourceConfig.java
- jdbc/src/test/resources/schema.sql
안녕하세요 스플릿~
2단계는 ResultSetExtractor를 추가한 것 이외에는 1단계에서 다 한것 같습니다.
제가 놓친것이 있을까요....?
JdbcTemplateTest도 추가해봤습니다.
> [JDBC 라이브러리 구현하기 - 2단계] 마코(이규성) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 밀리 추석 연휴는 잘 보내고 계신가요?
이번 단계에서는 지난 번에 비해서 크게 변한 건 없는 것 같습니다..
다만 try-with-resources 부분 중복코드들이 있긴한데, 이를 어떻게 해결하면 좋을지 고민중인데 잘 모르겠습니다 ㅠㅠ
밀리는 중복 코드를 어떻게 해결하실 생각이신가요?
저는 도저히 감이 잡히질 않습니다..!
남은 연휴도 잘 보내시길 바랄게요!
이번 리뷰도 미리 감사합니다🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 2단계] 제이(이재윤) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
가비 안녕하세용 ☀️ 즐거운 연휴 보내고 계시겠지요? 저는 그렇습니다 ㅎ
조금 늦게 리뷰요청을 보냈는데, 변경이 크진 않습니다.
왜냐면 힌트를 보고 리팩토링을 진행하다가 세번째 쯤에서 멈추고 그냥 롤백을 했기 때문입니다.
그 이유는.. 기존에 제가 작성한 것이 꽤 클린해보였기 때문인데요.
뭔가 결국엔 다시 제가 작성한 코드로 돌아갈 것 같아서 되돌려놨습니다.
학습목적으로 템플릿 메서드를 사용해볼 수는 있겠지만, 이게 추상클래스를 사용하는 것과는 어떻게 다른지도 느낌이 잘 오지 않았습니다. ;ㅅ;
결국 미션의 마지막 힌트처럼, 람다를 이용해서 코드를 줄이고 가독성을 높이는 것(=이전 제 코드)이 더 좋다는 판단을 했는데
가비는 미션하면서 어떻게 느꼈나요? 궁금하네요 :D
> [JDBC 라이브러리 구현하기 - 2단계] 로지(윤가영) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 홍고🍊
명절 잘 쇠셨나요?
람다에게 호되게 혼나고 온 가비입니다
저번 리뷰에서 ResultSet 자동종료 직접 찾아주셔서 감사해요
얕은 지식으로 넘어갈 뻔 했는데 덕분에 정확히 알게됐습니다
그래서 이번에는 ResultSet도 try-with-resources 구문에 같이 넣어줬어요
변경사항은 다음과 같아요
- `execute` 메서드 이름을 `update`로 변경
-  PreparedStatementExcutor 인터페이스를 생성하여 람다식으로 try-with-resource 구문 중복제거 (이 메서드 이름이 excute입니당)
- resultset 자원종료 추가
사실 코드 작성하고 나니 이게 제 한계인 것 같아요
홍고 보시기에 개선할 점이나 어색한 점 있으시다면 코멘트 남겨주심 코멘트를 마구마구 달아주심 너무 감사할 것 같습니다
재택근무 끝나고 캠퍼스에서 봬요~
> [JDBC 구현하기 2단계] 가비 미션 제출합니다

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/main/java/org/springframework/jdbc/core/SQLParameters.java
안녕하세요 연어! 추석 잘 보냈나요? ㅎㅎ
레벨2 이후로 캠퍼스가 갈라져서 못봤는데 이렇게 리뷰어와 리뷰이로 만나 다행입니다 ㅎㅎ
일단 후다닥 JDBCTemplate을 구현해 리펙토링 했습니다!
고수 연어님 리뷰 잘 부탁 드려요~~
>  [JDBC 라이브러리 구현하기 - 1단계] 에코(조은찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
안녕하세요 제리! 오션입니다!
이번 미션에서는 
익명 클래스, 함수형 인터페이스를 통해 템플릿 콜백 패턴을 활용해보려고 하였습니다!
가변 인자 를 통해 argument들을 받았습니다. 
람다를 최대한 활용하려고 해보았습니다.
try-with-resources를 사용하여 자원반납처리를 하였습니다!
checked vs unchecked exception 원래 SqlException을 던지던 것을 DataAccessException으로 변환하여 던지도록 처리하였습니다.
감사합니다!  즐거운 연휴 되세요 ㅎㅎ
> [JDBC 라이브러리 구현하기 - 2단계] 오션(김동해) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementGenerator.java
- jdbc/src/main/java/org/springframework/jdbc/core/StatementExecutor.java
리팩토링 재밌네요.
레벨3때는 프로젝트 하느라 자바보다 spring + jpa 랑 더 친했던 시기였는데,
미션하면서 다시 java랑 친해지는 기분이네요 ㅋㅋ
이것 저것 해보다가 그나마 이게 나은것 같아서 제출해봅니다.
이번에도 이리내의 맛도리 리뷰 기대하겠습니다.
> JDBC 2단계 폴로 미션 제출

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/dao/exception/UserHistoryNotFoundException.java
- app/src/main/java/com/techcourse/dao/exception/UserNotFoundException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/exception/DataSourceNotFoundException.java
안녕하세요 엔델!
1단계에서 이미 JdbcTemplate의 기존 형식을 구현해놓다 보니 2단계에서 할 부분이 별로 안보였던 것 같네요.
엔델에게 한 가지 궁금한 점이 있는데 커스텀 예외에 대해선 어떻게 생각하시는 지 궁금해요 :)
리뷰 잘 부탁드립니다!
> [JDBC 라이브러리 구현하기 - 2단계] 아벨(신준혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecute.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecuteTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/ResultSetMappingTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 박스터~
명절 잘 지내셨나요!
이번 2단계 미션도 잘 부탁드릴게요.
```mermaid
flowchart RL
UserDao --- JdbcTemplate
JdbcTemplate --- PreparedStatementExecuteTemplate --- DataSource
JdbcTemplate --- ResultSetMappingTemplate
```
- JdbcTemplate에서 PrepareStatement에 값을 세팅하고 실행하는 부분을 PrepareStatementExecuteTemplate에게 넘겼습니다.
- JdbcTemplate에서 ResultSet 내부 데이터를 RowMapper로 매핑하여 객체로 만드는 부분을 ResultSetMappingTemplate에게 넘겼습니다.
- 예외 발생시 RuntimeException이 아닌 DataAccessException을 던지도록 수정했습니다.
> [JDBC 라이브러리 구현하기 - 2단계] 헤나(박현서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 도치! 추석 연휴 거의 끝나고나서야 2단계 올리네요.. 좋은 리뷰 부탁드립니다🙌
이번 미션에서는 도치가 저번에 말씀해주셨던 피드백 반영하고, 코드 중복을 줄이기 위해서 `PreparedStatementExecutor`를 만들어서 콜백 메소드를 활용해봤습니다! 다만 `queryForOjbect`시에 결과가 2개 이상이면 예외 터지는 로직은 dao 테스트 코드가 터져서 했다가 다시 삭제했습니다ㅠ transaction이 구현되고, 테스트 간에 격리성이 보장이 될때 구현해놓겠습니다!
고생하세요~💪
> [JDBC 라이브러리 구현하기 - 2단계] 두둠(최영훈) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/Mapper.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCaller.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementGenerator.java
- study/src/main/java/aop/config/DataSourceConfig.java
- study/src/main/resources/application.yml
조이~! 안녕하세요🙇‍♂️
미션 제출이 늦어져 시간이 없을 것 같아 2단계까지 진행 후 제출합니다!
늦어져서 죄송해요ㅠㅠ
마지막 연휴 잘 지내고 캠퍼스에서 봬요!!
> [JDBC 라이브러리 구현하기 - 1, 2단계] 제리(권현재) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/SqlRuntimeExceptionTest.java
- app/src/test/resources/schema.sql
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplateBase.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplateExecutionBase.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplateExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/SqlExceptionConverter.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/SqlExceptionType.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/SqlRuntimeExceptionProvider.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/TableNotFoundSqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/exception/ColumnSqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/exception/DataConversionSqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/exception/MethodNotAllowedSqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/exception/SqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/error/exception/SyntaxSqlRuntimeException.java
- jdbc/src/main/java/org/springframework/jdbc/core/mapper/ResultSetObjectMapper.java
안녕하세요 레오~~ 연휴 잘 보내셨나요오!!😄
개인적으로 1단계를 다하고 2단계 요구사항을 봤는데 1단계에서 이미 많이 진행 부분이 많더라구요...ㅎㅎ😊
그래서 요구사항 중 예외처리, 트랜잭션 관리에 집중해서 진행해보았습니다!!😄
1단계 때 주셨던 맛있는 코멘트에 대해서도 최대한 반영해보려고 했습니다!! 이번에도 맛있는 리뷰 부탁드립니다ㅎㅎ👍
> [JDBC 라이브러리 구현하기 - 2단계] 스플릿(박상현) 미션 제출합니다. 

- jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
lms의 리펙토링 부분을 보니 1단계에서 했던 부분이 대부분인 것 같아서 커스텀 예외를 하나 추가해 봤습니다.
제가 놓친 부분이나 보강했으면 좋은 부분을 말씀해주시면 반영하도록 하겠습니다.
감사합니다.
> [JDBC 라이브러리 구현하기 - 2단계] 엔델(김민준) 미션 제출합니다.

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/config/TestDataSourceConfig.java
안녕하세요 땡칠! 0️⃣7️⃣
즐거운 한가위 연휴는 잘 보내고 계신가요? 🌕
1단계에서 너무 많은 상황을 고려하고 코드를 작성하다보니 2단계에서 할게 없어져버렸네요 🥲 🍂
지난 PR에서 남겨주신 내용에 대해 고민하고 답변을 남겨봤습니다~
2단계도 잘부탁드립니다~
> 지난 PR
> - https://github.com/woowacourse/jwp-dashboard-jdbc/pull/297
> [JDBC 라이브러리 구현하기 - 2단계] 주노(최준호) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcCallback.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 제나!
추석 연휴 잘 지내셨나요?? 저는 매우 푹~ㅎ 쉬었습니다 ㅎㅎ
2단계 완료하여 리뷰 요청 드립니다!
1. 제네릭 
저번단계에 리뷰 주셨던 내용 반영했습니다!
- JdbcTemplate에 제네릭 클래스 대신 제네릭 메소드 사용
- UserDao의 RowMapper의 타입 지정 -> User 타입 캐스팅 부분 제거
2. SQLException -> DataAccessException
미션 요구사항대로 checked exception(SQLException)을 unchecked exception(DataAccessException)으로 전환하였습니다!
또한 `queryForObject`의 조회 결과 개수에 대한 예외처리를 위해
뼈대코드에 존재했던 DataAccessException을 상속하는 EmptyResultDataAccessException과 IncorrectResultSIzeDataAccessException도 추가로 구현하였습니다~
3. 템플릿 콜백 패턴을 이용한 중복 로직 제거
이번 단계를 진행하며 가장.. 시간을 많이 투자한 부분인데요..!!
try-catch 쪽 중복 로직을 제거하고자 이런저런 시도 끝에
템플릿 콜백 패턴을 흉내내어 나름대로 만들어보았습니다..ㅎㅎ
**_현재 구조에 대해 제나는 어떻게 생각하시는지 궁금해요!!!_**
이번 단계도 잘 부탁드려용👨‍🎤
> [JDBC 라이브러리 구현하기 - 2단계] 오잉(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutorService.java
- jdbc/src/main/java/org/springframework/jdbc/exception/InvalidDataSizeException.java
안녕하세요 키아라~!
추석은 잘 보내셨나요? 🌕 벌써 연휴가 끝이라니 슬프네요ㅠㅠ
이번 단계는 중복을 어떻게 하면 줄일 수 있을지 많이 고민해봤습니다.
처음에는 방법이 떠오르지 않아 메소드 분리만 하고 끝냈었는데,
PR이 올라오는 것을 참고해보니 '템플릿 콜백 패턴'을 많이들 적용하셨더라구요.
그래서 저도 한 번 적용해보았습니다! 
하지만 오히려 중복을 제거하려다 더 복잡하고 이해하기 어려운 코드가 된 것 같아서 마음에 들진 않네요..
이전의 코드가 중복은 있지만 한 번에 이해하기는 더 쉬운 것 같더라구요. 
그리고 결국 `JdbcTemplate`에서 `ResultSet` 자원을 `close` 하는 부분이 중복이 되었는데 어떻게 해결할 지 잘 모르겠네용.. 😭 
키아라는 어떤식으로 중복을 제거하셨나요?! 
이번 단계도 잘 부탁드립니다 😊
> [JDBC 라이브러리 구현하기 - 2단계] 밀리(김미성) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/exception/DataNotFoundException.java
- jdbc/src/main/java/org/springframework/jdbc/core/exception/JdbcTemplateException.java
- jdbc/src/test/java/org/springframework/jdbc/core/JdbcTemplateTest.java
안녕하세요! 제이미 2번째 리뷰 요청이네요.
몇몇 예외처리를 추가하고, executUpdate에서 id를 반환하는 부분을 제거했습니다.
사실 2단계는 크게 바뀐 부분이 없어요.(2단계에서 해야할 걸 1단계에서 생각보다 많이 했더군요.)
제가 놓친 부분이 있다면, 과감하게 리뷰해주시면 감사하겠습니다.
> [JDBC 라이브러리 구현하기 - 2단계] 홍실(홍혁준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryCallback.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryTemplate.java
안녕하세요 로건 ! 즐거운 한가위 보내셨나요 ?! 🌕
저는 한가위때 가족들과 맛있는걸 많이 먹으러다녀서 2키로는 찐 것 같네요 ㅎㅎ
이번에 QueryTempalte - QueryCallback을 활용해 템플릿 콜백 패턴을 적용해보았습니다!
다만, queryForObject의 예외를 처리하는 과정에서 (결과가 1개가 아닐 때 예외 발생)
UserDaoTest의 findByAccount 메서드가 다른 테스트에서 insert 한 결과의 영향을 받아 실패했어요🥲 (findByAccount했을 때 result가 5개라서 실패)
실패하는 테스트는 우선은 `@Disabled` 처리를 해두었고, 3단계 이후에 트랜잭션을 적용하면서 다시 성공하는 테스트로 작성하겠습니다!
그럼 이번에도 좋은 리뷰 부탁드려요!!
> [JDBC 라이브러리 구현하기 - 2단계] 애쉬(정설희) 미션 제출합니다 

- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 디노~!
너무 늦어서 죄송합니다 ㅠㅠ:(
2단계는 커밋이 거의 없네요..!
잘 부탁드려요!!
> [JDBC 라이브러리 구현하기 - 2단계] 말랑(신동훈) 미션 제출합니다 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/MyRowMapper.java
안녕하세요 비버~ 
2단계 미션 간단하게 구현해서 제출합니다!
이번엔 간단하게 JdbdTemplate의 중복 코드 제거에 신경을 써봤습니다. 
그리고 Null을 반환하지 않도록 수정했습니다!
잘 부탁드립니다:)
> [JDBC 라이브러리 구현하기 - 2단계] 에밀(김대희) 미션 제출합니다 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
베로 안녕하세요! 어느덧 연휴의 절반이 지나가고 있네요.
매년 느끼지만, 대보름쯤의 달은 몇 번 봐도 질리지도 않게 예쁜 것 같아요.
한 해에 한 번 있는 날인 만큼 바쁘시더라도 여유를 갖고 밤하늘을 보며 산책하는 시간을 가져보시는 건 어떠신가요!? (한가위 다음 날 미션을 제출하며)
---
1단계에서 모든 메서드가 CheckedException을 반환하지 않도록 하였고, 또 이에 대한 처리 로직을 한 군데로 몰아 관리지점을 최소화할 수 있도록 코드를 작성했습니다. 이와 더불어 1단계에서 비즈니스외의 로직은 JDBCTemplate 모듈이 관리할 수 있도록 하였기 때문에 이번 단계에서는 큰 수정이 없었네요!
정말 아무 수정도 없이 내는 것 같아 Transaction 에 대해 공부하여 이를 관리하는 책임을 작성해볼까 했는데 3단계에 있길래 그대로 놔뒀습니다. 또, 그럼 커넥션 풀 이라도 만들어볼까 했는데 이것도 4단계에 있길래 그대로 남겼습니다.🤦‍♂️
혹시 제가 2단계에서 놓치고 가는 부분이 있다면 베로가 잡아주시길 바라며 미션을 제출해봅니다.
++남은 연휴도 좋은 시간 되시길 바랍니다!🙆‍♂️
> [JDBC 라이브러리 구현하기 - 2단계] 포이(김보준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
케로케로 안녕하세요🐸 키아라입니다🦁
이번 단계에서는 step1과 비교해서 크게 달라진게 없네요. Optional 반환으로 변경하는 정도로만 수정했어요. 
(step2 도저히 감이 안잡혀서..) 제가 놓친 부분이 있거나 추가했으면 하는 부분이 있다면 말씀해주세요!
잘부탁드립니더~
> [JDBC 2단계] 키아라 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 제리! Transaction 적용하기 미션을 진행하였습니다!
먼저 2단계에서 제리가 남겨주신 코멘트 관련해서 2단계 PR에 의견을 달았고 이번에 수정하였습니다.
Transaction을 구현 하고 동일한 Connection 을 공유하기 위해 Connection 을 계속 파라미터로 전달해야하는 일과 트랜잭션을 적용하면서 다시 비즈니스 로직과 데이터 접근 로직이 섞이는 일이 발생해서 수정을 진행하려고 하였더니 4단계가 딱 그런 미션인 것 같더라고요! 그래서 4단계에서  트랜잭션 동기화 방식을 통해 진행해보려고 합니다.
그래서 3단계에서는 Transaction 적용하는 것에 의의를 두고 진행하였습니다!
감사합니다 제리😀
> [JDBC Transaction 적용하기 - 3단계] 오션(김동해) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/dao/UniqueResultException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryLauncher.java
안녕하세요 주디!
연휴 잘 마무리 중이신가요?
1단계에서 리뷰해주신 try-catch 중복부분을 줄이기 위해서 함수형 인터페이스로 추상화 해보았습니다!
> [JDBC 라이브러리 구현하기 - 2단계] 우가(윤정욱) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/connection/ConnectionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
안녕하세요 도치👋 꼼꼼하게 리뷰해주셔서 놓치는 부분을 많이 잡을 수 있었습니다! 이번에도 좋은 리뷰 부탁드립니다🙇‍♂️
이번 미션에서는 트랜잭션을 구현하는데에 집중했습니다! 비슷한 미션을 해봤어서 다음 단계를 알다보니까 추상화를 깊게 하지  않았습니다. 하다보면 다음 단계처럼 될것 같아서 깊게 추상화 하는건 다음 미션으로 미루었습니다!
그럼 고생하세요💪
> [JDBC 라이브러리 구현하기 - 3단계] 두둠(최영훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
안녕하세요 지토 :)
길었던 연휴를 끝으로 내일이면 다시 시작이네요...ㅎㅎ
연휴 간 푹 쉬셨나요?
2단계 리팩터링에는 최대한 적혀있는 체크리스트에 맞게 구현이 되어있는지를 중점으로 리팩터링 했습니다!
따라서 크게 변동사항이 없는 것 같아요.
예외처리에 관련된 부분이 궁금해서 지토께 여쭤보고 싶습니다.
라이브러리 확장에 <SQLException은 Checked Exception이다. 커스텀 Exception을 추가해서 사용자는 Unchecked Exception이 되도록 변경하자.>라고 적힌 부분이 있었는데요.
이 부분은 어떻게 손을 대야할지 감이 안오더라구요...
지토는 어떤 방식으로 리팩터링 하셨는지 궁금합니다!
이번 리뷰도 잘 부탁드리겠습니다🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 2단계] 저문(유정훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallBack.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
안녕하세요 에단! 이번 미션에서 적용한 부분을 말씀드리겠습니다!
1. 중복 로직을 최소화하기 위해 템플릿 콜백 패턴을 적용하여 리팩토링을 해봤습니다. 
2. 또한 `query`와 `queryForObject`의 로직이 반환 값만 다르기 때문에 이 부분도 합쳐보았습니다.
3. 나의 트랜잭션으로 묶여야 하는 것들은 외부에서 주입한 Connection을 사용하도록 해야 하는데, Connection을 외부에서 주입할 때와 주입하지 않을 때에 로직이 비슷하기 때문에, 이부분도 메서드 추출을 해봤습니다.
감사합니다!! :)
> [JDBC 3단계] 헙크(정현승) 미션 제출합니다.

- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutorService.java
안녕하세요 다즐!
빠른 피드백 감사합니다!
2단계 미션은 콜백 패턴을 적용해서 중복 코드를 제거해봤습니다.
다즐이 피드백 주신 내용도 같이 반영해봤습니다!
명절 때 너무 열심히 놀았지만.. 남은 미션도 속도를 한번 내보겠습니다!
편하실 때 리뷰해주시면 감사하겠습니다👍
> [JDBC라이브러리 / 2단계] 로이(김덕우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
안녕하세요 디투!! 1단계 꼼꼼히 봐주셔서 감사합니다 ㅎㅎ
2단계 미션 구현하여 제출합니다!!
구현한 내용으로는
1. RowMapper 구현
2. ResultSet try-with-resources 적용
3. 반복되는 Connection, PreparedStatement 생성을 제거하기 위한 PreparedStatementExecutor 생성
입니다!!
비타 500 너무 감사하고 덕분에 힘이 나네요 ㅎㅎ
감사합니다☺️
+++ 1단계 리뷰 때 답변 달아놨습니다!! 
[확인하기](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/315#discussion_r1345527576)
> [JDBC 라이브러리 구현하기 - 2단계] 푸우(백승준) 미션 제출합니다. 

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/exception/IncorrectResultSizeDataAccessException.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/testUtil/TestDataSourceConfig.java
- jdbc/src/test/java/nextstep/jdbc/testUtil/TestDatabaseUtils.java
- jdbc/src/test/resources/schema.sql
안녕하세요 메리! 👋
이번 step2를 진행하면서 크게 변경된 부분은 저번 step1에서 메리가 리뷰해주신
`queryForObject`에서 단일건이 아닌 복수건이 조회될 경우 예외가 발생하도록 리팩터링하였습니다.
또한 `jdbcTemplateTest` 도 모킹이 아닌 H2 데이터베이스를 사용해서 테스트 하도록 수정하였습니다!
step2 잘 부탁드립니다! 🙇‍♂️
> [JDBC 라이브러리 구현하기 - 2단계] 블랙캣(송우석) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
안녕하세요 히이로 !!
명절은 잘 보내셨나요~~ 
이번 미션에서는 비즈니스 로직들을 하나의 Connection에서 동작하도록 구현해보았습니다.
Service에서는 `DataSource`에 의존하지 않도록 노력했습니다,,
그리고 트랜잭션 관련 작업은 모두 `TransactionManager`에서 행하도록 했습니다.
이번 리뷰도 잘 부탁드려요!
> [JDBC 라이브러리 구현하기 - 3단계] 우르(김현우) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 홍고🍊
재택도 이제 끝이네요
3단계 미션을 완료하고 리뷰 요청드립니다
3단계 요구사항 충족을 위해서 jdbcTemplate 내에 외부로부터 connection을 주입받아 사용하는 메서드를 추가했어요
테스트를 통과하게 만들고 나서 LMS를 보니, 4단계에서 개선할 수 있을 것 같더라구요
그래서 일단 통과하게 만든 다음.. 바로 리뷰 요청을 드리게 됐어요
그리고 JDBC 테스트를 추가해보았습니다
날씨 쌀쌀해졌는데 감기 조심하세요..!
> [JDBC 구현하기 3단계] 가비(이준희) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- jdbc/src/main/java/org/springframework/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStateUtil.java
- jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
- jdbc/src/main/java/org/springframework/jdbc/core/SingleResult.java
안녕하세요 민트!
[1단계](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/360) 미션에서 짚어주신 부분 위주로 수정하였습니다...!!
> PreparedStatement를 인자로 받아서 처리하고, 원하는 타입을 반환하는 함수형 인터페이스를 만들면 어떨까요??
이 부분은 잘 이해가 안대서,...다시 설명해주시면 감사하겠습니다...!!!!
> JDBC 라이브러리 구현하기 - 2단계] 케로(김지현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
마! 규성씨...
정말 고민을 많이 하면서 코드를 구현해봤는데
이게 최선이네요..
정말 최악의 코드가 나온 것 같습니다.
그래도 상부에 보고하지는 말아주세요
무서우니까!
이번에도 잘 부탁드려요! 기무사 스파이 출신 마! 규성씨~!
> [JDBC 라이브러리 구현하기 - 3단계] 매튜(김재연) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionTemplate.java
안녕하세요 애쉬! 벌써 JDBC 3번째 선물이네요..
3단계 보니까 커넥션을 넘기는 식으로 구현하더라구요. 그래서 service 에서 커넥션 생성 후 autocommit 을 false 로 설정하고 이를 그대로 repository에 넘기는 방식으로 구현했습니다!
그리고 이전 단계에서 남겨주신 리뷰는 댓글로 답변 남겼습니다!! 최대한 적용하려고 했는데 혹시 놓친 부분 있으면 다시 말씀해주십셔!
> [JDBC 라이브러리 구현하기 - 3단계] 레오(차영호) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 제나!
긴 연휴+재택을 지나.. 매우 오랜만에 캠퍼스에 나왔네요😆
3단계는 일단 요구사항만 충족하도록 구현했습니다!
try-catch 중첩도 그렇고 파라미터로 connection 넘기는 것도 그렇고.. 기타등등 맘에 안드는 부분이 많아서
리팩토링하려다 보니 해당부분은 4단계 요구사항인 것 같더라구요?!
그래서 일단은..?! 완성한 것 같습니다 ㅎㅎ
이번 단계도 잘 부탁드려요!!🧑‍🎤
> [JDBC 라이브러리 구현하기 - 3단계] 오잉(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/Transaction.java
안녕하세요 오도 ! 
이번에 미션이 트랜잭션을 적용하는거라 고민을 많이 해봤습니다 !
그래서 트랜잭션 매니저와 트랜잭션이라는 클래스를 설계해서 한 번 구현해봤습니다. 
서비스레이어에 침투적인거를 어떻게 해야할지 모르겠네요.. 그래도 최대한 역할을 분리해봤습니다 !
리뷰 잘 부탁드려용 !
> [JDBC 라이브러리 구현하기 - 3단계] 하디(전동혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 준팍~ 3단계 구현 완료해서 리뷰 요청 드립니다.
만족스럽게 중복된 부분을 제거하지는 못했습니다. 4단계 리팩토링에서 제거해보겠습니다.
이번에도 잘 부탁드려요.
> [JDBC 라이브러리 구현하기 - 3단계] 에단(김석호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/AutoClosableTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 오잉!👨‍🎤🧑‍🎤👩‍🎤👨🏼‍🎤🧑🏼‍🎤👩🏼‍🎤  GoodDino입니다~~ 🦖🎸🎶
한 번이라도 더 오잉과 티키타카를 해보고 싶어 3단계 요구사항만 빠르게 구현하고 리뷰 요청 보냅니다.!
지난번에 얘기해 주신 템플릿 콜백 패턴...! 템플릿 메서드 패턴과 헷갈렸습니다!!🥲 부끄럽네요..하하
오잉이 첨부해 주신 링크에 아주 깔끔하게 정리되어 있더라구요..덕분에 확실히 짚고 넘어가게 됐어요ㅎㅎ 감사합니다
이번 3단계를 진행하면서 패턴 적용을 뺄까 말까.. 콜백 패턴으로 바꿔볼까 말까.. 고민을 조금 해봤는데요..!
`일단 이대로 두고, 다음 단계를 진행하다가 상황을 보고 롤백할지말지 결정하는건 어떨까요??`
라는 오잉의 코멘트를 보고 우선 저도 두기로 했습니다..ㅎㅎ
오잉은 이번에 콜백 패턴이 적용된 채로 3단계를 진행하게 될 것 같은데, 
제 코드와 비교하면서 어떤게 조금 더 깔끔해 보이는지 판단 내려 주세요..!ㅋㅋㅋ
이번 단계에서 UserService의 changePassword 메서드에서 이중 try-catch문을 쓰는 레전드 로직이 나와버렸는데,
여기서도 한 번 더 패턴 적용으로 코드를 깔끔하게 만들 수 있을지, 아니면 과도한 추상화가 되어 버릴지 감이 오질 않네요..
try-catch-try-catch-try-catch-try-catch-try-catch-try-catch-try-catch-try-catch (~~어지럽죠?~~)
오잉과의 리뷰를 통해 해답을 찾을 수 있을거라 믿습니다..
이번에도 어김없이 잘 부탁드립니다아아아아🙇
> [JDBC 라이브러리 구현하기 - 3단계] 디노(신종화) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserDaoJdbc.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDaoJdbc.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/core/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/core/TransactionTemplate.java
안녕하세요 배배
생각보다 미션이 어려워서 고전하느라 조금 늦었습니다.
조금 더 고도화를 하고 싶었으나 배배의 리뷰를 받고 하는 것도 나쁘지 않을 것 같다는 생각에 이렇게 제출합니다
transaction template이라는 클래스를 통해 트랜잭션이 필요한 메서드들을 받아 트랜잭션의 시작과 커밋 롤백을 하게 해줍니다.
그리고 하나의 트랜잭션에서 다 같은 connection을 가지고 있지 않다면 rollback이 되지 않아 connection을 파라미터로 다 넘겨주려다가
너무 귀찮아서 다른 방법을 생각해봤습니다.
thread local을 이용해서 해봤습니다. 좀 더 수정을 할 수 있을 것 같은데 그건 좀 있다 생각해보겠습니다 감사합니다
> [ JDBC 3단계 ] 박스터 미션 제출 합니다

- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
안녕하세요 우르 🙇
1단계 리뷰 남겨주신 거 답글 달았습니다.
2단계에 뭘 해야할 지 잘 모르겠어서 중복된 코드를 줄여보고자 `jdbcTemplate` 에서 `try-with-resources` 사용하는 부분을 추출해봤습니다.
우르가 2단계 미션에서 얻고 싶은 것에 대해 물어보셨는데 `자바가 제공하는 기능을 극한으로 활용해 코드를 개선하는 경험`이 될 것 같습니다.
근데 어떤 부분을 이러한 `자바가 제공하는 기능`들로 더 개선하면 좋을 지 감이 잘 안옵니다.
어떤 부분들을 더 개선할 수 있을지 알려주시면 열심히 반영해보겠습니다!
감사합니다 😊
> [JDBC 라이브러리 구현하기 - 2단계] 오도(문민혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecuteTemplate.java
- jdbc/src/main/java/org/springframework/transaction/TransactionTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 박스터!
미션 제출이 늦어졌네요 죄송합니다 ㅠㅠ
이번 3단계 요구사항에서 하나의 Connection으로 묶기 위해서 TransactionTemplate이라는 클래스를 하나 구현하였습니다.
현재는 각 서비스를 생성할 때 TransactionTemplate을 같이 생성해야하기 때문에 번거로운 작업이 있습니다.
그리고 UserDao 내부 메서드를 호출할 때 Connection을 인자로 넣지 않아도 됐었는데 이번에 넣게 되었네요.
공통적으로 변경해야하는 부분이 보이지만 조금 더 고민해서 적용하면 4단계로 넘어가는거 같아서 먼저 제출하겠습니다!
이번에도 잘 부탁드려요 박스터 🏎️🏎️🏎️
> [JDBC 라이브러리 구현하기 - 3단계] 헤나(박현서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
팍하(팍스하이라는뜻)
3단계 진행시켜 봤습니다.
짜고나니 코드가 중구난방한데...리팩토링 해나가는 재미가 있을 것 같아 코드스멜 나는 작업물을 보내봐요ㅎㅎ
일단 서비스 계층에 `DataSource`를 주입받고, 여기서 커넥션을 열고 닫도록 했습니다.
한 커넥션 안에서 한 비즈니스 로직을 끌고 가기 위해,
하위 계층 클래스들은 전부 커넥션을 파라미터로 받아 쓰도록 했어요.
이렇게 만들고 나니 `JdbcTemplate`에서 `DataSource`가 필요가 없어져서...인스턴스 변수를 들고 있지 않는 상태가 됐는데, 뭔가 이상하긴 하네요ㅎㅎ
많은 지적을 부탁해보겠습니다 :)
> JDBC 라이브러리 구현하기 - 3단계] 하마드(이건회) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementQueryExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementQueryForObjectExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementUpdateExecutor.java
- jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 땡칠~! 어느덧 3단계 미션에 접어들었네요!
이번 미션에서는 트랜잭션을 구현해봤습니다.
Transaction 수행을 위한 TransactionManager를 만들었고 이를 수행하는 TransactionExecutor를 구성했습니다.
추가로 지난 2단계에서 PrepareStatement의 실행부에 대한 추상화를 과도한 추상화로 느껴 수행하지 않았었는데 이번에 메소드를 오버로딩하면서 추상화의 필요성을 느껴 해당 내용도 함께 진행했습니다!!
복잡도를 직접 체감하고 추상화를 해보니 손맛이 좋네요 😋
학습테스트를 진행하여 커밋범위를 별도로 지정했습니다~!
잘부탁드립니다~~
날씨가 많이 쌀쌀해지고있네요 감기조심하세요~ 🍂
> [JDBC 라이브러리 구현하기 - 3단계] 주노(최준호) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/ConnectionHolder.java
- jdbc/src/main/java/org/springframework/transaction/support/ConnectionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionCallback.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/org/springframework/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/org/springframework/transaction/support/ConnectionHolderTest.java
- jdbc/src/test/java/org/springframework/transaction/support/ConnectionManagerTest.java
- jdbc/src/test/java/org/springframework/transaction/support/TransactionTemplateTest.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 호이~
연휴는 잘 보내셨나요?
```mermaid
graph LR
TT[TransactionTemplate] --> CM[ConnectionManager] --> CH[ConnectionHolder]
JT[JdbcTemplate] --> CM --> DataSource
```
UserService에 트랜잭션을 적용하기 위해 Dao에 Connection을 전달하는 것이 아닌, Spring의 TransactionTemplate과 유사한 형태로 작성해보았습니다.
TransactionTemplate이 아닌 그냥 UserDao를 사용하는 경우 다음과 같은 형태로 사용합니다.
1. JdbcTemplate ConnectionManager에서 Connection 가져오기
2. Connection 반환
트랜잭션이 적용되는 경우 다음과 같이 동작합니다.
1. TransactionTemplate에서 ThreadLocal에 Connection 저장
2. TemplateCallback으로 받은 메서드 실행
3. 실행된 메서드에서 ConnectionManager를 통해 Connection을 가져올 때 ThreadLocal에 있는 Connection 반환
4. ThreadLocal에 있는 Connection 제거 및 해제
이번에도 리뷰 잘 부탁드립니다! 👍👍👍👍👍👍
> [JDBC 라이브러리 구현하기 - 3단계] 허브(방대의) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/Executor.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
안녕하세요 밀리!
저번에 말씀해주신 템플릿 콜백 패턴을 통해서 중복 코드를 줄여봤습니다.
확실히 JdbcTemplate에서 추가적인 기능이 생긴다면, 중복이 많이 줄어들 것 같아서 좋습니다!
다만 아직 미숙한 점이 있어서 리뷰하시다가 혹시 이해가 안되시는 부분이 있다면 코멘트 남겨주세요 ㅎㅎ
트랜잭션을 적용하면서 현재 connection을 파라미터로 넣어서 동일한 connection을 사용하고 있습니다.
비즈니스로직과 섞이는 문제점도 있고, 매개변수를 넣음에 따라 JdbcTemplate에서 트랜잭션용 메서드도 하나씩 더 오버로딩해서 만들어야하는 문제가 있습니다.
4단계 미션을 보니 이런 문제점을 해결하는 것 같아서 일단 기능 구현에만 집중했습니다.
이번 리뷰도 잘 부탁드리겠습니다 🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 3단계] 제이(이재윤) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 이오,,
3단계 미션만 보고 구현했을때 중복도 많이생기고 찝찝해서 이렇게 하는게 맞는건지 잘모르겠어서 제출 못하고있다가 4단계에서 리팩토링을 진행하는것같아서 일단 3단계부터 제출하겠습니다,,
> [JDBC구현하기 - 3단계] 파워(송재백) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
조이~! 안녕하세요🙇‍♂️
이번 3단계 미션 진행하며 저번 2단계에서 빠뜨린 UserHistoryDao 리팩터링도 해보았습니다!!
감사합니다 :)
> [JDBC 라이브러리 구현하기 - 3단계] 제리(권현재) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionProcessor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
안녕하세요 엔델!
이번 미션은 스프링의 TransactionSynchronizationManager을 참고해서 트랜잭션을 구현해보았습니다.
리뷰 잘 부탁드립니다 :)
> [JDBC 라이브러리 구현하기 - 3단계] 아벨(신준혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/dao/ConnectionCloseException.java
- jdbc/src/main/java/org/springframework/dao/TransactionAutoCommitException.java
- jdbc/src/main/java/org/springframework/dao/TransactionCommitException.java
- jdbc/src/main/java/org/springframework/dao/TransactionRollbackException.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 지토 :)
주말 잘 보내고 계신가요?
3단계 트랜잭션 적용하기는 최소한의 요구사항을 충족해보았습니다.
따라서 큰 변동사항은 없을 것 같아요.
다음 단계에 트랜잭션 동기화를 하면서 코드 개선점들이 생길 것 같네요.
이번 리뷰도 잘 부탁드립니다🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 3단계] 저문(유정훈) 미션 제출합니다. 

- README.md
- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/ConnectionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/org/springframework/jdbc/datasource/ConnectionManagerTest.java
- jdbc/src/test/java/org/springframework/transaction/support/TransactionManagerTest.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 코코닥! 👃👃🐔
3단계 미션 완료하고 제출합니다!
이번 미션에서 트랜잭션을 어떻게 하면 깔끔하게 처리할 수 있을지 조금 많이 고민하고, 적용한 것 같네요.
스포일러가 될 수 있으니, 구현 과정에 대한 설명은 밑에 커멘트로 남겨두겠습니다. 
리뷰 기다리겠습니다!
감사합니다!
> [JDBC 라이브러리 구현하기 - 3단계] 글렌(전석진) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 로이스~
이번 3단계에서는 jdbcTemplete의 메서드에서 connection 파라미터를 추가해 트랜잭션을 사용할수 있게끔 해보았습니다~
> [JDBC 라이브러리 구현하기 - 3단계] 루쿠(백경환) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 헤나
2단계에 이어서 3단계도 제출합니다!
3단계는 요구 사항대로 트랜잭션을 적용하는 부분까지만 진행했어요.
마음에 안드는 부분들도 있는데 트랜잭션 공부하고 학습 테스트하는 데 시간을 많이 보내서,
이 부분들은 다음 단계 요구 사항 진행하면서 해결해볼게요 🥲
> [JDBC 라이브러리 구현하기 - 3단계] 망고(고재철) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
안녕하세요 말랑, 이오입니다 :)
3단계 미션 가볍게 구현하였습니다.
생각보다 제출이 늦어져서🥲 더 리팩토링 할까 하다 우선 제출합니다..
이번 리뷰도 잘부탁드려요!
> [JDBC 라이브러리 구현하기 - 3단계] 이오(이지우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/Some.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/exception/DataAccessException.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 푸우
이번엔 별거 한게 없네요
요구사항에 충실하기 위해 굳이 중복코드를 제거하진 않았습니다
감사합니다
> jdbc step3 주드 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementExecutor.java
안녕하세요 무민! 어제 축구 결승 한일전 보셨나요?? 덕분에 오늘 꿀잠잤네요 ㅎㅎ
3단계 요구사항에 맞춰 구현해보았습니다.
트랜잭션을 적용하기 위해 Service 메서드에서 Connection을 획득하고, DAO 메서드에 Connection 객체를 모두 전파하니까 확실히 코드가 불편해지네요.
코드가 불편해도 일단은 3단계 요구사항에 맞춰 구현해보았습니다.
그럼 잘 부탁드립니다 🙇‍♂️
> [JDBC 구현하기 - 3단계] 도기(김동호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutorService.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionNoReturnExecutor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 키아라!
3단계 미션은 하면서 감이 잡히지 않아서 초반에 많이 헤맸던 것 같아요..!
2단계와 비슷하게 템플릿 콜백 패턴을 사용해서 서비스에서는 비즈니스 로직을 람다로 작성할 수 있게 구현했어요.
한 가지 찝찝한 점은 비즈니스 로직에서 리턴값이 존재할수도 존재하지 않을 수도 있어서 인터페이스와 메서드를 각각 두 개씩 만든 부분이에요.
하지만 마땅한 방법이 떠오르지 않아서 놔두었습니다..!
그리고 학습테스트도 어렵네요,, 🥲
그럼 이번 리뷰도 잘 부탁드립니다 ㅎㅎ
감사합니다 ☺️
> [JDBC 라이브러리 구현하기 - 3단계] 밀리(김미성) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
가비 하이 ☀️
가비를 쫓아 3단계를 구현해 왔습니다!
일단은 리팩토링을 진행하진 않고 먼저 구현했습니다.
다른 크루들의 구현 방법을 보니 트랜잭션 경계를 만들어주는 역할을 분리했더라구요!
저는 조금 더 공부해보고 4단계 때 적용해보도록 하겠습니다.
tdd로 진행하지 않아서 기능이 구현되었지만 테스트가 없는 것들이 있습니다. (특히 connection 객체를 인자로 받는 메서드)
이것들은 리팩토링 과정에서 없애려고 계획중입니다..! 도중에 리뷰를 받는 것 같아 죄송한데요. 이런 경우에도 테스트코드를 꼭 짜는게 맞을까? 라는 질문을 스스로 하게 되었고 제 결론은 No 였습니다. 기존의 테스트 코드를 만족하는 수준에서 다음 단계를 넘어가려고 합니다. 가비의 생각이 다르다면 request change 해주셔도 괜찮으니 의견주세요 :D
> [JDBC 라이브러리 구현하기 - 3단계] 로지(윤가영) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/MockJdbcTemplateTest.java
- jdbc/src/test/java/nextstep/jdbc/TestDataSourceConfig.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요, 오션 🌊🌊🌊
어제 세계불꽃축제와 한일전은 잘 보시고 오셨나요 ! ! 
불꽃축제 너무 예뻤죠 🎆🎇 !!! ~~(근데 당분간 한강은 생각 안날듯 ㅎㅎ;)~~
저번 1단계와 마찬가지로, 3단계도 구현만 우선적으로 했고 4단계에서 추가적인 고민을 해볼 예정입니다!
4단계 관련해서 리뷰 주셔도 좋습니다 🙇‍♂️
추가적으로, 기존에 통과되지 않는 테스트들이 있어서 수정해주었구요
2단계 마지막에 남겨주신 코멘트 참고해서 ResultSet 관련 부분해서 테스트를 추가하였습니다!
해당 테스트가 추가되면서 기존 JdbcTemplateTest가 MockJdbcTemplateTest로 변경된 점 참고 부탁드립니다~~
오션의 테코톡 기대하겠씁니다 (근데 주제가 뭐죠 ㅎㅎ? 미리 공부해가게요 ^^)
그으럼 3단계도 잘 부탁드립니다 🙇‍♂️🙇‍♂️
> [JDBC 라이브러리 구현하기 - 3단계] 라온(문채원) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/BaseJdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/ConnectionAction.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 하마드 ~
3단계 미션 제출합니다.  
전체적으로 코드가 깔끔하지 못해 리뷰하기 힘드실 것 같다는 생각이 들어 죄송하네요...😓
이번 리뷰도 잘 부탁드려요!
새로운 코드를 추가하면서 기존 코드들을 제거할지 고민을 좀 했었는데요..
다음 단계를 진행하면서 기존 코드를 재사용할수도 있을 것 같아서 일단 남겨두었습니다.
(현재 코드에서는 Dao 메서드들에 Connection을 파라미터로 넘기지만, 이후에 리패터링하면서 다시 제거할수도 있을 것 같아서요!)
만약 다음 단계 미션을 할 때 불필요하다 느껴지면 지우도록 하겠습니다🙂
> [JDBC 라이브러리 구현하기 - 3단계] 조이(김성연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
에밀... 상당히 오래간만이네요...
늦은 만큼 좋은 코드를 보여주고 싶었으나..
4단계에서 보여주기 위해 좀 참았습니다..ㅎ
가감 없는 리뷰, 과감한 리뷰 부탁드립니다!ㅎㅎ
> [JDBC 라이브러리 구현하기 - 3단계] 준팍(박준현) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
비버 제가 조금 늦었네요ㅠ
간단하게 3단계 구현해보았습니다! 
잘부탁드립니다~
> [JDBC 라이브러리 구현하기 - 3단계] 에밀(김대희) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/exception/ConnectionException.java
- jdbc/src/main/java/org/springframework/jdbc/exception/RollbackFailException.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
우가 안녕하세요 ㅎㅎ 그레이입니다 :)
이번 3단계는 우선 트랜잭션 동작을 구현하는데 집중했어요.
`UserService`에서 한 트랜잭션으로 `UserDao`와 `UserHistoryDao`를 관리를 해야 하다보니 `Connection` 객체가 비즈니스 코드에 들어올 수 밖에 없는 구조가 된 것 같아요 😀
추가적으로 rollback을 하기 위해서 try - catch 구문을 사용했는데요 !
```java
try {
connection.setAutoCommit(false);
user.changePassword(newPassword);
userDao.update(connection, user);
userHistoryDao.log(connection, new UserHistory(user, createBy));
connection.commit();
} catch (SQLException e) {
throw new ConnectionException(e.getMessage());
} catch (DataAccessException e) {
rollback(connection);
throw new DataAccessException(e.getMessage());
} finally {
close(connection);
}
```
DataAccessException 예외가 발생하는 경우 롤백이 필요하기 때문에 rollback을 호출한 후 동일한 예외를 다시 throw하도록 구현했습니다.
이미 하위 계층에서 발생한 예외를 잡아서 rollback하는 과정까지는 자연스러운 것 같은데 다시 throw 한다는게 애매한 것 …
> [JDBC 라이브러리 구현하기 - 3단계] 그레이(김동욱) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/main/resources/application.yml
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 주디!!
미션은 잘되가시나용?
Transaction 을 적용하기 위해서 Connection 을 넘겨주는 방식을 택했는데, 주디는 어떤 방식을 택하셨나요?
autoCommit setting 과 commit, rollback 등 겹치는 부분이 너무 많아서 메소드를 분리했습니다.
SQLException 발생 가능성이 있는 메소드가 너무 많아서 try-catch-try-catch-try-catch-try-catch-try-catch 가 될 것 같았습니다.
그래서 UserService 모든 메소드가 SqlException 을 던지고 있습니다.
SQLException 을 제거할 방법이 마땅히 떠오르지가 않아서 주디의 의견이 궁금합니다!!
> [JDBC 라이브러리 구현하기 - 3단계] 우가(윤정욱) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/transaction/exception/ConnectionManagerException.java
- jdbc/src/main/java/org/springframework/transaction/support/ConnectionManager.java
- jdbc/src/test/java/org/springframework/transaction/support/ConnectionManagerTest.java
- study/build.gradle
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 제이미!
3단계 미션 제출합니다.
3단계에서 ConnectionManager라는 클래스가 Connection을 스레드 별로 관리해주도록 구현했습니다.
3단계도 잘 부탁드립니다 😃
> [JDBC 라이브러리 구현하기 - 3단계] 홍실(홍혁준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/ConnectionUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/LogicExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 저문! 이레입니다
2단계에 리뷰 주신 내용에 대해서는 답글을 모두 달아놓았습니다.
1. 트랜잭션을 사용하려면 각 쿼리 실행에 필요한 Connection이 공유 되어야한다. 하나의 Connection은 하나의 DB의 세션과 연결되는데, 각 쿼리마다 다른 connection이 연결된다면 각각 다른 DB 세션과 연결되고, 이는 곧 서로 다른 트랜잭션이 실행되는 것이기 때문입니다.
2. 따라서 서비스에서 Connection을 생성하여 repository-jdbcTemplate까지 이어지는 쿼리 실행에 있어 동일한 connection을 사용하도록 했습니다.
3. 이 과정에서 트랜잭션과 비즈니스 로직의 분리가 필요하다고 생각했습니다.
4. Connection의 생성과 종료를 담당하는 ConnectionUtils를 만들었고,
5. transaction의 시작과 종료를 관리하는 TransactionManager을 만들었습니다.
6. 이를 통해 트랜잭션 관련 기능은 TransactionManager에게 일임하고, 서비스에서는 비즈니스 로직에 집중할 수 있도록 만들었습니다.
패키징에 대해서 깊은 고민 없이 배치를 했는데요, 이 점에 대해서 문제점이 있다면 리뷰해주시면 감사하겠습니다!
> [JDBC 라이브러리 구현하기 - 3단계] 이레(이다형) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDaoWithJdbcTemplate.java
- app/src/main/java/com/techcourse/dao/UserDaoWithNamedParameterJdbcTemplate.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/repository/UserRepository.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoWithJdbcTemplateTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/NamedParameterJdbcTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
할말을 잃게 만드는 구조의 코드가 완성되었습니다.
오늘 배운 JDK Proxy를 쓰면 해결이 되려나 했는데
4단계 때 제공하는 무언가를 사용해서 리팩토링을 수행하나 봐요!
그래서 이번에는 정말 돌아가기만 하도록 구현해 제출합니다. 🥹
> [JDBC 라이브러리 구현하기 - 3단계] 여우(조승현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 채채
이번에는 2단계 리뷰좀 반영하고 UserServiceTest가 돌아가도록 코드를 고쳐보았습니다.
그렇기 때문에 update 상황에 대해서만 userDao, jdbcTemplate에서 connection을 인자로 받는 메서드를 추가해보았어욥
리뷰 잘부탁해용
> [JDBC 라이브러리 구현하기 - 3단계] 이리내(성채연) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요, 아벨!
step3까지 시간이 조금 지났네요...ㅎ
이번에는 요구사항만 만족할 수 있도록 작성하였습니다.
update메서드에 한정하여 하나의 트랜잭션으로 관리되는 코드만 작성하였습니다!
리뷰 잘 부탁드려요~!
> [JDBC 라이브러리 구현하기 - 3단계] 로이스(원태연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
디노 안녕하세요~~
계속 미션이 너무 늦어지네요..ㅠㅠ
미션에 집중해야 하는걸 아는데도 플젝에서 할게 너무 많기도 하고...
ㅠㅠ 그래서 급급하게 하다보니 조금 코드도 이상하게 작성하게 되는 것 같아요..!
저번 미션에서 오류 있었던 부분이 있어서 해당 부분 수정하고, 3단계 진행했습니다~(정확히는 진행하다 중간에 수정했습니다..!)
잘 부탁드려요!
주말 잘 보내세요!
> [JDBC 라이브러리 구현하기 - 3단계] 말랑(신동훈) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
안녕하세요 로이~!
리뷰 요청이 늦어졌네요 🥲
2단계 요구사항에 있던 트랜잭션 부분을 하다 3단계도 같이 진행해서 요청 보냅니다 ˙ᵕ˙ 
1단계 때 리뷰 남겨주신 부분도 함께 적용했습니다 !!
Connection 객체가 비즈니스 로직과 섞이게 되어 마음에 걸렸지만 일단 LMS 요구사항을 만족하는것에 만족했습니다.... 
(사실 4단계에서 하는 것 같아 요번 단계는 현재 상태에서 리뷰를 받고 4단계 때 리팩토링 해보려고 합니다 !!)
이번에도 리뷰 잘 부탁드립니다 🙇‍♀️
> [JDBC 라이브러리 구현하기 - 2, 3단계] 토리(천은정) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
안녕하세요 우르!
3단계 미션에서는 비밀번호 변경과 로그 기록을 한 작업으로 묶기 위해 Connection 을 인자로 받을 수 있게 하였습니다.
서비스 로직에 트랜잭션을 관리하기 위한 Connection 관련 작업을 분리해내기 위해 TransactionManager를 만들었습니다.
리뷰해주셔서 감사합니다 😊
> [JDBC 라이브러리 구현하기 - 3단계] 오도(문민혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementImpl.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- study/build.gradle
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
3단계 리뷰도 잘 부탁드려요 블랙캣 😊
트랜잭션을 구현하기 위해 이것저것 생각해보다가 스프링 AOP같은 방식으로 메서드 앞 뒤에 따로 처리를 해 주고 싶었지만 능력이 부족해서 미션에서 주어진 요구사항만 통과하도록 한 상태입니다. 처음에 UserDao의 update와 UserHistoryDao의 log 외에 다른 메서드까지 `Connection`을 받도록 바꿨었는데 커넥션을 닫지 못하는 상태가 되었더라구요. 그래서 해당 메서드들은 다시 롤백시켜주었습니다.
4단계를 잠깐 보니 트랜잭션을 위해 따로 인터페이스를 분리해서 처리해주는 거 같은데 그 때 한 번 더 고민해봐야 할 것 같네요
> [JDBC 라이브러리 구현하기 - 3단계] 썬샷(오진택) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementUtils.java
- jdbc/src/main/java/org/springframework/jdbc/core/StatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 폴로!
저번 단계에서는 제가 코멘트 하나를 미처 못보고 지나쳤더라구요...🥲
그 때 주신 코멘트 덕에 어떻게 하면 unchecked exception 처리를 깔끔하게 할 수 있을지 오래 고민할 수 있었어요!
처음엔 함수형 인터페이스&람다식을 통해 try-catch와 내부 로직을 분리했는데요,
sql exception이 처리되지 않았다는 컴파일 에러가 발생해서 의아했었는데 함수형 인터페이스를 직접 정의하고 메서드 시그니처에 exception을 던지도록 하면 해결된다는 걸 처음 알게 되었어요. 감사합니다ㅎㅎ
남은 미션에서는 코멘트를 놓치는 일이 없도록 하겠습니다...!
그럼 3단계도 잘 부탁드립니다~~!
+) 학습 테스트 부분은 아직 학습중이라 커밋 내역은 신경 쓰지 않으셔도 될 것 같아요.
> [JDBC 라이브러리 구현하기 - 3단계] 아마란스(송세연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/ConnectionAgent.java
- jdbc/src/main/java/org/springframework/transaction/ConnectionHolder.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
오랜만에 캠퍼스 나오니까 많이 힘드네요...
그래도 열심히 3단계 구현해봤습니다.
음.
transactionManager에서 트랜잭션을 관리하는데요.
connection을 유지 하기 위해서 ThreadLocal에 connection을 저장해두는 ConnectionHolder 와
ConnectionHolder에서 connection을 가져오고 connection이 없는 경우에 connection을 새로 생성하는 ConnectionAgent를 구현했습니다.
TrnasactionManger와 JdbcTemplate에서 각각 ConnectionAgent를 의존하여 connection을 꺼내 쓰고 있습니다.
설명이 더 필요하시면 편하게 말씀해주세요!
> jdbc 3단계 폴로 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecuteTemplate.java
- jdbc/src/main/java/org/springframework/transaction/TransactionCallback.java
- jdbc/src/main/java/org/springframework/transaction/TransactionCallbackReturnVoid.java
- jdbc/src/main/java/org/springframework/transaction/TransactionTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 박스터~
3단계에서 남겨주신 피드백도 반영했습니다!
- TransactionTemplate에 인자로 기본으로 제공하는 Consumer를 사용했던 부분을 인터페이스를 만들어서 대체했습니다.
- TransactionCallback, TranscationCallbackReturnVoid
- TransactionTemplate에서 진행되던 Connection의 commit, rollback과 같은 기능을 TransactionManager를 구현하여 템플릿은 호출을 실제 트랜잭션 기능은 TransactionManager가 진행하도록 했습니다.
4단계 미션도 잘 부탁드리겠습니다 👍
> [JDBC 라이브러리 구현하기 - 4단계] 헤나(박현서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/jdbc/exception/CannotGetJdbcConnectionException.java
- jdbc/src/main/java/org/springframework/jdbc/exception/ConnectionCloseException.java
- jdbc/src/main/java/org/springframework/transaction/exception/TransactionAutoCommitException.java
- jdbc/src/main/java/org/springframework/transaction/exception/TransactionCommitException.java
- jdbc/src/main/java/org/springframework/transaction/exception/TransactionRollbackException.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 지토 :)
이번에 4단계를 하면서 많은 시행착오를 겪은 끝에 겨우 구현했네요..!
기본 요구사항에 더불어,  `TransactionExecutor`를 통해서 트랜잭션 처리에 대한 중복 로직을 처리했습니다.
이번 리뷰도 잘 부탁드립니다 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
> [JDBC 라이브러리 구현하기 - 4단계] 저문(유정훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 모디~
늦어서 죄송합니다.. 😢
저번 리뷰에서 ResultSet을 close 해달라는 리뷰를 받았었는데요, 2단계 리팩토링할 때 ResultSet을 일부러 close하지 않았습니다.
그 이유를 pr에 작성했어야 했는데 깜빡했네요..ㅠㅠ
ResultSet은 try-with-resources 사용하거나 명시적으로 close()를 호출하지 않아도 자동으로 닫힌다고 합니다!
[공식문서](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html)의 `Field Summary` 조금 위쪽을 보면 아래와 같이 적혀있더라구요!
> A ResultSet object is automatically closed when the Statement object that generated it is closed, re-executed, or used to retrieve the next result from a sequence of multiple results.  
따라서 굳이 작성해서 try-catch문을 만들 필요가 없다고 생각해서 제거하였습니다.
이번 리뷰도 잘 부탁드립니다!!
> [JDBC 라이브러리 구현하기 - 3단계] 엔초(권예진) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/connection/ConnectionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/TransactionTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
- mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java
- study/src/test/java/transaction/stage2/FirstUserService.java
안녕하세요 도치🙌 드디어 마지막 pr이네요! 4단계까지 따로 보내는게 처음이라 많이 뵙는거 같네요 ㅋㅋㅋ 끝까지 잘 부탁드립니다!
이번 미션에서는 트랜잭션 동기화, 트랜잭션 서비스 추상화에 집중했습니다! 그리고 `PlatformTransactionManager`를 구현 해보려고 했는데 쉽지 않더라고요.. 그래서 일단 포기했습니다🥲
한글날 푹 쉬시고 시간 될 때 리뷰 부탁드립니다💪
> [JDBC 라이브러리 구현하기 - 4단계] 두둠(최영훈) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionProcessor.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 엔델! 휴일 잘 보내고 계신가요 ㅎ
이번엔 Transaction 로직을 TransactionTemplate로 분리했고, TxUserService에서 TransactionTemplate를 사용하는 식으로 추상화를 진행했습니다.
또한 기존의 TransactionManager의 역할을 DataSourceUtils와 TransactionSynchronizationManager로 나누어 주었습니다. 기존의 TransactionManager는 딱 트랜잭션 주요 기능의 포트 역할만 맡게끔 개선했습니다.
리뷰 잘 부탁드립니다 :)
> [JDBC 라이브러리 구현하기 - 4단계] 아벨(신준혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/ConnectionHolder.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- study/build.gradle
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 스플릿! 마코입니다~
이번 미션은 학습 테스트를 진행하고 트랜잭션을 적용하는데에만 집중했습니다.
학습 테스트에서 도커가 실행이 잘 안되는 이슈가 있어서 애를 먹었네요ㅎㅎ 의존성을 최신 버전으로 업데이트하니까 해결됐습니다.
트랜잭션을 구현할 때 Connection을 파라미터로 넘기는 것을 고민하다가 TransactionSyncronizationManager와 DataSourceUtils로 해결할 수 있을 것 같아서 사용해 봤습니다.
스레드마다 요청을 처리하기 때문에 ThreadLocal을 사용하면 메서드 파라미터로 전달하지 않아도 같은 Connection 객체를 사용할 수 있더라고요.
이번 리뷰도 잘 부탁드립니다~
> [JDBC 라이브러리 구현하기 - 3단계] 마코(이규성) 미션 제출합니다. 

- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
안녕하세요, 이제 마지막 단계에서 뵙게 되었네요.
이번 단계역시 lms 순서대로 진행했습니다.
1. Transaction synchronization 적용하기의 경우 저번 단계에서 TransactionSynchronizationManager를 사용하면서 적용했다고 생각하고 넘어갔습니다.
2. 트랜잭션 서비스 추상화하기를 따라서 진행했는데요. UserService 인터페이스를 만들고, 그것을 구현하는 2개의 클래스를 구현한 다음, UserServiceTest가 성공하도록 미션을 진행했습니다.
감사합니다.
> [JDBC 라이브러리 구현하기 - 4단계] 엔델(김민준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/TransactionalExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
잘부탁드립니다 글렌 드디어 마지막이네요 간단한 요약입니다.
1. DataSourceUtils와 TransactionSynchronizationManager의 ThreadLocal을 통해 스레드에서 커넥션을 공유해서 사용했어요.
2. 커넥션을 close하는 코드도 DataSourceUtils를 통해 해결했는데, 이때 autoCommit이 true라면 close하고 커넥션을 지워줍니다.
3. autocmmit이 false라면 아무일도 일어나지 않고 early return 합니다.
4. 트랜잭션을 적용한 로직에선 처음에 autoCommit을 false로 설정하기에 아무리 jdbcTemplate의 메소드를 호출해도 close되지 않습니다.
5. 대신 모든 로직이 완료되면 autoCommit을 true로 변경시키고 ```DataSourceUtils.releaseConnection()```을 호출해 close합니다.
코드로 보면 간단한데, 텍스트로 적으니까 어려워보이네용..
> [jdbc 미션 4단계] 오리(오현서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxAppUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
조이 안녕하세요~!
저번 미션에서 `UserService` 클래스의 `changePassword` 메서드를 보고 아래와 같은 질문을 남겨 주셨는데요!!
> `UserService` 클래스의 제리 ! 이 하나의 작업에 사용된 Connection은 하나인가요?🤔
이 질문의 의도를 잘 이해하지 못해 답을 못했습니다.
단순히, 커넥션이 사용되는 갯수를 물어보는 질문이었다면 1개가 맞다고 답할 수 있을 것 같아요.
혹시 위 질문을 통해 제가 눈치챘어야 할 다른 의도가 있었다면 답변 부탁드립니다ㅠㅠ
> [JDBC 라이브러리 구현하기 - 4단계] 제리(권현재) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
안녕하세요 제나~~~
10월의 두번째 연휴네요 ㅎㅎㅎ
이번 연휴 잘 쉬셨나요?? 저는 매우 푹 쉬었습니다 ><
4단계 미션 완료했습니다!
이번에 작업한 내용은 다음과 같습니다.
1. Transaction Synchronization 적용 (TransactionSynchronizationManager)
2. 트랜잭션 서비스 추상화 (UserService -> TxUserService&AppUserService)
3. 트랜잭션 중복 로직 제거 (TransactionTemplate)
이번 단계도 잘 부탁드려용👨‍🎤🧑‍🎤👩‍🎤
> [JDBC 라이브러리 구현하기 - 4단계] 오잉(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/jdbc/exception/ConnectionBindingException.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java
안녕하세요 우가 ㅎㅎ
벌써 우가와 함께하는 마지막 단계네요 🥲
마지막 단계인만큼 좀 더 꼼꼼하게 코드를 작성했습니다 ~
4단계 요구사항인 애플리케이션 메서드에서 connection 파라미터를 제거하고 트랜잭션 서비스를 추상화했어요 !
추가적으로 이전 단계와 다르게 `TransactionTemplate` 클래스를 추가했어요.
UserService에 존재하던 트랜잭션 관련 코드를 해당 클래스로 책임을 부여했습니다 :)
마지막 단계 리뷰도 잘 부탁드려요 😆
> [JDBC 라이브러리 구현하기 - 4단계] 그레이(김동욱) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/TransactionServiceCallback.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 아벨! 직전 리뷰에서 남겨주신 코멘트 반영했습니다!
4단계를 진행하면서 트랜잭션 로직을 비즈니스 로직에서 분리하도록 수정하였습니다.
커넥션이 돌아다니지 않아서 좋은 것 같아요..!
제공되어있는 class를 활용하니 어렵지 않게 적용하였습니다!
리뷰 잘 부탁드립니다~!
> [JDBC 라이브러리 구현하기 - 4단계] 로이스(원태연) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/transaction/Executor.java
- jdbc/src/main/java/org/springframework/jdbc/core/transaction/ExecutorWithoutReturnValue.java
- jdbc/src/main/java/org/springframework/jdbc/core/transaction/TxExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java
쥬니 안녕하세요! 
4단계 미션으로 돌아왔습니다...! 
4단계 요구사항을 간단하게 반영해 봤어요
JdbcTemplate에서만 DataSource를 통해 커넥션을 직접 관리하도록 수정하고, 그외의 Service, DAO 코드에서는 커넥션 객체를 직접 다루지 않도록 모든 파라미터에서 제외했습니다.
그리고, UserService 객체를 인터페이스로 사용해서 기존 애플리케이션 로직은 AppUserService, 트랜잭션 관련 로직까지 포함하는 서비스 로직은 TxUserService로 분리했습니다. 
TxUserService에서 트랜잭션과 관련된 로직이 매우 중복되기 때문에, TxExecutor로 분리했습니다!
> 깃짱의 JDBC 구현 4단계 🌟

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/ObjectConverter.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/org/springframework/jdbc/config/DataSourceConfig.java
- jdbc/src/test/java/org/springframework/jdbc/datasource/DataSourceUtilsTest.java
안녕하세요 디투 3,4 단계 미션 완료하고 제출합니다!!
진행한 작업은 다음과 같습니다.
3단계
1. UserHistoryDao 가  jdbcTemplate 사용하도록 변경
2. UserService 가 DataSource 를 받아서 두 개의 Dao 가 같은 트랜잭션 범위를 공유하도록 만든다.
4단계
Service 에 transaction 관련 작업들을 분리하기 위해 Service 를 인터페이스로 변경했습니다
그 후 Service 의 두 가지 구현체의 역할은
1. TxService : Transaction 관리
2. AppService: 비즈니스 로직
입니다!!
이 때 TxService 에 connection을 가져와 setAutoCommit(false)와 같은 로직이 상당히 반복되고 다른 Service 에서도 똑같이 반복될 것으로 예상되어 TransactionManager를 만들었습니다!!
리뷰 감사합니다 디투 ㅎㅎ
> [JDBC 라이브러리 구현하기 - 3,4단계] 푸우(백승준) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/ServiceCallBack.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/ServiceCallBack.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManger.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 로이스~ 
이번 4단계 미션은 요구사항에 맞게
Transaction synchronization을 적용하고 트랜잭션 서비스를 추상화하였습니다!
리뷰 잘부탁드려요~
> [JDBC 라이브러리 구현하기 - 4단계] 루쿠(백경환) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/ConnectionSynchronizationManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> [JDBC 라이브러리 구현하기 - 4단계] 오도(문민혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionCallback.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 헤나!
벌써 JDBC 미션 마지막이네요 🥲
이번 4단계는 기능 요구 사항에 나와있는
1. Transaction synchronization 적용하기
2. 트랜잭션 서비스 추상화하기
에 맞춰서 `TransactionSynchronizationManager` 구현하고, `DataSourceUtils`와 `TransactionSynchronizationManager`를 사용하도록 수정,
그리고 `UserService`를 추상화하여 `AppUserService`와 `TxUserService`로 비즈니스 로직과 데이터 액세스 로직을 분리하도록 했습니다.
마지막 리뷰도 잘 부탁드립니다 😎
> [JDBC 라이브러리 구현하기 - 4단계] 망고(고재철) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementQueryExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementUpdateExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 로이 ~! 토리입니다 ˙ᵕ˙ 
이전까지 추상화를 해주는게 오히려 가독성이 떨어질 것 같아 하지 않았었는데,
리뷰를 보고 4단계 요구사항과 함께 `preparedStatement`에 대한 추상화 작업도 진행했어요 !
이번에도 리뷰 잘 부탁드립니다 🙇‍♀️
> [JDBC 라이브러리 구현하기 - 4단계] 토리(천은정) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutorService.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionNoReturnExecutor.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionNoReturnExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 키아라 🤗🤗🤗
드디어 마지막 단계네요..!
그동안 리뷰 해주시느라 고생많으셨어요!! 감사해요 ㅎㅎㅎ
이번 단계는 재밌네요 ㅎㅎ 
Connection 객체가 계속 타고 타고 들어가던게 정말 마음에 안들었었는데, 
ThreadLocal로 해결되니 속이 너무 시원하네요 😌
또 서비스를 추상화하니 실제 비즈니스 로직이 들어간 서비스에 트랜잭션 관련된 코드도 싹 없어졌네요 ㅎㅎ
그럼 마지막 리뷰도 잘 부탁드립니다 🙇‍♀️
> [JDBC 라이브러리 구현하기 - 4단계] 밀리(김미성) 미션 제출합니다.

- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TXUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutorService.java
- jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 다즐!
늘 빠른 피드백에 감사하고 있습니다ㅎㅎ
미션을 미리미리 하지 못해서 3,4단계를 함께 진행한 점 양해 부탁드릴게요ㅠ
시간 괜찮으실 때 리뷰해주시면 감사하겠습니다!
남은 연휴 잘 보내세요!!
> [JDBC 라이브러리 / 3, 4단계] 로이(김덕우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/JdbcTransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionCallback.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionCallbackWithoutResult.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
- study/src/test/java/transaction/stage1/Stage1Test.java
안녕하세요 에단! 😀
4단계쯤 되어 코드를 되돌아보니, 약간은 복잡한 감이 있지 않나 싶긴하네요 ㅋㅋㅋㅋ 그래도 이번 JDBC 미션에서는 중복을 줄이려는 것을 중요시해보려고 합니다. 이번에도 트랜잭션을 적용하는 부분에서, 서비스 레이어에서는 비즈니스로직만 신경쓸 수 있도록 트랜잭션 템플릿 패턴으로 리팩토링해봤습니다. 나머지는 이번 4단계에서 힌트를 준 로직에서 크게 건든 것 없이 그대로 구현하였습니다.
이번에도 같이 의견 나눠보면 재밌을 것 같네요! 시간 부담갖지 마시고 천천히 리뷰 주셔도 괜찮습니다!
> [JDBC 라이브러리 구현하기 - 4단계] 헙크(정현승) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
- jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
안녕하세요 비버!
제가 많이 늦었네요..
이해해주셔서 감사합니다! 
마지막 리뷰 잘 부탁드려요~
> [JDBC 라이브러리 구현하기 - 4단계] 에밀(김대희) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 땡이! 리뷰어 관계로 만나게 되어 반갑습니다 :) 
이번 미션에서는 JdbcTemplate을 직접 구현하여 기존 UserDao에 있던 DB 접근 로직을 제거했습니다.
평소에 DB에 관심 있기도 했고, 레벨 2에서 JdbcTemplate를 다뤄봤어서 재미있게 진행한 것 같습니다.
어색한 점이 있다면, 얼마든지 리뷰 남겨주세요! 잘 부탁드려요 🙇
> [JDBC 라이브러리 구현하기 - 1단계] 초코칩(권기호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/NonUniqueResultException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
> [1단계 - JDBC 라이브러리 구현하기] 로키(정해성) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/sample/Person.java
안녕하세요 종이! 리뷰이 명오입니다.
체스 미션 당시를 떠올려보며 구현해보았습니다.
미션 요구사항이 간단하여 큰 변경사항은 없습니다.
잘 부탁드립니다~
> [JDBC 라이브러리 구현하기 - 1단계] 명오(김형호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/logback.xml
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectParameterCountException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/samples/TestUser.java
미아 안녕하세요. 냥인입니다. 😸
미인팀 결성(ㅋㅋ)한 게 엊그제 같은데 벌써 레벨 4가 되었네요.
중복 코드를 좀 없애고 싶은 마음이 있지만, 
2단계가 리팩토링이니 일단 요구사항만 만족하고 제출합니다. 
다음 리뷰 요청 때 반영할 듯싶어요.
이번 미션 리뷰 잘 부탁드립니다. ㅎ ㅎ
> [1단계 - JDBC 라이브러리 구현하기] - 냥인(최가희) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/SimplePreparedStatementSetter.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 무빈! 구름 ⛅️입니다.
미션 요구 사항을 다음과 같이 이해했어요.
- 리팩터링은 UserDaoTest를 활용해 진행한다. 
- 이해: UserDaoTest를 통과한다.
- 중복을 제거하기 위한 라이브러리는 JdbcTemplate 클래스에 구현한다. 
- 이해: JdbcTemplate의 query, queryForObject, update를 구현한다.
- DataSource는 DataSourceConfig 클래스의 getInstance() 메서드를 호출하면 된다.
- 이해: 4단계 부분이라 생략
Step2 제목이 리팩토링이라 무리하지 않고, 간단하게 작성했어요. 
미리 리뷰 감사합니다!
> [1단계 - JDBC 라이브러리 구현하기] 구름(김민수) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallBack.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 폭포 🌊
이렇게 리뷰어, 리뷰이로 만나뵙게 되어 반갑습니다
벌써 마지막 미션이네요 이번 미션동안 잘 부탁드려요!
> [JDBC 라이브러리 구현하기 - 1단계] 프린(남기범) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetExtractor.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 메이슨~ 리뷰어로 만나게 되서 반갑네요!
1단계 제출합니다!
리뷰 잘부탁드립니다~
> [1단계 - JDBC 라이브러리 구현하기] 카피(김상혁) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/Password.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/GeneratedKeyHolder.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 마크~
리뷰이 리비입니다. jdbc 미션으로 만나게 되어 반갑습니다 ㅎㅎ
미션 진행해보았습니다! 리뷰 잘 부탁드립니다 🙇🏻‍♂️
> [1단계 - JDBC 라이브러리 구현하기] - 리비(이근희) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserRowMapper.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/DataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 러쉬 🏈 JDBC 라이브러리 미션의 리뷰이 제제입니다.
스터디에 이어 오랜만에 코드 이야기를 하게 됐네요 무척 기대가 됩니다 ㅎㅎ
궁금한 부분있으면 맘껏 질문해주세요! 잘 부탁드립니다 🙇‍♀️
참고로 이번 미션에서 가장 막막한 부분이 JdbcTemplate 테스트였는데요, 데이터베이스 접속 부분이 있어 일단 Mock으로 테스트진행했습니다.
> [1단계 - JDBC 라이브러리 구현하기] - 제제(장진우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/samples/TestUser.java
시소~ 안녕하세요🖐️리니입니다 ㅎㅎ
1단계는 실제 JdbcTemplate을 보면서 학습하고, 구현해보았어요.
테스트는 어떻게 작성해야할지 모르겠어서 우선은 mocking으로 테스트했습니다. 마음에 들지는 않아서 시소에게 좋은 방법이 있다면 도움 받고 싶어요 😊
2주간 리뷰 잘 부탁드립니다.!
> [1단계 - JDBC 라이브러리 구현하기] 리니(이예린) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/dao/rowmapper/UserHistoryRowMapper.java
- app/src/main/java/com/techcourse/dao/rowmapper/UserRowMapper.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/dao/rowmapper/UserHistoryRowMapperTest.java
- app/src/test/java/com/techcourse/dao/rowmapper/UserRowMapperTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/ConditionExpression.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/QueryBuilder.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/QueryMethod.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/query/InsertQuery.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/query/Query.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/query/SelectQuery.java
- jdbc/src/main/java/com/interface21/jdbc/querybuilder/query/UpdateQuery.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementResolverTest.java
안녕하세요 로키 콜리입니다 🥦 
사실 jdbcTemplate 구현 자체는 일찍 마쳤는데 querydsl 처럼 타입 안전한 queryBuilder를 구현해보고 싶어 조금 늦어졌어요. 생각보다 일이 커져서 포기할까 하다가 그래도 완주했습니다 하하..
우선 jdbc 내의 querybuilder 패키지 내에 있는 객체들은 이번 미션 목적과는 무관하니 리뷰 대상에서 제외해주셔도 좋을 것 같아요.
한가지 질문을 드리면 rowMapper를 통해 mapping 하는 객체들을 jdbcTemplate이 queryForObject와 query 등의 메서드 들에서 Object, List<Object> 를 반환하도록 했는데요. 이로 인해서 jdbcTemplate을 사용하는 상위모듈인 dao 계층에서 형변환이 필요했어요. 로키는 이러한 부분을 어떻게 처리했는지 궁금합니다.
4단계에 달하는 마지막 미션의 시작이네요!
잘 부탁합니다 로키 ⏲️
> [1단계 - JDBC 라이브러리 구현하기] - 콜리(김건우) 미션 제출합니다 🥦 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/CastingResultSetParser.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetParser.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/User.java
안녕하세요 초롱! 리뷰어로 만나니까 새롭네요. 리뷰 잘 부탁드립니다!
간단하게 JdbcTemplate에 두 종류의 메서드를 추가했습니다. 자원 close 하는 부분은 아직 신경쓰지 않았습니다. 좋은 방법이 있을지 생각해보는 중이라서요. 무작정 닫아버리니까 닫힌 자원이라는 예외가 발생하더라구요.
> [JDBC 라이브러리 구현하기 - 1단계] 로빈(임수빈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 다온! 리브입니다. 😊
레벨 2 때 다온과 페어를 하면서 다온의 기가막힌 테스트 코드를 전수 받은 기억이 있는데 이렇게 다시 만나게되어 무척 기쁩니다!
이번 JDBC 라이브러리를 구현하면서는 실제로 JdbcTemplate의 코드를 많이 참고했습니다. 😅
테스트도 최대한 꼼꼼히 작성하려 노력했는데 부족한 부분이 없을지 모르겠네요.
리뷰 잘 부탁드리고 즐거운 주말 되세요 🥹
> [1단계 - JDBC 라이브러리 구현하기] 리브(김민주) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/exception/DataAccessException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 호티! 클로버입니다.
이렇게 리뷰어와 리뷰이 관계로 만나게 되니 반갑네요 ^_^
이번 미션에서는 `UserDao`를 리팩토링 하는 것과 리팩토링을 위해 `JdbcTemplate`을 구현하는 걸 목표로 했어요.
미션을 진행하다 질문이 하나 생겼어요.
현재 JdbcTemplate 구현은 Connection과 PreparedStatement를 사용하다보니 테스트를 짜기 어려운 부분이 있었는데요, 직접 모두 제어할 수 없는 부분이라 mocking을 활용해야 한다고 생각했습니다. 
그래서 mocking을 통한 테스트 작성을 시도해봤는데, PreparedStatement가 어떤 값을 반환할지 미리 지정해두고 그 반환값에 대한 테스트를 진행하는게 의미가 없다고 느껴 결국 삭제했습니다.
따라서 현재 JdbcTemplate은 테스트가 없는 상태인데, 직접 구현한 부분에 대한 테스트가 없어 찜찜한 느낌이에요. 😢 
만약, 호티라면 어떤 방법을 사용해서 테스트할지 조언을 구하고 싶어 질문 드려요.
앞으로 2주동안 잘 부탁드립니다 🙇
> [1단계 - JDBC 라이브러리 구현하기] 클로버(이은정) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/TestEntity.java
안녕하세요 프린! 리뷰이 우주입니다~
1단계 미션에서는 이후 리팩토링 과정도 있다고 생각해 기능 구현에만 집중했습니다.
앞으로 잘 부탁드리겠습니다!!
> [1단계 - JDBC 라이브러리 구현하기] 우주(김성현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 구름! 처음으로 인사드리네요ㅎㅎ
다들 어렵지 않게 미션했다는 얘기들이 많은데 저는 좀 어려웠던 것 같아요..
특히 테스트 짜는 게 굉장히 어려웠습니다.
그럼 이번 리뷰 잘 부탁드립니다ㅎㅎ
> [jdbc 구현하기] 초롱 1단계 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/exception/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/exception/IncorrectResultSizeDataAccessException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 제리!
이번에 리뷰이로 만나게된 뽀로로입니다~
부족하지만, 잘 부탁드립니다~! 😀😀
> [1단계 - JDBC 라이브러리 구현하기] - 뽀로로(조경찬) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요~! 재즈 😊 
배키입니다 🙇‍♀️
팀원으로 지내다가 리뷰어로 보니 새롭네요..ㅎㅎ
1단계 제출합니다. 편하게 리뷰해 주세요~
미션 구현은 생각보다 괜찮았는데, 테스트 코드를 작성하는 게 너무 어려웠어요.
마지막 미션 잘 부탁드려요 👍
> [1단계 - JDBC 라이브러리 구현하기] 배키(백은희) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 레디 ! 켬미입니다 😊
이야기할 시간 없어서 아쉬웠는데, 이렇게 리뷰어-리뷰이로 만나서 반갑네요 ! 
일단 열심히 구현해봤는데 부족한 점이 있을 겁니다 ㅎㅎ
막힘없는 리뷰 부탁드릴게요 ~!
> [1단계 - JDBC 라이브러리 구현하기] 켬미(김경미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- docs/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 테니! 폭포입니다. 만나서 반갑습니다. 😄 
1단계 - JDBC 라이브러리 구현하기 구현 완료하여 PR 보냅니다.
구현 흐름은 아래와 같습니다.
* `UserDaoTest`를 활용하여 `UserDao` 클래스 구현
* `UserDao` 클래스의 중복 제거를 위해 `JdbcTemplate` 라이브러리 구현
* 구현한 `JdbcTemplate` 클래스를 바탕으로 `UserDao` 클래스 코드의 중복을 제거하며 리팩토링
* `JdbcTemplate` 테스트 작성
2단계가 `JdbcTemplate` 리팩토링이긴 하지만, 눈에 보이는 리팩토링이 필요한 부분들은 어느 정도 미리 적용시킨 상태입니다. 따라서, 리팩토링에 대한 리뷰를 미리 해주셔도 상관 없습니다! 편하게 리뷰 부탁드립니다. 🙇 감사합니다.
> [1단계 - JDBC 라이브러리 구현하기] - 폭포(이성주) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 망쵸! 
리뷰어로 망쵸를 만나는 것은 처음이네요 ㅎㅎ
오프라인에서도 말했듯이 메타인지를 잘 할 수 있게 물어봐주시면 좋을 것 같아요!
이번 미션 잘 부탁드려요!!
> [JDBC 라이브러리 구현하기 - 1단계] 타칸(최원준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserRowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
테드 안녕하세요 🥹
UserDao에서 JDBC API를 사용해 하나하나 설정해주던 것을 JdbcTemplate로 넣어주었습니다~~
다음 단계가 리팩토링인 만큼, 일단 요구사항에 나온 만큼만 작업했어요.
그럼 마지막 미션 잘 부탁드립니다~~
> [1단계 - JDBC 라이브러리 구현하기] 땡이(정지호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCreator.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/MockUser.java
안녕하세요 감자 🥔 반갑습니다 !
일단 완성을 우선으로 수행했습니다 ㅎㅎ
편하게 리뷰 해주세요~ 😄
> [1단계 - JDBC 라이브러리 구현하기] 테니(나아연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 포케 〰️👋🏻
잘 지내고 있나요?
바쁘시겠지만 리뷰 잘 부탁드려요 :)!
> [1단계 - JDBC 라이브러리 구현하기] 릴리(최윤서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/build.gradle
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/DatabasePopulatorUtils.java
- jdbc/src/test/java/com/interface21/jdbc/core/H2DataSourceConfig.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/resources/schema.sql
안녕하세요 콜리~!!! 이렇게 또 만나게 됐네요!
코드 품질도 품질이지만, 학습목표인 JdbcTemplate라이브러리 구현에 맞는 지식적인 질문을 해주시거나, 중복코드제거 측면에서 코드를 더 바라봐주시면 더 좋을 것 같습니다!
이번 미션 잘부탁합니다!
> [1단계 - JDBC 라이브러리 구현하기] 도도(김도선) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/build.gradle
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PrimitiveTypeConverter.java
- jdbc/src/main/java/com/interface21/jdbc/core/TypeConverterUtils.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/support/TestDataSourceConfig.java
- jdbc/src/test/java/support/TestUser.java
오랜만이에요 도라! 🙋🏻‍♂️
UserDao 작성 -> JdbcTemplate로 변경 -> JdbcTemplate 메서드 분리 순으로 진행해봤어요.
실제 JdbcTemplate은 참고하지 않고 구현해서 방식이 조금 다를 수 있어요.
리플렉션 사용이 적절한지, 코드가 깔끔한지, 테스트가 잘 작성되었는지 궁금해요.
이번 미션 잘 부탁드립니다!
> [1단계 - JDBC 라이브러리 구현하기] 트레 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/DataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 리브 선배님.
선배님께 귀중한 리뷰를 받을 기회가 주어져 무한한 영광입니다.
선배님께서 남겨주시는 어떠한 의견이라도 감사히 받고, 겸허한 마음으로 개선해 나가겠습니다. 
바쁘시겠지만, 부디 편안한 마음으로 리뷰해 주시면 감사하겠습니다.
감사합니다.
낙낙 올림.
> [1단계 - JDBC 라이브러리 구현하기] - 낙낙(이낙헌) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/support/domain/User.java
안녕하세요, 알파카! 🦙
리뷰어로 만나니 더 반가운 것 같습니다.
알파카는 `JdbcTemplate` 테스트를 어떻게 작성하셨나요?
저는 모두 Mocking을 통해서 작성했습니다. 알파카의 테스트 전략이 궁금합니다!
리뷰 잘 부탁드립니다!
> [1단계 - JDBC 라이브러리 구현하기] 리건(이한길) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcCallback.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcResourceCloser.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetHandler.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 이상~!
미션으로 만나서 매우 반갑네요 ㅎㅎ
레벨2때 했던 학습테스트를 참고하면서 구현해봤어요. 
테이블에서 여러 행을 조회할 때와 단일 행을 조회할 때 ResultSet을 처리하는 로직이 달라서, ResultSetHandler라는 인터페이스를 만들어서 추상화했습니다. 
리뷰 잘부탁드려요~!
>  [1단계 - JDBC 라이브러리 구현하기] - 제우스(신재우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 배키!
수요일이 미션시작 이었지만 게으름으로 인해 드디어 1단계를 완성하게 되었네요.. 😅
아래는 요구 사항 및 구현에 대한 정리 입니다!
개발자는 아래 사항만 집중할 수 있도록 한다.
- SQL 쿼리 작성
- 쿼리에 전달할 인자
- SELECT 조회 결과를 추출
해당 함수형 인터페이스를 만들어 `JdbcTemplate` 에서는 `UserDao` 넘겨준 `rowMapper` 를 사용하도록 하였습니다.
이로써 **SELECT 조회 결과를 추출** 요구 사항을 만족하였습니다.
위 항목을 진행하며 ` UserDao` 에 있는 메서드들은 `sql` 쿼리문 하나, `jdbcTemplate` 의 메서드 호출 및 리턴 하나로 라인 2개만 써서 기본적인 CRU 를 할 수 있도록 구성이 되었네요!
쿼리에 전달한 인자는 `PrepareStatement` 를 사용하였으며 `Object` 자료형의 배열을 전달하는 가변 인자를 사용하였습니다!
`JdbcTemplate` 을 구현할 때도 `try with resource` 구문과 `catch and logging` 구문이 비슷하게 중복되어 이를 `SqlExecutor` 인터페이스와 `execute` 메서드로 분리하였습니다!
<br>
바쁜 와중 리뷰를 부탁 드릴게요.. 배키!! 🤗
감사합니다~ 🎉
> [1단계 - JDBC 라이브러리 구현하기] 새양(양경호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/support/jdbc/init/TestDatabasePopulatorUtils.java
- jdbc/src/main/java/com/interface21/dao/support/DataAccessUtils.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
산초 반가워요~ JDBC 라이브러리 구현하기 미션으로 만나게 되었네요.
1레벨에서 가볍게 JdbcTemplate를 구현했어서 크게 어렵진 않았네요. 잘 부탁드려요~!
> [1단계 - JDBC 라이브러리 구현하기] - 마크(김승현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 비토!! 미션 리뷰어라니 반갑네요 😁
> 개발자는 SQL 쿼리 작성, 쿼리에 전달할 인자, SELECT 구문일 경우 조회 결과를 추출하는 것만 집중할 수 있도록 라이브러리를 만들자.
JdbcTemplate에서 어디까지 해주어야 할 지 고민하다가 ResultSet을 가공해서 원하는 객체로 매핑하는 과정은 JdbcTemplate의 사용자가 하도록 했습니다. 요구사항에서 말하는 "조회 결과를 추출"하는 행위라고 생각했어요! 놓친 부분이 있다면 가감없는 리뷰 부탁드려요 :)
잘 부탁드립니다 🙇🏻‍♀️🙇🏻‍♀️
> [1단계 - JDBC 라이브러리 구현하기] - 미아(이종미) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
잉크 안녕하세요,
jdbc 미션 리뷰이 무빈입니다!
마지막 미션으로 처음 인사하는 것 같네요!
되게 늦게 1단계 PR 을 쏘게 된 것 같습니다.
늦게 리뷰를 부탁하게 되어 죄송하고, 앞으로는 착실히 리뷰 요청 해보겠습니다 ㅎㅎ
아직 이번 미션에 필요한 지식이 충분치 않았다고 느꼈습니다.
그렇기에 각 단계에서 요구하는 요구치를 충족하는 것을 우선 노력해 보았습니다!
그러다보니 정말 간단한 코드가 되었네요!
- UserDao 객체에서 DB 연결 및 쿼리문 실행과 관련한 로직 제거
- 위 로직을 JdbcTemplate 클래스로 이동
- 이에 따라 RowMapper 인터페이스 생성
- JdbcTemplate 내 update, query, queryForObject 메서드는 중복된 부분이 정말 많습니다. 이를 추출하고 싶었는데, 어떻게 할 수 있을지 해답을 못 찾은 상태입니다. 2단계가 리팩터링이라 지금 깊은 고민은 하지 않았습니다만, 코드가 이쁘지 않더군요.
- 네이밍은 레벨 1 에서 JdbcTemplate 를 사용했던 경험을 돌아보면서 기존과 비슷하게 네이밍을 하려고 했습니다. 혹시 다른 부분이 있다면 제안 주시면 감사하겠습니다!
- JdbcTemplate 에 대한 테스트를 작성하지 못했습니다. mocking 을 해야만 테스트를 작성할 수 있을지에 대해서 고민하고 있었는데, 혹시 잉크는 어떻게, 무슨 관점으로 JdbcTemplate 에 대한 테스트를 구성하셨나요?
많이 부족하지만, 이번 미션도 잘 부탁드립니다!!
잉크도 미션과 프로젝트 모두 화이팅입니다 🙌
> [1단계 - JDBC 라이브러리 구현하기] 무빈(김현중) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/TestUser.java
> [1단계 - JDBC 라이브러리 구현하기] 잉크(이예찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserMaker.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/Maker.java
- jdbc/src/main/java/com/interface21/jdbc/core/ObjectMaker.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
제제 안녕하세요! 아토입니다.
레벨1때 술 한 번 마셔보고 이후로 첫 인연이네요! 반가워용
저는 이번 미션으로 세 번의 리뷰어가 모두 선릉캠이 되었답니다.... ㅎㅎ
레벨1때 자바를 처음 써보고, 레벨2때 스프링을 처음 써보고, 두 번째 미션으로 (당연하게도) JDBC 또한 처음 써봤는데요,
그 이후로도 JDBC를 사용할 일이 없었어서 잘 모르는 상태로 lms와 첨부된 문서만을 보며 구현했습니다!
최대한 원래의 JdbcTemplate을 보지 않고 하려고 해서 조금 어색하거나 미숙한 부분이 있을 수 있어요 🥹
일단은 TODO를 먼저 채워보려고 했고... 그 이후 공통 부분을 분리하려고 해보았습니다
구현 내내 오잉또잉 하면서 진행했네요... ㅋㅋㅋㅋㅋ
그렇다면... 편하게 리뷰 남겨주시죠!
> [JDBC 라이브러리 구현하기 - 1단계] 아토(이혜린) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 폴라! 한 번도 같이 얘기해볼 기회가 없었던 것 같은데, 만나서 반갑습니다😄
리뷰 잘 부탁드립니다 :)
> [1단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/application.yml
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 커비! 😇
미션으로 처음 만났네요 반갑습니다!!
이번 미션은 단순하게 JDBC 기능 구현을 해봤습니다.
리뷰 잘 부탁드립니다~~ 🙇🏽‍♂️
> [1단계 - JDBC 라이브러리 구현하기] - 이상(이건상) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 켬미~~ 2단계로 돌아왔습니당
리팩터링 부분이라서 변경사항이 많지 않네요.
1단계에서 다음 다음 부분들은 이미 충족되어 있었어요
- 커스텀 Exception을 추가해서 사용자는 Unchecked Exception이 되도록 변경하자.
- RowMapper 인터페이스을 제네릭을 사용하도록 개선해보자.
이번 단계에서는 콜백함수를 적용해서 `Connection try-catch 부분을 분리`해봤습니다.
더 좋은 아이디어가 있다면 알려주세요!
이번 리뷰도 잘 부탁드립니다🙇🏻‍♂️
> [2단계 - JDBC 라이브러리 구현하기] 러쉬(이태훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/mapper/UserRowMapper.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/mapper/UserRowMapperTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/TestUser.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 안나!
리뷰어로 만나뵙게되어 반갑습니다 👋
최대한 간단하게 구성하기 위해 노력했고, 열심히 구현했습니다 😊
잘부탁드리겠습니다 🙇‍♂️
> 추가적으로 `queryForObject` 메서드에서 반환값이 아무것도 없거나 여러개인 경우에 예외를 던지게 구성했었는데, 기존 `UserDaoTest`에서 데이터를 넣은 후 따로 롤백이 이루어지지 않기에 임의로 새로운 데이터를 넣고 `findByAccount`를 검증하게 되었습니다
> [1단계 - JDBC 라이브러리 구현하기] 호티(윤주호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
안녕하세요 구름!
2단계를 진행하려고 봤는데 1단계에서 어느정도 진행이 된 것 같더라구요..
2단계를 어느정도 읽어보고 1단계를 진행할 걸 그랬네요😭
LMS에 있는 다이어그램을 따라가보려고 했는데 JdbcTemplate이 왜 추상 클래스로 되어있는지, 그 의도를 파악하는 데에 실패했네요..
그래서 우선 `PreparedStatementSetter` 인터페이스만 추가해보았습니다.
또한, 파라미터가 전달되지 않는 경우에는 PreparedStatementSetter가 생성되지 않도록 구현해보았어요
이번 리뷰도 잘 부탁드립니다!
> [JDBC 구현하기 2단계] 초롱 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/logback.xml
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 커찬, 폰드입니다🙇‍♂️
`JdbcTemplateTest`에서 자원 반환 부분만 확인하였는데,
어떻게 개선할 수 있을지 혹시 의견 있으시다면 여쭙고 싶네요!
리뷰 잘 부탁드리겠습니다!
> [1단계 - JDBC 라이브러리 구현하기] 폰드(권규택) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 로빈! 레모네 입니다.
로빈과 코드 이야기는 처음이라 기대되네요 😎
실제 jdbcTemplate의 메서드 구조를 참고하여 구현해 보았습니다.
리뷰 잘 부탁드립니다!
> [1단계 - JDBC 라이브러리 구현하기] - 레모네(이지현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 뽄드 :> :> :>
만나서 너무 반갑네요 ^_________^
1단계는 요구사항이 많지 않아서 우선 일반적인 리팩토링이라고 생각하고 가볍게 구현해봤습니다!
리뷰 주고받으면서 서로 공부가 되었으면 합니다
리뷰 잘 부탁드려요 😘😘
> [1단계 - JDBC 라이브러리 구현하기] 도비(김도엽) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/build.gradle
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryConsumer.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryFunction.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 카피😊
리뷰어로 만나서 정말 반갑습니다.
전반적인 내용은 모두 LMS 에 나온 그대로 구현했습니다.
그럼 이번 리뷰도 잘 부탁드립니다!😇
> [1단계 - JDBC 라이브러리 구현하기] 산초(나영서) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/SqlExecutorTest.java
미아 안녕하세요. 냥인입니다. ㅎ‿ㅎ
리팩터링 생각보다 많이 어렵네요...
~~LMS 내용 파악하는 게 어려웠어요.~~ ㅎㅎㅎㅎㅎ😆
그래서 유명한 스프링 도서의 도움 좀 받았는데, 요구사항에 맞게 구현했는지 잘 모르겠어요.
이번에도 리뷰 잘 부탁드립니다.
남은 주말도 즐거운 시간 되세요. 🤍
> [2단계 - JDBC 라이브러리 구현하기] 냥인(최가희) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/dao/ResultNotSingleException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/TestUser.java
안녕하세요 리니 반갑습니다!
1단계 미션 진행하여 리뷰 요청 드립니다.
UserDao에서 jdbc를 직접 사용하지 않고 JdbcTemplate을 통하여 편하게 사용할 수 있도록 변경했습니다.
편하게 리뷰 부탁드려요~
> [1단계 - JDBC 라이브러리 구현하기] 테드(김규태) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetExtractor.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapperResultSetExtractor.java
- jdbc/src/test/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetterTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/RowMapperResultSetExtractorTest.java
안녕하세요 폭포!
이번 단계에서는 2가지에 초점을 두고 리팩터링을 진행했습니다
1. `PreparedStatement`의 place holder를 채우는 책임을 `PreparedStatementSetter` 함수형 인터페이스로 추상화
2. `ResultSet`의 데이터를 추출하는 책임을 `ResultSetExtractor<T>` 함수형 인터페이스로 추상화
감사합니다 :)
> [JDBC 라이브러리 구현하기 - 2단계] 프린(남기범) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallBack.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetCallBack.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
조이썬 안녕하세요. 아톰입니다. JDBC 라이브러리 1단계 구현했습니다.
리뷰 잘 부탁드립니다. 🙇🏻‍♂️
> [1단계 - JDBC 라이브러리 구현하기] - 아톰(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/dao/NoResultFoundException.java
- jdbc/src/main/java/com/interface21/dao/NotSingleResultException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ObjectMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 이든! 오랜만이네요!!
우선은 사용자가 라이브러리를 편하게 사용할 수 있도록 만드는 것에 초점을 맞추었어요.
`JdbcTemplate` 에 대한 테스크 코드를 작성해 보고 싶었는데, "쿼리를 잘 실행할 수 있다" 라는 것을 어떻게 테스트 해야 할 지 잘 생각이 나지 않아 일단 테스트 코드는 비워둔 상태입니다.
파라미터 바인딩도 조금은 마음에 들지 않지만, 일단 주어진 요구사항을 만족시키는 데 집중해 보았어요!
잘 부탁 드립니다!
> [1단계 - JDBC 라이브러리 구현하기] 짱수(장혁수) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementResolver.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementResolverTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
시소, 안녕하세요~
1단계에서 이미 어느정도 리팩토링을 진행했다보니, 빠르게 2단계로 돌아왔습니다🖐️
이번 pr에서의 변경사항은 다음과 같아요!
- `PreparedStatementResolver` 분리
- `UserHistoryDao` 리팩터링
이번 리뷰도 잘 부탁드립니다:)
> [2단계 - JDBC 라이브러리 구현하기] 리니(이예린) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/dao/UserRowMapper.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
릴리 안녕하세요~ 주말은 잘 보내셨나요?
우선 1단계 기능 구현하고 먼저 제출 드립니다!
\+ JdbcTemplate에 대한 테스트는 고민하다가 일단 생략했습니다. UserDaoTest에서 JdbcTemplate를 사용하고 있기도 하고, JdbcTemplate의 테스트는 mock을 대부분 사용할 것 같아 실제 동작을 검증한다고 할 수 없다고 생각했어요~
감사합니다!
> [1단계 - JDBC 라이브러리 구현하기] 상돌(이상진) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/mapper/UserRowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
- study/src/test/resources/schema.sql
안녕하세요, 땡이! 주말 잘 보내셨나요?
2단계의 리팩터링 요구 사항에 맞게 수정했습니다.
어색한 점이 있다면, 리뷰 부탁드립니다 🙇
1. IllegalArguementException에서 DataAccessException 사용하도록 변경
2. RowMapper, PreparedStatementSetter 인터페이스 분리
> [2단계 - JDBC 라이브러리 구현하기] 초코칩(권기호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- docs/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/exception/DatabaseException.java
- jdbc/src/main/java/com/interface21/jdbc/exception/UnexpectedResultSizeException.java
- jdbc/src/test/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetterTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요, 테니! 2단계 요구사항 구현 완료하여 PR 보냅니다.
1단계에서 구현한 코드가 2단계 리팩토링의 대부분의 요구사항을 만족했다보니, 큰 적용사항은 없었던 것 같아요. 주요 변경점은 아래와 같습니다.
* 처음에는 LMS의 그림에 맞추어 `PreparedStatementSetter`를 구현해보았습니다. 그런데 오히려 가변 인자를 사용했을 때보다 코드가 더 복잡해지는 것을 느끼고 다시 되돌렸습니다. `매번 PreparedStatementSetter 인터페이스를 구현하려니 번거롭다. 가변인자를 사용해서 좀더 편리하게 만들 수 없을까?` LMS에 적혀있는 이 문구가 제가 겪은 경험을 대변하고 있는 것 같다는 생각도 들었습니다.
* `JdbcTemplate`의 전체적인 코드를 개선했습니다. (메서드 네이밍, 메서드 분리 등등)
* 라이브러리가 Unchecked Exception이 되도록 Custom Exception을 적용했습니다.
리뷰 부탁드립니다. 감사합니다! 🙇
> [2단계 - JDBC 라이브러리 구현하기] 폭포(이성주) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentsPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/DataSizeMismatchException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetExtractor.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapperResultSetExtractor.java
- jdbc/src/test/java/com/interface21/jdbc/core/ArgumentsPreparedStatementSetterTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/RowMapperResultSetExtractorTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
페드로 안녕하세요~ 2단계로 돌아왔습니다. 이번 단계에서는 약간 머리 맞았는데요.. 1레벨 체스에서 했던 대로 `ResultSet` 만들고 진행했는데 완전 그걸 모른 상태로 하면 더 즐거웠을 듯해요. 아쉬운대로 몇 가지 보이는 것들에 대한 추상화, 테스트 보강을 진행했습니다.
잘 부탁해요~
> [🔥 JDBC 라이브러리 구현하기 - 2단계] 아루(이동훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlParameterSource.java
- jdbc/src/main/java/com/interface21/jdbc/core/mapper/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/sql/Sql.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/SqlParameterSourceTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/mapper/RowMapperTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/mock/FakeResultSet.java
- jdbc/src/test/java/com/interface21/jdbc/core/mock/User.java
- jdbc/src/test/java/com/interface21/jdbc/core/sql/SqlTest.java
안녕하세요 도비! 리뷰 잘 부탁드립니다!
- JdbcTemplate 테스트도 작성해야하는데 시간이 너무 걸릴거 같아 우선 1차 제출드립니다..!
- 실제 JdbcTemplate은 ```insert```라는 이름의 메서드는 없지만 편의상 이렇게 작명하였습니다!
> [1단계 - JDBC 라이브러리 구현하기] 켈리(양성욱) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/CannotQueryException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 커비~ 😇
2단계는 1단계에 작성한 코드를 가이드에 맞게 리팩터링하는 것이 미션이었습니다.
이미 어느정도 구성을 비슷하게 가고 있어서 PreparedStatementSetter 인터페이스를 추가하고 JdbcTemplate 메서드들에 적용했습니다.
그리고 transactional propagation 학습테스트도 함께 제출합니다.
바쁜 스케쥴에도 힘내시고 리뷰 잘 부탁드릴게요!
감사합니다. 🙇🏽‍♂️
> [2단계 - JDBC 라이브러리 구현하기] 이상(이건상) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/CannotGetJdbcConnectionException.java
- jdbc/src/main/java/com/interface21/jdbc/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/IncorrectBindingSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapperFactory.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
제우스, 안녕하세요~ 한글날 잘 쉬고 계신가요? 
2단계를 읽어봤는데, 대부분 1단계에서 진행한 내용 같아서요. 
약간의 리팩터링과 학습 테스트를 추가해서 곧바로 리뷰 요청해요 😀 
혹시 제가 빠뜨린 부분이나, 좀더 개선하면 좋을 부분이 있다면 알려주세요!
> [2단계 - JDBC 라이브러리 구현하기] 망쵸(김주환) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 망쵸! 
이번 step2에서는 이전 단계에서 요구사항을 대부분 지킨 것 같아서 파일 변화가 별로 없네요!
학습 테스트도 같이 해서 커밋해두었습니다!
이번에도 잘 부탁드려요!!
> [2단계 - JDBC 라이브러리 구현하기] 타칸(최원준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryExecution.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 테바!
레벨 2 이후에 오랜만에 뵙는 것 같아요!
잘부탁드립니다~!
> [1단계 - JDBC 라이브러리 구현하기] - 호기(조호연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetterTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 다온~ 리브입니다!
2단계 리팩터링 완료하여 PR 보냅니다.
운이 좋게도(?) 1단계 때 구현된 부분이 많아서 큰 변화는 없었습니다. 😭
학습 테스트도 같이 포함했으니 리뷰 잘 부탁드립니다. 😊
> [2단계 - JDBC 라이브러리 구현하기] 리브(김민주) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 카고!
2단계 리뷰요청드립니다
미션 설명을 보고 PreparedStatementSetter 를 만들었는데 의미있는 리팩토링인지 잘 모르겠네요
잘 부탁드립니다~
> [2단계 - JDBC 라이브러리 구현하기] 잉크(이예찬) 미션 제출합니다.

- TODO.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/RowMapperTest.java
- jdbc/src/test/java/com/interface21/jdbc/support/TestUser.java
> [Step1] 테바(김성겸) JDBC 라이브러리 구현하기 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserRowMapper.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
릴리 안녕하세요~ 
지난 단계에서 도움주신 덕분에 이번 단계에서는 수정할 부분이 그렇게 많진 않았던 것 같아요~
학습 테스트는 조금 더 확인해보고싶은 부분이 있어 허락해주시면 3단계 제출때 같이 하고, 아니면 다음 리뷰때 함께 제출하겠습니다!
즐거운 주말 보내세요~
> [2단계 - JDBC 라이브러리 구현하기] 상돌(이상진) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/StatementExecutor.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 리브!!
기존 1 단계에서 이미 구현된 부분이 많아, 변경 사항이 많지 않습니다!!
편하게 리뷰 주시면 감사하겠습니다 :)
> [2단계 - JDBC 라이브러리 구현하기] 낙낙(이낙헌) 미션 제출합니다.

- README.md
- jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
- jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapperResultSetExtractor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementSetterTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/RowMapperResultSetExtractorTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/support/User.java
- jdbc/src/test/java/com/interface21/jdbc/core/support/UserRowMapper.java
안녕하세요 명오! 제리입니다
<br>
**리뷰 시 참고사항**
- connectionpool 학습 테스트는 3단계에서 함께 제출하겠습니다.
<br>
편하게 리뷰 남겨주세요 감사합니다 🙇‍♀️🙇‍♀️
> [2단계 - JDBC 라이브러리 구현하기] 제리(김민정) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/build.gradle
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요. 아톰
2단계 완료 헀습니다.
기존 코드랑 크게 바뀐 점이 없는 것 같습니다.
더 개선 할 점을 찾아보려고 했지만 눈에 크게 들어오는 점이 없어서 리뷰 요청 보내요.
추가로 1단계에서 학습 테스트가 merge되는 바람에 리뷰를 못 받아서 이 부분도 봐주시면 감사하겠습니다.
잘 부탁드립니다.!
> [2단계 - JDBC 라이브러리 구현하기] 위브(김기범) 미션 제출합니다.

- README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/exception/JdbcSQLException.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 레디 😊 2단계로 찾아온 켬미입니다 ~!
2단계 미션을 진행하면서 추가된 기능은 다음과 같습니다 
- 함수형 인터페이스 사용
- 제네릭 사용
- 익명 클래스(람다) 사용
저번 미션에서 리펙터링을 일부 해놔서 변경 사항이 많지 않네요 !
추가적 학습 테스트도 진행하였습니다 ~ 확인 부탁드려요 !
이번 미션도 리뷰 잘 부탁드립니다 ~ 😁
+) 저번 미션에서 이야기했던 DI 로직은 현재 [JDBC 라이브러리 구현하기]라는 미션에 학습할 주요 키워드가 아니라고 판단해 추가하지 않았습니다 ~ 하지만 만약 DI 로직을 구현했더라면 레디와 이야기 나누었던 것처럼 컨트롤러 단부터 서비스를 의존성 주입하는 방식으로 변경할 것 같습니다 !
```java
public UserController(final UserService userService) {
this.userService = userService;
}
```
> [2단계 - JDBC 라이브러리 구현하기] 켬미(김경미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/ConsumerWrapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/StatementParamSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/ThrowingConsumer.java
- jdbc/src/test/java/com/interface21/jdbc/core/StatementParamSetterTest.java
- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/User.java
- study/src/test/resources/hikari.properties
안녕하세요 감자~!
테코톡 준비하느라 2단계 리뷰요청이 많이 늦었습니다 ㅠㅡㅠ
1단계에서 남겨주신 리뷰도 반영했어요 😄
편하게 리뷰해주세요~!
> [2단계 - JDBC 라이브러리 구현하기] 테니(나아연) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 마크..! 어떤 부분을 리팩터링 해야할 지 고민이 많았는데 잘 생각이 떠오르지 않아요.
우선은 템플릿 콜백 메서드 패턴을 이용해서 공통되는 로직을 추상화하고 변경될 수 있는 로직을 람다로 다루도록 리팩터링 했습니다~
이번 리뷰도 잘 부탁드립니다 🙇🏻‍♂️
> [2단계 - JDBC 라이브러리 구현하기] 리비(이근희) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/Callback.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/jdbc/exception/CannotGetJdbcConnectionException.java
- jdbc/src/main/java/com/interface21/jdbc/exception/JdbcQueryException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 프람!
2단계 구현 완료하여 리뷰 요청합니다.
1단계 때 이미 어느 정도 완성이 되어서 변경사항이 많지 않네요.
DM으로 말씀드린 학습 테스트도 포함하였습니다.
이번 단계도 잘 부탁드립니다!
> [2단계 - JDBC 라이브러리 구현하기] 메이슨(김경원) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 망쵸!
빠르게 3단계도 구현해보았습니다!
코드 파일 변경이 조금 있는데 실질적으로 했던 작업은 별로 없는 것 같네요 ㅎㅎ;;
이번에도 잘 부탁 드려요!!🙇‍♂️
> [3단계 - JDBC 라이브러리 구현하기] 타칸(최원준) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
잉크 안녕하세요!
3단계로 다시 뵙네요 ㅎㅎ
이번 단계는 transaction 적용하기 였습니다.
지식이 많지 않다보니 최대한 LMS 에서 제시한 방향대로 구현하게 된 것 같아요.
그렇기 때문에 기존의 UserServiceTest 의 테스트를 통과하는 것을 목표로 두게 되었어요.
- UserDao, UserHistoryDao 에 connection 을 주입받아 동작하는 메서드 구현
- UserService 에서 한 트랜잭션으로 위 메서드들을 관리
- 이를 위한 TransactionManager 구현
입니다.
지난 단계에서 함수형 인터페이스를 사용하라는 것에 힌트를 얻어, TransactionManager 의 책임을 jdbc 패키지로 옮기면서 Runnable 을 받아 처리할 수 있도록 구현해 보았습니다!
또한 static 처리를 통해 connection 을 다루는 어디서든 한 transaction 으로 관리하도록 했습니다.
이번 3단계도 잘 부탁드리고 잉크도 미션 화이팅입니다!!
> [3단계 - Transaction 적용하기] 무빈(김현중) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/JdbcConfig.java
- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/service/UserServiceImpl.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionProxy.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/transaction/TransactionManagerTest.java
- jdbc/src/test/java/com/interface21/jdbc/transaction/TransactionProxyTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/connectionpool/stage2/Stage2Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 트레 💩🐾 감자입니다
학습 테스트가 어려워서 3단계 제출 못 할 뻔했네요 🥲
3단계 리뷰도 잘 부탁드립니다 🙇‍♀️
>  [3단계 - JDBC 라이브러리 구현하기] 감자 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplateException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 프린! 우주입니다.
1. 2단계는 이전 1단계에서 이미 진행한 내용이 많이 포함된 것 같아 어딜 고쳐야할 지 잘 모르겠더라구요... 혹시 부족한 부분 있다면 알려주세요!
2. custom 예외처리 관련해서 상황에 따라 다른 unchecked exception으로 처리하고 싶었습니다. 그러나 코드가 공통적으로 SQLException을 던지고 있어 분기 처리하기 힘든 것 같아 바로 PR 제출 했습니다
잘 부탁드립니다!
> [2단계 - JDBC 라이브러리 구현하기] 우주(김성현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/java/transaction/DatabasePopulatorUtils.java
- study/src/main/resources/application.yml
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
- study/src/test/java/transaction/stage2/UserRepository.java
- study/src/test/java/transaction/stage2/UserRepositoryImpl.java
안녕하세요 초롱! 개인적으로 비즈니스 로직과 뒤석이는 걸 허용하면서 트랜잭션을 적용하는 것 자체는 학습 관점에서는 아무것도 얻어가는 것이 없다는 생각이 들었어요. 이번 단계를 구현하면서 빨리 다음 단계를 진행하고싶다는 욕구만 잔뜩 들었네요 😅
반면, 학습 테스트는 유용한 부분이 많았어요. 테크니컬 라이팅 주제인 가상 스레드에 대해 공부할 때 커넥션 풀 설정과 성능 사이의 이해하지 못한 결과가 있었는데, 그 이론적 배경을 알아냈거든요. PreparedStatement가 대체 뭘 준비하는건지 잘 몰랐었는데, 관련 내용도 학습할 기회여서 좋았어요. 스프링의 트랜잭션 전파는 좀 더 파봐야 할 것 같긴 하네요.
결론적으로 **이번 리뷰에선 학습 테스트 위주로 이야기 나눠보면 좋을 것** 같아요!
> [3단계 - JDBC 라이브러리 구현하기] 로빈(임수빈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- study/src/main/resources/schema.sql
- study/src/test/java/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
안녕하세요 뽀오오온드
2단계 요구사항 적절히 적용해봤습니다!
저는 PreparedStatementSetter가 생기면 오히려 요구사항에 적혀있는 `매번 PreparedStatementSetter 인터페이스를 구현하려니 번거롭다. 가변인자를 사용해서 좀더 편리하게 만들 수 없을까?`를 적용하는 것과 반대된다고 생각되었습니다.
따라서 기존의 코드에서 가변인자로 주어져서 JdbcTemplate 자체에서 `PreparedStatement`에 가변인자로 주어진 파라미터 값이 매핑되도록 두었습니다.
요부분에 대해서 집중적으로 얘기 나눠보고 싶네요 :>
리뷰 잘 부탁드립니다!
> [2단계 - JDBC 라이브러리 구현하기] 도비(김도엽) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/util/SQLExceptionUtil.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/main/java/com/interface21/transaction/util/SQLExceptionUtil.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
미아 안녕하세요~ ㅎ.ㅎ
3단계 요구사항대로 changePassword()에 트랜잭션 경계를 설정해서 원자성을 보장해 주었는데요, 다시 코드가 예쁘지 않게 돌아왔습니다. 
그래서 4단계 진행을 기다리고 있어요. ㅋ‿ㅋ
이번 리뷰도 잘 부탁드려요. 😸
+) 아 그리고 질문이 한 가지 있는데요, 미아는 트랜잭션 경계 설정을 위한 DataSource를 어디에서 가져올 것인가요? 
저는 UserService가 DataSource를 필드로 갖게 하고, 이를 외부에서 주입받는 형태로 구현하였습니다. 당연히 좋은 구조는 아니지만 서비스에서 트랜잭션을 설정하고 있는 형태에서는 이게 최선의 구조라고 생각하였어요.
> [3단계 - Transaction 적용하기] 냥인(최가희) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 제리~ 
이번 단계도 리뷰 잘 부탁드립니다~ 😀
> [2단계 - JDBC 라이브러리 구현하기] 뽀로로(조경찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionRollbackException.java
안녕하세요, 알파카! 🦙
3단계 미션 코드를 들고 빠르게 돌아왔습니다.
미션에서 의도한 방향이겠지만 서비스 코드가 조금 더러워진 것 같습니다..
리뷰 잘 부탁드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 리건(이한길) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementSetterTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 리니!
미션 2단계 완료하여 리뷰 요청 드립니다.
1단계 구현하면서 이것저것 하다보니 리팩터링이 일부 되었었네요. 리팩터링 할 부분 조금 더 찾아 반영해봤습니다.
리뷰 잘 부탁드립니다!
> [2단계 - JDBC 라이브러리 구현하기] 테드(김규태) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/SQLFunction.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 포케 :)
3단계 진행하면서 코드가 뭔가.. 파라미터도 많아지고 지저분해지네요 😅
리뷰 잘 부탁드립니다! 
감사합니다~
> [3단계 - Transaction 적용하기] 릴리(최윤서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 클로로루실후르바!
이번 단계는 4단계에서 진행될 리팩토링 및 동기화 구현 없이 트랜잭션 로직 구현만 진행해서 그런지 추가된 점이 많지 않네요..
이번 단계도 잘 부탁드립니다~ 🙇
> [3단계 - JDBC 라이브러리 구현하기] 알파카(최휘용) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
안녕하세요 테바!
리팩토링에 대해 많이 만질게 없었습니다..!
이번 단계도 잘부탁드립니다!
> [2단계 - 리팩터링] 호기(조호연) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 카피 ☕️
늦게 리뷰 요청 드리게 되었습니다..😢
늦은 만큼 주말동안 열심히 달려봐요!!
> [2단계 - JDBC 라이브러리 구현하기] 산초(나영서) 미션 제출합니다.]

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 새양.
미션 종료 시점까지 얼마남지 않았네요 .😭
리뷰주시면 최대한 빠르게 반영하고 요청드리겠습니다 
4단계 미션에서 비즈니스 로직과 인프라 로직을 분리하는 요구사항이 있어,리팩터링도 그때 많이 적용하면 좋을거 같아요.
이번 리뷰도 잘부탁드립니다.,
> [3단계 - JDBC 라이브러리 구현하기] 프람(김민종) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ParameterSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 구름!!
학습테스트가 너무 어려워서 한참을 헤매다가 이제서야 제출하게 되었습니다..
한참을 헤맸지만 아직도 여전히 모르겠더라구요..ㅎㅎ
그리고 이번 단계에서는 구름이 얘기하신대로 코드가 정말 엉망이 되더라구요..
얼른 4단계를 시작해서 다 뜯어 고쳐버리고 싶습니다.
그럼 이번 리뷰도 잘 부탁드립니다!!
> [JDBC 구현하기 3단계] 초롱 미션 제출합니다.

- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/ConnectionCallback.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionJdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
제우스, 안녕하세요. 망쵸입니다 😀 
3단계 완성해서 리뷰 요청드려요. 
3단계를 처음 진행했을 때, 서비스에서 커넥션을 만들고 트랜잭션 경계를 정하고 dao 로직을 호출하게 했어요. 코드가 굉장히 별로더군요. 
4단계에서 스레드 로컬을 사용하는 걸로 알고 있어요. 정답은 알지만, 현재 단계에서 최대한 리팩터링하고 싶었어요! 
커넥션을 서비스에서 직접 다루지 않고 싶었고, 서비스에 서비스 로직만 남기기 위해 노력했어요. 하지만, 실패했답니다.. 단순 리팩터링으로는 어렵더군요. 불가능하기에 스프링에서는 스레드 로컬을 사용하지 않을까 하는 생각이 들었어요. 
조금 보기 불편한 코드가 있을 수 있어서, 양해 부탁드려요 🙇‍♂️ 4단계에서 대부분의 코드가 삭제될 거라 생각하고 있어요!
> [3단계 - JDBC 라이브러리 구현하기] 망쵸(김주환) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/controller/LogoutController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/controller/UserSession.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTransactionTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCreator.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionalCallback.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTransactionTemplateTest.java
안녕하세요 페드로? 이번 단계 진짜 재미있었습니다 ㅋㅋㅋ JdbcTemplate에서는 아무리 생각해도 트랜잭션이나 Connection을 다루는 게 참 별로였는데 (Connection을 받아올 책임이 없고, 직접 PreparedStatement와 소통하는 것이 중심임), 새로운 객체를 도출해내서 나름 뿌듯합니다.. 페드로는 어떻게 보실지 모르겠네요.
리뷰 포인트는
1. `JdbcTemplate`에서 Connection을 다루지 않음 (PreparedStatementCreator가 Connection을 가지고 이를 바탕으로 생성합니다)
2. `JdbcTransactionTemplate` 내부에 선언한 `interface`를 클래스로 분리해야 할지
3. 전체적으로 코드가 읽기 편하고, 의도를 잘 알아볼 수 있는지
4. 빼먹은 테스트는 없는지...
정도입니다. 이번에도 잘 부탁해요~
> [🔥 JDBC 라이브러리 구현하기 - 3단계] 아루(이동훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/dao/mapper/UserHistoryRowMapper.java
- app/src/main/java/com/techcourse/domain/User.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/JdbcTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/transaction/stage1/Stage1Test.java
안녕하세요 땡이! 😄 초코칩입니다.
이번 3단계 미션에는 트렌젝션을 적용하는 것을 목표로 했습니다~
이번 단계에서도 잘 부탁드려요 👋
1. 트랜잭션 적용
2. UserHistory RowMapper 적용
3. 학습테스트 phantom read 버그 수정
> [3단계 - JDBC 라이브러리 구현하기] 초코칩(권기호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 이상~! 👋
3단계에서는 단순히 LMS의 요구사항만 만족시키기 위해 구현했습니다. 
그래서 JDBC의 구현은 변경하지 않고, UserService와 UserDao, UserHistoryDao에서 DB 커넥션과 PreparedStatement를 직접 다루게 두었어요. 
트랜잭션을 위해 Connection 객체를 파라미터로 받는 메서드들은 원래 있던 메서드를 변경하는 대신 오버로딩했습니다. 
또, transaction 학습 테스트도 추가했어요. 
3단계도 잘부탁드려요~!!
> [3단계 - JDBC 라이브러리 구현하기] 제우스(신재우) 미션 제출합니다. 

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/ConnectionConsumerWrapper.java
- jdbc/src/main/java/com/interface21/jdbc/ThrowingConnectionConsumer.java
- jdbc/src/main/java/com/interface21/jdbc/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 레모네!
좀 더 리팩토링을 해보고 싶었는데 4단계가 리팩토링에 가까운 것 같아서 최소한의 요구사항만 만족시키고  리뷰요청 보냅니다!
남은 미션도 잘부탁드려요!
> [3단계 - JDBC 라이브러리 구현하기] 비토(오상훈) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/support/AbstractErrorCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/ErrorCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2BadGrammarsErrorCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2CanNotAcquireLockCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2DataAccessResourceFailureCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2DataIntegrityViolationCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2DuplicateKeyErrorCodes.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2SQLExceptionTranslator.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcNoResultTransactionCallback.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransaction.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransactionTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/support/H2SQLExceptionTranslatorTest.java
조이썬 안녕하세요. 아톰입니다. 
이번에는 트랜잭션 기능을 구현했습니다. 그리고, 트랜잭션과 관련된 다음 클래스들을 추가했어요.
- JdbcTransaction
- JdbcTranscationManager
- JdbcTransactionTemplate
- JdbcNoResultTransactionCallBack
이전에 피드백 주신 ErrorCodes를 각각 클래스로 분리했어요. 어색한 부분이 있다면 피드백 부탁 드립니다.
이번에도 잘 부탁 드립니다. 🙇🏻‍♂️
> [3단계 - JDBC 라이브러리 구현하기] 아톰(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionManager.java
안녕하세요 애버~ 커찬입니다.
빠른 구현에 놀라셨나요? (저도 오늘 3단계 구현할 줄 몰랐습니다.)
LMS에 있는 요구사항 위주로 구현해 보았습니다
(Connection 로직과 비즈니스 로직이 같이 있는 상황이 너무 마음에 들지 않지만요;;)
개선은 TransactionSynchronizationManager를 통해 4단계에서 해보도록 하겠습니다. 요구사항과 클린 코드를 중점으로 리뷰 부탁드릴께요!
c.f. 학습 테스트는 4단계 PR과 같이 올려도 괜찮을까요?
> [3단계 - JDBC 라이브러리 구현하기] 커찬(이충안) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTransactionManager.java
안녕하세요, 다온. 리브입니다!
오랜만에 레벨 1하는 기분이 들어서 너무 재밌었네요 ㅋㅋㅋ
서비스에서 최대한 트랜잭셔널 관련 로직을 분리할 수 있도록 노력했습니다.
분리하려다보니 AOP가 왜 필요한지 좀 느낄 수 있었어요...😁
리뷰 잘 부탁 드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 리브(김민주) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 카피😊 3단계 구현하고 왔습니다. 두개의 다른 dao 의 함수가 하나의 커넥션을 사용하게 하기 위해서 Connection 을 인자로 받게 해주었습니다. 사실 이렇게 함으로써 코드가 지저분해져서 개선을 해볼까! 싶기도 했지만😅 4단계 요구사항에 `DAO가 Connection 객체를 파라미터로 전달받아 사용하지 않도록 만들어보자.`가 있어서 3단계는 여기까지 하고 제출합니다.
지난 리뷰에서 질문 주신 부분들 덕분에 저도 더 많이 공부할 수 있었습니다. 감사합니다🙇🏻‍♀️
그럼 이번 리뷰도 잘 부탁드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 산초(나영서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
안녕하세요 비토! 3단계 기능 요구 사항을 구현 완료해서 리뷰 요청합니다! 서비스 로직에 data access 계층이 섞여있는게 불편하지만 .. 다음 단계를 위해 남겨둡니다 😅
> [3단계 - JDBC 라이브러리 구현하기] 미아(이종미) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 명오! 제리입니다
<br>
**리뷰 시 참고사항**
- 4단계에서 리팩터링을 진행할 것 같아 3단계 요구사항을 만족하는 최소한의 코드 변경만을 했습니다.
<br>
편하게 리뷰 남겨주세요 감사합니다 🙇‍♀️🙇‍♀️
<br>
추가로 이전 단계 PR에 남겨주신 코멘트에 대해 답을 작성했습니다.
> NPE가 그냥 발생하는 것과 코드에서 NPE를 명시해주는 것은 어떤 차이가 있을까요?
코드에 명시해주면 명시적 처리가 가능하며 구체적인 메세지를 전달할 수 있어요
객체 생성에 대한 명세인 생성자에서 명시해주는 것은 문서화 측면에서 좋을 것 같아요
> [3단계 - JDBC 라이브러리 구현하기] 제리(김민정) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
>  [3단계 - Transaction 적용하기] 잉크(이예찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/StatementParamSetter.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 감자 🥔
벌써 토요일이라니 마음이 급하네요 ㅎㅅㅎ. .
우선 요구사항 만족을 우선으로 LMS 힌트를 참고해 구현했어요!
다음 단계에서 Connection과 비즈니스로직을 분리하라는 요구사항이 있길래, 4단계에서 리팩토링을 진행하고자 해요.
이번 리뷰에서는 트랜잭션을 중점으로 리뷰해주시면 감사하겠습니다 :>
> [3단계 - JDBC 라이브러리 구현하기] 테니(나아연) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/service/transaction/TransactionConsumer.java
- app/src/main/java/com/techcourse/service/transaction/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/transaction/TransactionFunction.java
- app/src/main/java/com/techcourse/service/transaction/TransactionManager.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- app/src/test/java/com/techcourse/service/transaction/TransactionManagerTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 러쉬 3단계 미션으로 다시 돌아왔습니다 🚀
트랜잭션 적용해서 리팩토링까지 깔끔하게 하고 싶었지만 쉽지 않았네요 🥲
이번 리뷰도 잘 부탁드려요~
> [3단계 - JDBC 라이브러리 구현하기] 제제(장진우) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/service/transaction/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/transaction/TransactionManager.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/exception/JdbcSQLException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 레디 ~! 3단계로 찾아온 켬미입니다 !
이번 미션은 말 그대로 `Transaction 적용하기` 에 초점을 맞춰서 구현만 했습니다 !
커넥션을 주입하는 코드로 변경되니 try-catch 문이 많아져서 코드가 마음에 안드네요..! ㅜㅜ
그래도 어찌저찌 구현은 했습니다 ㅎㅎ 
이번에도 리뷰 잘 부탁드립니다 ~!
> [3단계 - Transaction 적용하기] 켬미(김경미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/InMemoryUserHistoryDao.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/transaction/TransactionManagerTest.java
- study/src/main/java/aop/domain/User.java
- study/src/main/resources/schema.sql
- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
- study/src/test/java/connectionpool/stage0/Stage0Test.java
- study/src/test/java/connectionpool/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/User.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
짱수 안녕하세요.
이번 3단계는 테스트를 통과하는것을 최우선 목표로 세우고 미션을 진행했습니다.
편하게 리뷰 부탁드립니다.
> [3단계 - JDBC 라이브러리 구현하기] 로키(정해성) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/CannotGetJdbcConnectionException.java
- jdbc/src/main/java/com/interface21/jdbc/core/CannotGetPreparedStatementException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcDataAccessException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
안녕하세요 커찬🙇‍♂️
이번 미션, 기능 요구사항을 만족하는데 집중했습니다.
트랜잭션 경계 설정에 어색한 부분이 있다면 말씀해주세요.
감사합니다!
> [3단계 - JDBC 라이브러리 구현하기] 폰드(권규택) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/CannotQueryException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 커비~ 😇
3단계 트랜잭션 진행해봤습니다.
`UserService`에서 호출하는 메서드인 `changePassword` 메서드 내부에서 `UserDao.update`, `UserHistoryDao.log` 메서드를 호출하는데,
각 메서드에서 예외가 발생할 가능성이 있기 때문에 `changePassword` 메서드에서 `Connection` 객체를 생성해서 두 메서드에 넘겨주도록 구현했습니다. 
이렇게 `update`, `log` 메서드는 같은 `Connection` 객체를 대상으로 쿼리를 수행합니다.
두 메서드 중 어느 곳이든 예외가 던져지면, 외부 메서드인 `changePassword` 메서드에서 `rollback`을 합니다.
결국 모두 성공하거나 모두 실패하는 원자성을 갖습니다.
리뷰 잘 부탁드립니다 감사합니다. 😊
> [3단계 - JDBC 라이브러리 구현하기] 이상(이건상) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 켈리~
몸은 좀 괜찮아 졌나요?
3단계 구현을 했는데 리펙토링은 4단계라 코드가 조금 지저분 하네요.
> [3단계 - JDBC 라이브러리 구현하기] 백호(전호건) 미션 제출합니다.

- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage1/UserDao.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 산초~ DB Connection Pool과 Transaction 학습 테스트를 포함하여 2단계 미션 제출합니다~
짚어주신 getNullableSingleResult 부분에 대해,
spring `DataUtils` 구현에서 `singleResult` 와 `nullableSingleResult` 메서드는 엄연히 다른 메서드인데 nullable을 이름에서 빼야하는지 
Jdbc 명세에서 `@Nullable` 키워드로 명시하고 있는 부분을 뺼 필요가 있는지 고민을 해보았어요. 
이번 미션이 JDBC를 이해하기 위한 목적도 있다고 생각해요. 기존 구현을 거의 이해하고 똑같이 구현할 수 없지만 비슷하게 구현하는 것이 그 목적에 가깝다고 생각하여 제 구현대로 가보려고 해요. 그래서 `queryForObject` 메서드 또한 null을 반환할 수 있다는 의미로 `@Nullable`을 추가해주었어요.
> [2단계 - JDBC 라이브러리 구현하기] 마크(김승현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 폴라! 3단계로 돌아왔습니다.
이번에도 리뷰 잘 부탁드립니다 🙇‍♂️
+) `SQLException 발생 시 예외 메시지를 구체적으로 전달`이라는 커밋은 2단계 리뷰 반영 내용인데, 로컬에만 커밋해놓고 push를 안했더라구요😅 이번 단계에 포함해서 push했습니다!
> [3단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 도라! 3단계 적용하면서 많이 지저분한 코드가 되었네요.
connection을 열고 닫는 작업을 모두 service에서 직접 해주고 있어요 😢
4단계에서 리팩터링하라는 의도인 것 같아 이대로 제출합니다!!
> [3단계 - JDBC 라이브러리 구현하기] 트레 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionException.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionCallback.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 폭포 🌊
트랜잭션 적용으로 중복 코드가 많이 생겼는데, 4단계를 구현하다 보면 자연스럽게 제거될 것으로 판단되어서 남겨두었어요
트랜잭션은 `TransactionTemplate`으로 구현했습니다 이번 프로젝트에서 사용한 적이 있어서 크게 어려움은 없었던 것 같아요
DAO와 TransactionTemplate, JdbcTemplate에 존재하는 커넥션 관련 코드는 4단계 때 PlatformTransactionManager, TransactionSynchronizationManager를 구현하면서 책임이 이동할 듯합니다
이번 단계도 잘 부탁드려요 감사합니다 :)
> [JDBC 라이브러리 구현하기 - 3단계] 프린(남기범) 미션 제출합니다 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionException.java
안녕하세요, 시소!
3단계에서는 트랜잭션을 구현해보았는데요,
`UserService`의 `changePassword` 메서드 내부에서는 `UserDao.update`, `UserHistoryDao.log` 메서드를 호출합니다.
userDao와 userHistoryDao를 한 트랜잭션으로 묶으려면 동일한 Connection 객체를 사용하도록 해야해서, `changePassword`에서 Connection을 생성하여 내부에서 호출하는 두 메서드에 전달해주도록 구현해봤어요!
그 과정에서 예외가 발생한다면 rollback을 수행하도록 구현했습니다.
4단계에서 리팩터링을 하기 때문에 우선은 요구사항을 최소한으로 만족시키는 선에서 구현해보았습니다.
리뷰 잘 부탁드립니다~🖐️
> [3단계 - JDBC 라이브러리 구현하기] 리니(이예린) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionManagerTest.java
안녕하세요 낙낙!
이번 단계에서는 얼른 수정해버리고 싶은 코드를 완성했네요 🥲
어디까지를 이번 단계 범위로 잡아야 하나에 대한 고민이 있었는데 
4단계 미션에서 `UserService에서 changePassword() 메서드를 하나의 트랜잭션으로 처리하려면 Connection 객체가 비즈니스 로직과 섞이게 된다.` 라는 요구사항이 있는 것을 보고 
현재 jdbc와 service 코드의 혼재가 잘못된 것이 아니구나... 생각이 들었습니다
추후 리팩토링은 4단계 영역이라 생각하여 이번 단계는 이렇게 마무리하였어요 🤔
오늘 하루도 파이팅입니다 👊
> [3단계 - JDBC 라이브러리 구현하기] 시소(신지송) 미션 제출합니다

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 뽀온드
다시 찾아왔습니다!
트랜잭션 관리라는 측면에서의 기능 구현을 진행해봤는데요.
기존 코드의 범용성을 살려서 진행해보고 싶었는데, 결국에는 오버라이딩으로 구현하게 되었네요..ㅜㅜ
리뷰 잘 부탁드립니다 ^___^
> [3단계 - JDBC 라이브러리 구현하기] 도비(김도엽) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ResultSetMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 안나 🙇‍♂️
3단계는 비교적 코드의 변화가 많이 없었던 것 같네요!
서비스 로직이 너무 더러워지는 것 같아.. 트랜잭션 매니져라는 객체를 통해 분리하는 작업만 구성해 놓았습니다
(2단계 리뷰에 달아주신 부분 중 함수형 인터페이스를 래핑하는 것도 반영해놓았습니다 👍)
이번 리뷰도 잘부탁드립니다 🔥
> [3단계 - JDBC 라이브러리 구현하기] 호티(윤주호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/exception/DataQueryException.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 메이슨~
3단계 미션으로 돌아왔습니다!
이번 미션을 하면서 코드가 상당히 지저분해진 측면이 있네요!
단계 진행하면서 차차 리팩토링 해보죠!
잘부탁드립니다~
> [3단계 - JDBC 라이브러리 구현하기] 카피(김상혁) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
- jdbc/src/test/java/com/interface21/transaction/TransactionManagerTest.java
안녕하세요 프람!
3단계 미션 완료하여 리뷰 요청합니다.
중간에 삽질을 많이 해서 구현이 늦어졌네요 😭
이번 단계에는 요구사항 만족에 초점을 두어서, 변경사항이 많지 않습니다.
이번 단계도 잘 부탁드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 메이슨(김경원) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/utils/SQLExceptionHandler.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 조조~
3단계는 크게 구현할 부분이 없었던 것 같아요! 👀
코드적으로 더 나은, 그러니까 10줄 이내 + 역할 분리 등등에 대한 고민을 조금 더 해보고는 싶었는데요.
4단계를 슬쩍 훔쳐보니 그런 리팩터링을 4단계 때 하게 될 것 같아서용.
우선은 3단계 요구사항인:: `UserServiceTest`의 모든 테스트 메서드가 통과하는 걸 목표로 잡고 구현했습니다.
깨지던 테스트도 수정해두었으니 같이 확인해주시면 될 것 같아요!
감사합니다~~!! ☺️
> [3단계] 애쉬 미션 제출입니다~

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementSetterTest.java
안녕하세요 리니!
3단계 트랜잭션 적용하기 완료하여 리뷰 요청드립니다.
미션에서 changePassword에 대한 내용만 있었지만,
UserService에서 모든 로직에 트랜잭션을 사용하도록 변경해봤습니다.
JdbcTemplate에서도 직접 커넥션을 사용하기도 하고, 받아서 사용할 수도 있도록(현재 미션 상황처럼 직접 커넥션을 관리하는 개발자가 있을 수도 있으니) 변경했습니다.
이번에도 리뷰 잘 부탁드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 테드(김규태) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- docs/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/manager/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/manager/TransactionManagerTest.java
안녕하세요 위브! 
벌써 3단계까지 오게 되었네요! ☺️
좀 이것저것 해볼까 싶다가 4단계 요구사항을 보니 하려던 행위와 비슷해서 3단계는 요구사항만 지켰습니다!
`commit`과 `rollback`만 담당할 객체가 생긴 것이 가장 큰 변화겠네요! 🤔
이번 리뷰도 잘부탁드립니다! 😄
>  [3단계 - JDBC 라이브러리 구현하기] 폴라(장유진) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요~ 제리 😀
프로젝트 일정 때문에 리뷰 요청이 너무 늦어지네요..ㅎㅎ 
이번 단계도 잘 부탁드립니다~~
> [3단계 - JDBC 라이브러리 구현하기] 뽀로로(조경찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/JdbcException.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/mapper/ConstructorRowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/mapper/RowMapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/sql/Sql.java
- jdbc/src/test/java/com/interface21/jdbc/core/mapper/ConstructorRowMapperTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/sql/SqlTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/SecondUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 도비. 오래 기다리게 해드려서 정말 죄송합니다. 이대로면 너무 늦을거 같아서 할수 있는 만큼 2단계 수행해서 제출합니다.
부족한 부분이 많아 리뷰가 두렵지만 지적해주시는 부분 최대한 수용하도록 노력하겠습니다. 감사합니다.
리플렉션 부분은 해결법을 찾을 수 없어서 우선 말씀해주신 피드백처럼 함수형 인터페이스로 분리해보았습니다..!
리뷰 잘 부탁 드리겠습니다.
> [2단계 - JDBC 라이브러리 구현하기] 켈리(양성욱) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
안녕하세요 카키!
3단계를 진행하다보니 각 객체의 역할이 불분명해진단 느낌이 들었습니다.
불편함을 느끼는 부분은 4단계에서 해소되는 거 같네요,,
우선은 요구사항을 충족하는 방향으로 눈 딱 감고 구현했습니다.
> [3단계 - JDBC 라이브러리 구현하기] 도라(추서연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/application.yml
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
안녕하세요 타칸.
금세 돌아온 커비입니다.
학습 테스트 + 2단계 때 남겨주신 코멘트까지 야무지게 반영해서 돌아왔습니다.
리뷰 가봅시다!
> [3단계 - JDBC 라이브러리 구현하기] 커비(이현지) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/TransactionException.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
제제 안녕하세요! 아토입니닷
일단 요구사항은 만족하게 구현해봤습니다...!!!
그래서 변경사항이 많지는 않네요... ㅎㅎ
편하게 확인하시고 리뷰 남겨주세요.
미리 감사합니닷
> [JDBC 라이브러리 구현하기 - 3단계] 아토(이혜린) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/domain/UserHistory.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/OrderedSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 이든~ 또 뵙네요 하하
>  추후 확장성을 생각해서 FunctionalInterface 정도로 분리해주는 건 괜찮은 선택이라고 생각해서 반영하였습니다.
라이브러리를 제공해 주는 입장에서는 확장성에 대해 조금 더 열어 두는 것이 좋을 것 같다는 생각이 들었어요. 
그래서 이번 단계에서 `PreparedStatementSetter` 를 분리해 보았습니다!
이번 단계도 잘 부탁드려요~
> [3단계 - Transaction 적용하기] 짱수(장혁수) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/resources/truncate.sql
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
테드 안녕하세요! 또또또 돌아온 땡이 입니다. 🥸
트랜잭션 적용이 기존 코드에 끼지는 영향을 최소화 하기 위해 Connection 객체를 인자로 받는 메서드를 새로 생성해주었습니다. 커넥션을 다루는 코드가 비즈니스 레이어에 있는게 찜찜하지만, 일단 최대한 깔끔하게 짜보려 했습니다.
propagation 학습 테스트에도 학습한 내용 정리해두었으니 함께 확인 부탁드릴게요!
이번 단계도 잘 부탁드립니다!
> [3단계 - Transaction 적용하기] 땡이(정지호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/CheckedExceptionExecutor.java
- app/src/main/java/com/techcourse/support/SQLExceptionConsumer.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 뽀로로 😄 포케입니다.
이번 3단계 미션에는 이전 코드를 유지한 채 변경을 최소화 하여 트렌젝션을 적용하는 것을 목표로 했습니다~
이번 단계에서도 잘 부탁드려요 👋
> [3단계 - JDBC 라이브러리 구현하기] 포케(이무송) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
- jdbc/src/test/java/com/interface21/jdbc/core/RowMapperTest.java
> [Step2] 테바(김성겸) JDBC 구현하기 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/TransactionExecutor.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/TransactionExecutorTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- study/src/main/resources/schema.sql
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
- study/src/test/java/transaction/stage2/User.java
릴리 안녕하세요 ~
트랜잭션 학습테스트 & 3단계 기능 구현 완료하여 제출드려요.
요구사항대로 구현하려면 파라미터에 Connection을 추가해줘야 했는데요, 기존 코드를 날릴까 고민하다가 Dao, JdbcTemplate에서는 Connection을 받는 메서드를 하나 더 오버로딩 하는 방식으로 구현했어요~
감사합니다😄
> [3단계 - Transaction 적용하기] 상돌(이상진) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
안녕하세요 애쉬 ~ 안나입니다
빠른 리뷰 감사드려요!
이번 미션에서는 TransactionManager가 공동 Connection 객체를 가지고 트랜잭션 시작 및 커밋 / 롤백 처리를 담당하는 것으로 구현하였습니다.
이 경우 Connection이 Dao, JdbcTemplate 메서드들의 파라미터로 공유되어야 합니다. 다음 단계에서 이 문제를 해결하기 위한 방법을 고민해보겠습니다! 😄
+) 학습 테스트의 경우 4단계 미션에서 함께 제출할게요. 
리뷰 잘 부탁드립니다 😄
> [3단계 - Jdbc 라이브러리 구현하기] 안나(김민겸) 미션 제출합니다 🧐

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 테바!
마감기한이 얼마 안남아 최소한의 기능 구현에만 집중했습니다,,!
잘부탁드립니다!
> [3단계 - JDBC 라이브러리 구현하기] 호기(조호연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
안녕하세요 프람!
4단계 미션 완료하여 리뷰 요청합니다.
학습 테스트도 진행해서 추가로 올리도록 하겠습니다.
어느덧 마지막 미션의 마지막 단계네요. 이번 단계도 잘 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 메이슨(김경원) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 무빈! 구름 ⛅️입니다.
이번에는 `step4`와 `AOP와 Spring AOP 학습테스트`를 진행했습니다.
step4 구현에서는 proxy를 이용하는 것이 아닌 인터페이스를 활용하여 트랜잭션 서비스를 추상화하는 것이어서 그 수준까지만 구현하였습니다.
또한 `생각해보기`의 PlatformTransactionManager를 구현할려다가 너무 커지는 것 같아서 제외하고 제출합니다.
> JDBC가 아닌 JPA, JMS 같이 다른 커넥션을 사용하거나 2개 이상의 데이터소스를 하나의 트랜잭션처럼 관리하려면 어떻게 해야 할까?
PlatformTransactionManager는 트랜잭션 관리의 인터페이스입니다. commit, rollback과 같은 메서드가 정의되어 있습니다. 
구현체로 DataSourceTransactionManager, JpaTransactionManager, JtaTransactionManager 등이 있습니다.
- 로컬 트랜잭션은 단일 데이터베이스에 대한 트랜잭션이고, DataSourceTransactionManager 구현체를 통해 관리됩니다. 
- 글로벌 트랜잭션은  여러 데이터 소스나 여러 리소스를 포함하여 하나의 트랜잭션을 구성하는 것입니다. 이는 분산 트랜잭션이라고도 합니다. JtaTransactionManager 구현체를 통해 관리됩니다. 
- JTA는 분산 트랜잭션을 관리하기 위한 Java의 표준 API입니다. 여러 데이터 소스와 JMS, 다른 리소스를 아우르는 트랜잭션을 관리할 수 있습니다.
제가 구현한 TransactionTemplate은 Connection을 통해 …
> [4단계 - JDBC 라이브러리 구현하기] 구름(김민수) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/com/interface21/transaction/util/SQLExceptionUtil.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/SqlExecutorTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/aop/stage2/Stage2Test.java
미아 안녕하세요~~ 냥인입니다. 😼
4단계 요구사항 만족 뒤 제출합니다.
학습 테스트는 아직 못해서 조오금 천천히 올려두…될까요….?🥺
이번에도 리뷰 잘 부탁드리고 이따 봅시다. ㅎ.ㅎ
> [4단계 - Transaction synchronization 적용하기] 냥인(최가희) 미션 제출합니다. 

- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/datasource/DataSourceUtilsTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 비토! 이번 미션은 추상화 덕에 편하게 쓰던 트랜잭션 동기화를 구현해야 해서 좀 머리 아팠네요 .. 🤯
다른 건 요구사항과 동일한데
기존 트랜잭션을 사용하지 않던 서비스 메소드들도 정상적으로 동작하게 하기 위해서 SqlExecutor에서 트랜잭션이 존재하는 경우와 존재하지 않는 경우를 나눠서 구현했습니다 :) 트랜잭션이 존재하지 않는 경우에서 DatasourceUtil에서 Connection을 가져다 쓰면 null 값이 반환될 테니까요 ! 
이번 미션도 잘 부탁드려요 ☺️
> [4단계 - JDBC 라이브러리 구현하기] 미아(이종미) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/JdbcTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/PlatformTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionCallback.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionHolder.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/com/interface21/jdbc/datasource/JdbcTransactionManagerTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 폭포~ 마지막 단계, 마지막 미션이군요 시간 참 빠르네요 :)
학습테스트는 아직 못했는데 곧 커밋 올릴게요!
마지막까지 잘 부탁드립니다 감사합니다
_2024.10.15 추가_
지난번 오프라인으로 요청해주신 내용은 코드 라인마다 하나하나 설명을 달려고 했는데 생각보다 오래 걸리더라구요
제가 학습하면서 정리했던 [노션 링크](https://given53.notion.site/PlatformTransactionMananger-11ece343914380d997b8d587da70a11e?pvs=4)를 남겨놓겠습니다 읽으면서 궁금하신 부분은 dm이나 오프라인으로 편하게 요청해주세요!
> 링크 만료기간은 10월 22일 15시까지입니다
> [JDBC 라이브러리 구현하기 - 4단계] 프린(남기범) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 망쵸!
이번에는 트랜잭션을 추상화해보았습니다!
프록시를 사용하는 미션일 줄 알았는데 요구사항만 봐서는 프록시를 사용하지 않더라고요!
그래서 간단하게 구현해보았습니다!
트랜잭션을 직접 하려니까 헷갈리는 부분이 많아서 조금 어려웠네요..
이번에도 잘 부탁드려요!
> [4단계 - JDBC 라이브러리 구현하기] 타칸(최원준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- jdbc/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 감자 ~ 🥔
감자의 빠른 리뷰 덕에 마감기한 지킬 수 있었습니다 👍
마지막 리뷰도 잘 부탁드립니다 !! ㅎㅎ
> [4단계 - JDBC 라이브러리 구현하기] 테니(나아연) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/jdbc/exception/ExceptionExecutor.java
- app/src/main/java/com/techcourse/support/jdbc/exception/RunnableWithException.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/aop/stage2/Stage2Test.java
안녕하세요 🚢🗝️!
우테코의 리뷰형 미션을 이렇게 막을 내리는 군요...!
그동안 리뷰 받으며 저도 많이 생각하고 성장 하게 되었어요!
이번 미션을 하며 진행했던 것을 아래와 같습니다!
1. `java-aop` 에서 `AOP 개념` `Proxy vs proxy & decorator pattern` `JDK Proxy` `CGLIB` `Spring AOP` `AspectJ` 에 대해 학습
2. 본 미션 `Transaction synchronization` 을 적용하며 트랜잭션을 거는 관점을 비지니스 영역에서 분리 학습
3. `java-jdbc > study > aop` 에서 `Proxy with Interface or Class` `Advice, Advisor, Pointcut` `DefaultAdvisorAutoProxyCreator` 용어 및 개념 학습
<br>
그럼 시간나실 때 마지막 리뷰 부탁드릴게요!
감사합니다~ 🤗
> [4단계 - JDBC 라이브러리 구현하기] 새양(양경호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 커비!
4단계 미션으로 Transaction synchronization 적용하고 트랜잭션 서비스를 추상화하여 UserService 인터페이스를 만들고 TxUserService, AppUserService 클래스를 생성하고 구현해서 트랜잭션 처리와 비즈니스 로직을 분리했습니다. 그래서 TxUserService에서 트랜잭션 처리를 하면서 AppUserService를 의존관계로 가지고 사용하도록 변경했습니다.
또한 AOP 학습 테스트도 함께 추가했습니다!
리뷰 잘 부탁드립니다. 감사합니다~~ 😇
>  [4단계 - JDBC 라이브러리 구현하기 이상(이건상) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/SQLFunction.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 포케~ 
벌써 4단계네요 🤗 
리뷰 잘 부탁드립니다!
감사합니다 :)
> [4단계 - JDBC 라이브러리 구현하기] 릴리(최윤서) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
잉크 안녕하세요!
드디어 마지막 단계입니다.
- 서비스 추상화
- Transaction Synchronization 적용
LMS 에서 제시한 미션 요구사항을 만족하는 걸 목표로 미션 진행했습니다!
트랜잭션 관련한 부분이라 테스트 짜는게 너무 어렵더군요 ㅠㅠ
따로 구현하진 못했습니다,,,
마지막까지 리뷰 잘 부탁드립니다!
잉크도 화이팅이에요!!
> [4단계 - Transaction synchronization 적용하기] 무빈(김현중) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 호기~!
드디어 마지막 단계네요!
이번 단계도 잘 부탁드립니다 😁
> [4단계 - JDBC 라이브러리 구현하기] 몰리(김지민) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManger.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 재즈! 
배키입니다~~
급하게 제출하니, 부족한 점이 많을 것 같아요🥲
편하게 리뷰 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 배키(백은희) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/ServiceLogic.java
- app/src/main/java/com/techcourse/service/TransactionTemplate.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/ConnectionConsumer.java
- jdbc/src/main/java/com/interface21/jdbc/core/ConnectionConsumerWrapper.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/ServiceLogic.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/ServiceLogic.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
> [4단계 - JDBC 라이브러리 구현하기] 위브(김기범) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 로빈!! 레모네 입니다!
학습테스트를 아직 하지 못해서, 기능에 대한 피드백을 먼저 주시면 감사하겠습니다.
학습테스트는 다음 리뷰 요청때 꼭 반영하겠습니다!
마지막 4단계도 잘 부탁드립니다 🙇‍♀️
> [4단계 - JDBC 라이브러리 구현하기] 레모네(이지현) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/LogicExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/transaction/stage1/Stage1Test.java
안녕하세요 안나! 🙇‍♂️
벌써 마지막 미션이네요 🥲
저번 리뷰에서 언급해주신 학습테스트도 추가해놓았습니다.
이번에도 잘부탁드립니다!! 🔥
> [4단계 - JDBC 라이브러리 구현하기] 호티(윤주호) 미션 제출합니다.

- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/service/UserServiceImpl.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
안녕하세요 리건!
제가 어쩌다보니 요구사항을 STEP3에서 처리하게 되었는데요..
그러다보니 큰 변경사항이 없던 것 같습니다.
학습 테스트만 빠르게 처리해서 올리겠습니닷..!!
- 2보다 큰 Indent를 가진 로직을 별도의 메서드로 분리
- UserService를 Interface로 분리 후 TxUserService 구현
> [STEP4 - JDBC 미션] 이든(최승준) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 구름. 어느덧 마지막 미션의 마지막 단계네요.
시간이 벌써 이렇게 흘렀구나 싶습니다.
이번 리뷰도 잘 부탁드려요.
> [jdbc 구현하기 4단계] 초롱 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/jdbc/support/h2/H2SQLExceptionTranslator.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransaction.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/JdbcTransactionTemplate.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
조이썬 안녕하세요. 아톰입니다.
이번에는 TransactionSynchronizationManager를 사용해 커넥션 동기화를 구현했어요.
이전 단계에서 남겨주신 질문은 이전 PR에 답변 남겨놓았어요. 
이번에도 리뷰 잘 부탁 드립니다. 감사합니다. 🙇🏻‍♂️
> [4단계 - JDBC 라이브러리 구현하기] 아톰(이하늘) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 켈리~
4단계 트랜젝션 인터페이스 분리와 AOP 학습테스트 진행했습니다.
감사합니다.
> [4단계 - JDBC 라이브러리 구현하기] 백호(전호건) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 엑스칼리버 ⚔️ 
이번 미션을 통해 드디어 서비스 계층에서 커넥션을 dao로 넣어주지 않도록 바뀌게 되었네요! 휴~
마지막 미션의 마지막 단계 리뷰도 잘 부탁드립니다!!!
> [4단계 - JDBC 라이브러리 구현하기] 알파카(최휘용) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTransactionTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
페드로 페드로 페드로~
이번 미션에서 성공적으로 서비스에서 트랜잭션을 덜어냈어요. 기존에 Connection을 최대한 활용하지 않도록 구현해서 편하게 옮겨 왔습니다. 몇 가지 의문이 있긴 한데.. 이건 코멘트로 달아둘게요
마지막 미션의 마지막 리뷰 귀하다... 고생했습니다 우리
> [🔥 JDBC 라이브러리 구현하기 - 4단계] 아루(이동훈) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요, 알파카! 🦙
이번 4단계에서 드디어 Connection이 여러 계층에 침투된 코드를 벗어나
추상화를 적극 활용해 깔끔해진 코드로 변모했습니다.
얼마 남지 않은 미션, 알파카도 파이팅입니다!
리뷰 잘 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 리건(이한길) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/TransactionConnection.java
- jdbc/src/main/java/com/interface21/transaction/service/TransactionService.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/transaction/service/TransactionServiceTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
테드 안녕하세요! 4단계 진행 후 리뷰 요청 드립니다!
1. ThreadLocal을 사용해 같은 트랜잭션 내부에서 커넥션 객체를 공유할 수 있도록 했습니다. 이에 따라 각각의 dao는 커넥션 객체를 인자로 넘겨받지 않도록 수정했습니다.
2. TransactionService를 분리해 비즈니스 로직과 커넥션 관련 로직을 분리했습니다.
바쁜 와중에 감사합니다. 이번 단계도 잘 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 땡이(정지호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/resources/schema.sql
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/TxUserServiceTest.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하십니까 타칸.
드디어 귀사와의 마지막 과제를 제출하게 되었습니다.
충분히 고려하고 피드백 후 머지 결정 내려주시기 바랍니다.
감사합니다.
> [4단계 - JDBC 라이브러리 구현하기] 커비(이현지) 미션 제출합니다. 

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/service/transaction/TransactionManager.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 러쉬 ~ 🏈
4단계는 급하게 구현하느라 일단 요구사항을 만족하는 걸 1차 목표로 했어요.
놓친 부분도 많을 것 같아 리뷰반영하면서 차근차근 리팩토링해보려고 합니다 ㅎㅎ
리뷰 편하게 해주세요 마지막단계까지 잘 부탁드려요 💪
> [4단계 - JDBC 라이브러리 구현하기] 제제(장진우) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/JdbcTransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/aop/stage2/Stage2Test.java
안녕하세요 땡이!
벌써 마지막 미션이네요!
끝까지 잘 부탁드립니다 😄
> [4단계 - JDBC 라이브러리 구현하기] 초코칩(권기호) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/datasource/DataSourceUtilsTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/aop/stage2/Stage2Test.java
안녕하세요 리니~
미션 마지막 단계 진행하여 리뷰 요청 드립니다😊
Connection 객체를 비즈니스 로직과 분리하기 위해 TransactionManager를 사용했습니다.
TransactionManager를 통해 모든 비즈니스 로직이 자동으로 트랜잭션이 관리되고, TransactionSynchronizationManager를 통해 스레드 간 동일한 커넥션을 사용할 수 있도록 구현했습니다.
이번에도 리뷰 잘 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 테드(김규태) 미션 제출합니다.

- app/src/main/java/com/techcourse/config/DataSourceConfig.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/main/java/com/techcourse/support/TransactionExecutor.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요, 호티! 클롱바입니다~
마지막 미션 제출이네요!
미션 진행하면서 생긴 고민점이 한 개 생겼는데 호티의 의견이 궁금해요!
`TxUserService`가 가지고 있는 `executeInTransaction`은 트랜잭션을 처리하는 별도의 객체를 만들어 위임하는게 나을까요? 
다른 TxXXXService에서도 사용하게 될 로직인데 너무 `TxUserService`에 종속된 것 같은 느낌이 들었어요. 
하지만 지금은 `TxUserService`외에 사용하는 곳이 없어 일단은 한 곳에 넣어두었습니다.
마지막 단계도 잘 부탁드립니다~ 🙇
> [4단계 - JDBC 라이브러리 구현하기] 클로버(이은정) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/TransactionTemplate.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/main/java/aop/service/TxUserService.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage1/UserServiceProxy.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/aop/stage2/Stage2Test.java
안녕하세요 카피😊
이번 단계의 미션도 구현하고 왔습니다.
지난 단계들에서 카피가 해주신 리뷰나 질문으로 많이 배울 수 있었어요.
감사합니다😇
그럼 이번 리뷰도 잘 부탁드립니다!
> [4단계 - JDBC 라이브러리 구현하기] 산초(나영서) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionException.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
제제 안녕하세요! 아토입니다~~~
빠르게 마지막 단계 구현 해보았습니다.
DM으로 말씀드린대로 이 부분 리뷰를 먼저 마무리하고,
aop 학습테스트 후에 프로덕션 코드 적용까지 진행해볼까 해요!
현재 구현사항 관련해 제안 혹은 질문들 편하게 남겨주세요!
> [JDBC 라이브러리 구현하기 - 4단계] 아토(이혜린) 미션 제출합니다.

- README.md
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 명오! 제리입니다
편하게 리뷰 남겨주세요 감사합니다 🙇‍♀️🙇‍♀️
> [4단계 - JDBC 라이브러리 구현하기] 제리(김민정) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionTemplate.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 산초~ 
DataSourceUtils와 TransactionSynchronizationManager를 활용하여 DAO가 Connection 객체를 파라미터로 전달받아 사용하지 않도록 만들어봤어요. 이전 단계에서 구현했던 TransactionTemplate를 활용하여 트랜잭션 서비스를 구현해봤습니다.
잘 부탁드려요!
> [4단계 - JDBC 라이브러리 구현하기] 마크(김승현) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
- study/src/test/java/transaction/stage1/Stage1Test.java
- study/src/test/java/transaction/stage2/FirstUserService.java
- study/src/test/java/transaction/stage2/Stage2Test.java
안녕하세요 제리~ 
어느덧 마지막 단계 리뷰 요청이네요~ 🤣
제리 리뷰 덕 많은 도움을 받을 수 있었습니다~
이번에도 잘 부탁드려요! 👍
> [4단계 - JDBC 라이브러리 구현하기] 뽀로로(조경찬) 미션 제출합니다.

- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TxUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- docs/README.md
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
- jdbc/src/test/java/com/interface21/jdbc/core/TransactionManagerTest.java
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 초코칩! 
테스트가 금쪽이네요... 빠르게 보완하겠습니다...!
> [4단계 - Transaction synchronization 적용하기] 레디(최동근) 미션 제출합니다.

- app/src/main/java/com/techcourse/controller/LoginController.java
- app/src/main/java/com/techcourse/controller/RegisterController.java
- app/src/main/java/com/techcourse/controller/UserController.java
- app/src/main/java/com/techcourse/dao/UserDao.java
- app/src/main/java/com/techcourse/dao/UserHistoryDao.java
- app/src/main/java/com/techcourse/service/AppUserService.java
- app/src/main/java/com/techcourse/service/TransactionalUserService.java
- app/src/main/java/com/techcourse/service/UserService.java
- app/src/test/java/com/techcourse/dao/UserDaoTest.java
- app/src/test/java/com/techcourse/service/AppUserServiceTest.java
- app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
- app/src/test/java/com/techcourse/service/UserServiceTest.java
- jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
- jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
- jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
- jdbc/src/test/java/com/interface21/jdbc/datasource/DataSourceUtilsTest.java
- jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
- study/src/main/resources/schema.sql
- study/src/test/java/aop/stage0/Stage0Test.java
- study/src/test/java/aop/stage0/TransactionHandler.java
- study/src/test/java/aop/stage1/Stage1Test.java
- study/src/test/java/aop/stage1/TransactionAdvice.java
- study/src/test/java/aop/stage1/TransactionAdvisor.java
- study/src/test/java/aop/stage1/TransactionPointcut.java
- study/src/test/java/aop/stage2/AopConfig.java
안녕하세요 도라! `Connection`을 어디서 닫아야할지 고민이 많이 되었던 미션이에요.
현재 방식은 아래와 같은데, 어색하거나 복잡하지 않은지 궁금합니다. 잘 부탁해요!
(1) 트랜잭션이 적용되지 않은 경우
`JdbcTemplate`이 알아서 닫아준다.
(2) 트랜잭션이 적용된 경우
`TxService`에서 개발자가 직접 닫아야 한다.
**IntelliJ가 아닌 Gradle로 빌드해주세요!**
> [4단계 - JDBC 라이브러리 구현하기] 트레 미션 제출합니다.

- study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
학습테스트에 존재하던 Poling -> Pooling으로 오타 수정하였습니다.
> Poling 오타 수정
