woowacourse/java-jdbc

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/build.gradle
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/RowMapper.java
jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
jdbc/src/main/java/nextstep/jdbc/exception/EmptyResultDataException.java
jdbc/src/main/java/nextstep/jdbc/exception/IncorrectResultSizeDataAccessException.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 잘부탁드립니다!
예전에 토비의 스프링 스터디를 진행하면서 비슷한 내용을 학습한 경험이 있는데, 덕분에 조금 수월하게 구현할 수 있었습니다.
---
구현하면서 궁금점이 생겼는데요. 
```
@Override
@Nullable
public <T> T queryForObject(String sql, RowMapper<T> rowMapper) throws DataAccessException {
List<T> results = query(sql, rowMapper);
return DataAccessUtils.nullableSingleResult(results);
}
```
실제 JdbcTemplate의 경우 단건 조회할 때에도 내부적으로 리스트 조회 메서드를 실행한 다음, 해당 컬렉션의 크기를 비교해서 실제 결과가 단건만 존재하는지 검사합니다.
제 개인적인 생각으로는 코드는 깔끔하게 줄어들 수 있어도, 약간(?)은 비효율적인 방식이라고 생각되는데요.
예를 들어, 데이터 조회 결과가 1만건이라면 반복문을 순회하면서 mapRow로 1만개의 인스턴스를 만들고나서야 단건인지 검사하게 될텐데요.
불필요한 객체 생성 및 반복문 순회 필요 없이 2번만 ``next``를 호출하여 단건 조회인지 검증하도록 코드를 작성했습니다.
코기의 생각은 어떤지 궁금합니다~

[JDBC 라이브러리 구현하기 - 1, 2단계] 케빈(박진홍) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/ManualHandlerMapping.java
app/src/main/java/com/techcourse/config/DataSourceConfig.java
app/src/main/java/com/techcourse/controller/LoginController.java
app/src/main/java/com/techcourse/controller/RegisterController.java
app/src/main/java/com/techcourse/controller/UserController.java
app/src/main/java/com/techcourse/controller/UserSession.java
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
app/src/main/java/com/techcourse/support/context/ContextLoaderListener.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/build.gradle
jdbc/src/main/java/nextstep/jdbc/JdbcExecutionException.java
jdbc/src/main/java/nextstep/jdbc/JdbcPreparedStatementExecution.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/RowMapper.java
jdbc/src/main/java/nextstep/jdbc/exception/JdbcException.java
jdbc/src/main/java/nextstep/jdbc/exception/JdbcExecutionException.java
jdbc/src/test/java/nextstep/jdbc/DataSourceConfig.java
jdbc/src/test/java/nextstep/jdbc/DatabasePopulatorUtils.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/jdbc/User.java
jdbc/src/test/resources/logback.xml
jdbc/src/test/resources/schema.sql
learning/src/test/java/servlet/ServletTest.java
mvc/src/main/java/nextstep/mvc/HandlerAdapter.java
mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java
mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
mvc/src/main/java/nextstep/mvc/view/util/ViewRedirectHelper.java

안녕하세요 검프, 연휴는 잘 보내셨나요 ㅎㅎ 이번주도 화이팅입니다~!  
너무 구현한게 적은 느낌이라 이대로 제출해도 되나 싶은데... 리뷰 일단 요청하겠습니다!!  
콜백은 2개 추가했습니다! 템플릿 메서드 패턴은 JdbcTemplate의 execute 메서드로 사용했습니다.  
네이밍은 실제 JdbcTemplate의 네이밍 참고를 좀 했습니다!!  
리뷰 감사합니다. 검프!!

[JDBC 라이브러리 구현하기 - 1, 2단계] 파즈(강승윤) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/RowMapper.java
jdbc/src/main/java/nextstep/jdbc/ThrowingFunction.java

안녕하세요, 리차드 🙌
로또 미션 때 페어로 만난게 벌써 반년이 훌쩍 넘어갔네요. 시간 참 빨라요 😨
이번 미션을 진행하면서, 중복 코드가 많이 발생하더라구요.
예전 체스미션때 중복코드를 템플릿 메서드 패턴을 통해 해결해본적 있었는데, 이번엔 람다를 사용해서 한번 개선해보았습니다.
그런데, 아직 `ResultSet` 에서 `getXXX()` 를 해오거나, `preparedStatement.executeUpdate()` 같은것을 실행할 때 람다식 내부에서 `SQLException` 을 try - catch 해줘야 하는 것은 해결하지 못했어요. 아직 감이 잡히지 않네요!
아무튼 1단계 리뷰 잘 부탁드립니다!

[JDBC 라이브러리 구현하기 - 1단계] 후디(조동현) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/resources/clear.sql
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java

안녕하세요 아스피!
2단계 미션 제출합니다ㅎㅎ
지난번 피드백이 고민해볼 문제들이어서 좋았어요
이번에도 좋은 피드백 기대하겠습니다! 😄
지난번 피드백 중 [예외 메시지에 쿼리문 전달](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/114#discussion_r987522797) 이 있었는데요, 결론은 쿼리문을 삭제했습니다ㅠ.ㅠ
저는 사용자가 요청한 (데이터가 담긴) 쿼리문을 보여주어 빠르게 문제를 인식하도록 했었는데 제가 추가한 쿼리문은 파라미터가 셋팅되지 않은 쿼리문이더라구요. 아스피가 말해주어서 그때 알았습니다 😢 원래의 목적대로 파라미터가 셋팅된 쿼리문을 전달하기에는 편의성을 위해 추가하는 과정 때문에 코드 내부 로직이 복잡해지고, 로그로도 남기기 때문에 불필요하다고 느꼈습니다. 
- JdbcTemplate 템플릿 메서드 패턴 적용
- UserHistoryDao 에서 JdbcTemplate 사용
- UserService 테스트 추가

[JDBC 라이브러리 구현하기 - 2단계] 유콩(김유빈) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/domain/User.java
jdbc/src/main/java/nextstep/jdbc/BeanPropertyRowMapper.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/QueryExecutor.java
jdbc/src/main/java/nextstep/jdbc/support/DataAccessUtils.java
jdbc/src/test/java/nextstep/jdbc/BeanPropertyRowMapperTest.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 열음 :) 2단계 미션으로 돌아왔습니다.
제 나름대로의 생각으로는 2단계 힌트중에 1단계 미션에서 이미 구현된 부분이 꽤 많다고 느꼈습니다. 반영되지 않은 부분이라면 템플릿 메서드 패턴 적용 정도였는데요, try ~ catchd에서 커넥션을 만들고 PreparedStatement를 만들고, 쿼리를 실행하는 부분들이 공통 로직이기 때문에 이 부분을 콜백 메서드를 만들어서 중복 제거가 되도록 만들었습니다.
그리고 기존에는 query와 queryForObject가 굉장이 애매하게 중복된 부분이 있었는데요, 이는 queryForObject도 바로 ResultSet을 가져와서 사용하기 때문이었는데, query의 결과로 나온 리스트를 가지고 데이터 개수를 판단하도록 로직을 변경했습니다. 굳이 객체로 만들 필요 없는 객체까지 만들 필요가 있냐는 의견도 있을 수 있지만, 개인적인 의견으로는 어차피 데이터베이스에서 row를 읽어오는 시간이 더 걸리지, 이미 읽어온 ResultSet을 객체로 매핑하는 부분은 크게 시간이 걸리지 않는다고 판단, query의 결과를 사용하더라도 성능상 큰 차이가 없을거라는 판단을 했습니다.
지난 1단계에서 코멘트 주셨던 cleanup의 경우, 테이블 네임을 가져와서 각각의 테이블에 대해 클린업을 해주는 부분의 문법이 각 벤더사마다 다 달라서 모든 DBMS에 대해 작동하는 cleanup을 만드는데 어려움이 있어 기존의 truncate.sql을 사용하는 방법을 유지했습니다.
마지막으로 2단계 뭐 더 할게 없을까 하다가... ORM처럼 자동으로 매핑해주는 …

[JDBC 라이브러리 구현하기 - 2단계] 오찌(오지훈) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/resources/schema.sql
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplateUtils.java
jdbc/src/main/java/nextstep/jdbc/ResultExtractor.java
jdbc/src/main/java/nextstep/jdbc/StatementCallback.java
jdbc/src/main/java/nextstep/jdbc/StatementSetter.java
jdbc/src/test/java/nextstep/jdbc/Fixture.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/jdbc/ResultExtractorTest.java
jdbc/src/test/java/nextstep/jdbc/StatementSetterTest.java
jdbc/src/test/java/nextstep/jdbc/User.java

안녕하세요! 엘리 🙌 
```
R(Request Change): 꼭 반영해주시면 좋을 것 같아요!
C(Comment): 제 사소한 의견이랍니다:)
A(Approve): 짱짱! 저도 동의합니다!
```
오 이거 뭐죠?! 처음 당해보는 리뷰 방식인데 정말 좋은 방법 같네요!!  
(우테코 초반에 리뷰어님이 ~~는 어떨까요?, 왜 이렇게 구현하셨나요? 이렇게 코멘트 남기면 머리 쥐어뜯으면서 바로 코드 고쳤는데 저렇게 받았다면 지금 제 머리숱이 좀 더 남아있지 않았을까 라는 생각이 드네요)
1단계에서 꼼꼼하게 리뷰해주셔서 정말 감사합니다👍
2단계에서는 실제 JdbcTemplate 에서 사용되는 템플릿 콜백 패턴을 적용해봤어요.
기존에 비슷한 흐름을 가진 로직을 하나의 템플릿 메서드로 선언하고 서로 다른 부분들은 콜백함수로 구현해서 중복을 줄였어요.  
그리고 PreparedStatement 설정, ResultSet 순회, 엔티티 반환하는 각각의 로직들을 클래스 단위로 분리해봤습니다!!  
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/111#pullrequestreview-1130160663
이 부분에 대해서 제가 표현을 잘 못 한 것 같네요😅 checked exception 을 throws 하는 경우에 해당 메서드와 checked exception 이 결합돼서 checked exception 을 사용하면 OCP를 위반할 여지가 있다. 라는 의미였습니다..

[JDBC 라이브러리 구현하기 - 2단계] 칙촉(안영윤) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java

안녕하세요, 리차드 🎶 뭔가 오랜만에 리뷰 요청 드리는 것 같네요 😅
2단계 힌트를 보니 이미 1단계에서 미션 의도대로 설계가 된 것 같아서 지난번 말씀드린 것 처럼 3단계까지 함께 리뷰 요청 드려요.
(혹시 2단계 리팩토링 부분에서 제가 놓친게 있다면 리뷰 부탁드립니다 ㅎㅎ;)
3단계는 스프링이 트랜잭션 동기화와 추상화를 어떻게 하고 있는지 이해가 필요해서 조금 오래걸렸던 것 같아요.
관련하여 공부를 좀 했는데 https://hudi.blog/spring-transaction-synchronization-and-abstraction/ 에 정리해두었으니 참고하면 좋을 것 같아요.
이번 리뷰도 잘 부탁드립니다 👋

[JDBC 라이브러리 구현하기 - 2, 3단계] 후디(조동현) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 베베
1단계에서는 기능 동작에 우선을 두고 작업을 했습니다. 
2단계에서 코드의 중복이나 이러한 부분들을 제거하도록 하겠습니다
감사합니다.

[ JDBC 1단계 ] 박스터 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

존경하옵는 에밀 선생님께,
안녕하십니까?
저희가 함께하였던 레벨1 방학이
어느덧 179일이 지나간 것을 깨닫게 되었습니다.
시간이 참 빠르게 지나가는 것 같아 마음이 헛헛합니다.
솔직히 말씀드리면, 
선생님께 저의 진전된 모습을 제대로 보여드리고자 하는 마음은 크나, 
아직도 부족한 실력에 대한 걱정이 앞섭니다.
부족한 모습마저 사랑으로 감싸주시길 간청드립니다.
현재의 작업 순서는 다음과 같습니다:
- UserDao 내부의 모든 메서드의 구현
- DAO 내에서의 update 메서드 분리
- queryForObject 메서드의 분리
- query 메서드의 분리
- 분리한 메서드들을 JdbcTemplate으로 이전 
- 아뢰옵기 황송하오나, 커밋 이름에는 약간의 착오가 있음을 양해 부탁드립니다...
- JdbcTemplate에 대한 테스트 케이스 추가
추후에는 DB ConnectionPool에 대한 학습 테스트도 추가할 예정입니다.
존경하는 에밀 선생님의 세심한 지도와 가르침을 바라며, 
계속해서 저에게 힘과 도움을 주시기를 희망합니다.
감사의 말씀을 전하며, 아름다운 하루 되시길 바랍니다.

[JDBC 라이브러리 구현하기 - 1,2단계] 준팍(박준현) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 밀리~
기능이 동작되게 JdbcTemplate을 구현해봤습니다.
현재 중복 코드가 조금 있는데, 2단계 리팩토링 진행하면서 리팩토링 하겠습니다.
잘 부탁드립니다 :)

[1단계 - JDBC 라이브러리 구현하기] 제이(이재윤) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 이오
step2가 리팩터링이여서 기능 돌아갈정도로만 구현했습니다,,
저는 RowMapper에서 rowNum을 사용하지않았는데
https://github.com/spring-projects/spring-framework/issues/7796#issuecomment-453314824
RowMapper rowNum에 관한 Pr을 확인했을때
- 적은 정보를 제공하기 보다 많은 정보를 제공하는 것이 낫다
- rowNum 인수를 무시하는 것은 충분히 쉽다
라는 이유때문에 대부분 사용하지않지만 남겨둔것으로 보였습니다.
그래서 저는 이때까지 rowNum을 사용해본적이없고 오히려 불편하기도하며 코드가 더러워지는것같아서 제거했습니다,,
flyway jdbc도 rowNum없이 인터페이스를 정의했네요,,
이번 미션 잘 부탁드립니다! 👍

[JDBC 라이브러리 구현하기 - 1단계] 파워(송재백) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 루카 ~! 이렇게 만나뵙게 되서 영광입니다 히힛 😉
1단계를 우선적으로 구현해보았어요.
미션을 진행하면서, 궁금한 점이 두 가지정도 있었는데요..
두 가지 모두 JdbcTemplate의 queryForObject 메서드 관련입니다 !
**1. 예외처리**
스프링 부트에서 해당 메서드를 사용할 때, 결과가 없거나 2개 이상일 경우에 오류가 발생하는데요 !
현재는 데이터가 없는 경우에만 예외를 던지고 있는데, 2개 이상인 경우에는 주석처리를 해두었어요.
그 이유는 테스트 코드에서 롤백이 되지 않기 때문에.. 테스트가 통과가 안 되더라구요 ㅠㅠ
이 부분을 어떤 방식으로 해결할 수 있을까요..
**2. 파라미터**
제가 알기론, queryForObject 메서드의 파라미터 중에 Class 타입이 들어가는 것으로 알고 있는데요.
현재는.. rowMapper를 통해 구현해놓은 상태입니다.
Class 타입을 받아서.. 어떻게 구현할 수 있을지 고민입니다 ㅠㅠ
리플렉션을 사용해서, 필드를 초기화해주는 방법밖에 없을까요 ?

[JDBC 라이브러리 구현하기 - 1단계] 쥬니(전정준) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 오잉! 디노입니다~🦖
잘 지내고 계신가요?
우가를 통해 간간히 소식만 듣고 있네요ㅎㅎ
2단계가 리팩터링이길래 우선 DaoTest만 돌아가는 정도로 구현했습니다!
더도 말고 덜도 말고 한가위만 같아라..
즐거운 추석 연휴 보내세요~🍁🌕

[JDBC 라이브러리 구현하기 - 1단계] 디노(신종화) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

안녕하세요 주디 이렇게 만나뵙게 되어 반갑네용 ㅎㅎㅎ
잘 부탁드립니다 🙇‍♂️

[JDBC 라이브러리 구현하기 - 1단계] 우가(윤정욱) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

베로 안녕하세요! 
안경은 뿔테보다는 무테가 멋집니다. 
이번 미션에서는
1. JDBC Template안에서 예외처리 로직을 한 곳에 모아 적절히 처리하고 (사실 일단 모으긴 했는데 아직 적절히 처리해주는 로직은 없습니다.)사용자에게는 `DataAccessException` 이라는 공통 예외로 던져준다.
2. 템플릿 콜백패턴을 통해 JDBC 안에서 메서드가 계속해서 늘어나더라도 중복 코드를 최소화한다. 
이 두 가지에 집중해보았습니다.
이 과정에서 JDBC Template을 사용할 때 필요한 여러 인터페이스, 클래스들을 만들게 되었는데 이 중 RowMapper에 대한 사소한 의문이 생겼습니다.
RowMapper의 메서드 mapRow 에서 두번째 파라미터 rownum은 언제 사용하는게 적절할까요? (저는 아직은 필요를 못느껴 삭제했습니다.)
민족의 대명절 추석이 얼마 안남았는데 건강 잘챙기시고 가족분들한테도 안부 전해주세요 감사합니다.

[JDBC 라이브러리 구현하기 - 1단계] 포이(김보준) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/dao/EmptyResultDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 로건! 😎
발표 스터디 이후로 오랜만이네요 ㅎㅎ 즐거운 명절 보내고 계신가요?! 🌕
요구사항을 만족시키는 선에서 간단하게 구현해봤어요!
queryForObject와 query 메서드에서 중복이 있는 것 같아 아쉬움이 있는데,
2단계 요구사항이 리팩토링인 만큼 우선 돌아가는 코드를 작성하는데 집중했어요!
그럼 리뷰 잘 부탁드립니다 🙇🏻‍♀️

[JDBC 라이브러리 구현하기 - 1단계] 애쉬(정설희) 미션 제출합니다

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
study/src/main/java/connectionpool/DataSourceConfig.java
study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
study/src/test/java/connectionpool/stage1/Stage1Test.java
study/src/test/java/connectionpool/stage2/Stage2Test.java

안녕하세요 바론! 연휴 잘 보내고 계신가요?!
JDBC 라이브러리 구현해서 보냅니다!
리뷰 잘 부탁드려요~!

[JDBC 라이브러리 구현] 리오(오영택) 1단계 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapResultSetExecutor.java

안녕하세요 베베 2단계는 리팩터링이 요구사항이라 리팩터링을 했습니다.
제가 구현한 코드보다 나은 방법이 있을 방법이 있을 것 같은데 머리가 굳었는지 고정관념 때문인지 생각이 안나네요
베베의 조언 기다리겠습니다.

[ JDBC 2단계] 박스터 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

안녕하세요 헤나!
리뷰어-리뷰이로 만나게 돼서 영광입니다 🙇‍♂️
추석에 바쁘게 움직이다 보니 1단계 제출이 생각보다 살짝 늦어졌네요 하하,,
이번 1단계는 요구 사항에 나온 것처럼 `UserDaoTest`를 참고해 테스트가 통과하도록, `JdbcTemplate`에서 DB 관련 작업을 하고 `UserDao`에서는 쿼리문과 결과 값에만 집중할 수 있도록 분리해 구현했습니다.
리뷰 잘 부탁드립니다 😎
[커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/331/files/06379e5dfc39fca37fa096cc17bb04273303e594..6294dfd4937e1c78cc8ea5ee101abec4016940fb)

[JDBC 라이브러리 구현하기 - 1단계] 망고(고재철) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 에단! 만나뵙게 되어 반갑습니다 :)
이번 단계에서는 학습테스트를 통해 JDBC 템플릿에서 제공하는 기본적인 기능들을 익히는 데에 초점을 두었습니다.
반복되는 코드들을 줄이기 위해 JDBC에서 어떤 구조를 가지고 있는지, 라이브러리를 확인하여 대략적인 메서드 시그니처를 확인하였고 구현해봤습니다. 앞으로도 여러가지 방향으로 대화 나누어봤으면 좋겠네요! 감사합니다.

[JDBC 라이브러리 구현하기 - 1단계] 헙크(정현승) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/build.gradle
jdbc/src/main/java/org/springframework/jdbc/BadGrammarJdbcException.java
jdbc/src/main/java/org/springframework/jdbc/CannotGetJdbcConnectionException.java
jdbc/src/main/java/org/springframework/jdbc/JdbcException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/main/java/org/springframework/jdbc/core/StatementCreator.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

[JDBC 라이브러리 구현하기 - 1단계] 도치(김동흠) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/dao/EmptyResultAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/ArgumentPreparedStatementSetter.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 스플릿! 마코입니다~😄
스플릿을 마지막으로 모든 온보딩 조원과 페어, 미션을 진행했네요ㅎㅎㅎ
일단은 요구 사항만 충족시키도록 구현했습니다.
무언가 더 해보고 싶지만 어렵기도하고 2단계가 리팩터링이라 다음 단계로 미루겠습니다.
즐거운 추석 보내세요~~🌕

[JDBC 라이브러리 구현하기 - 1단계] 마코(이규성) 미션 제출합니다. 

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

안녕하세요 이레~~!! 바론입니다 😸 
JDBC 미션의 리뷰어로 이레를 만나게 되어서 너무 기쁘네용 ㅎ.ㅎ
이번에는 1단계 요구사항에 맞춰서 UserDao에 있던 Connection을 통해 직접 결과를 만들고, 쿼리를 날리는 부분을 JdbcTemplate으로 옮겼습니다!
그리고 UserDaoTest가 모두 통과하도록 UserDao에 있던 `todo` 메서드들을 마저 구현했습니다.
[이 커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/305/files/06379e5dfc39fca37fa096cc17bb04273303e594..8b660b81022357bc7b70f34515d7eab34f771775)만 리뷰 해주시면 감사하겠습니다! 
리뷰 잘 부탁드립니다~~~~~ 💟

[JDBC 라이브러리 구현하기 - 1단계] 바론(이소민) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml
study/src/test/java/aop/stage0/Stage0Test.java

안녕하세요 디노~ 추석 잘 보내고 계신가요~?
미션 잘 부탁드립니다!(명절 다 보내시구 천천히 해주셔도 돼요 :))

[JDBC 라이브러리 구현하기 - 1단계] 말랑(신동훈) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/resources/truncate.sql
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 무민! 만나서 반갑습니다 🙇‍♂️
추석 연휴는 잘 보내고 계신가요? 어제 달이 진짜 크던데 보셨는지 모르겠네요.
처음에 어디서부터 어디까지 구현해야할 지 감이 안와서 [Oracle 공식문서](https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html) 보고 감을 잡았습니다.
UserDaoTest의 경우도 제 입맛대로 단언문을 바꿔보았어요.
그에 따라 요구사항에는 존재하지 않지만 DB를 clean up 해주는 메서드도 구현하게 된 점 미리 말씀드립니다.
그럼 잘 부탁드립니다 👍

[JDBC 구현하기 - 1단계] 도기(김동호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

안녕하세요 말랑!
리뷰 잘부탁드립니다 😊
이번 단계에서는 구현한 코드가 많지 않아서 코멘트 남길 부분은 별로 없네요.
즐거운 한가위 되세요! 😃

[JDBC 라이브러리 구현하기 - 1단계] 이오(이지우) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/MyPreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/ObjectMapper.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

오랜만입니다~ 비버 
잘 지내고 계시죠? 
저는 잘 지내고 있답니다. 
리뷰 잘 부탁드립니다 ^^
감사합니다.

[JDBC 라이브러리 구현하기 - 1단계] 에밀(김대희) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java

안녕하세요 파워! 코코닥입니다
1단계를 통해서 2단계의 요구사항을 대부분 만족했던 것 같아요.
그래서 무엇을 더 리팩터링해볼 수 있을까 고민하다가, `try-catch 구문에 대한 반복을 제거해보면 좋겠다!` 싶어서 해당 부분을 목표로 리팩터링을 진행했습니다.
`try-with-resources 구문, SQLException 을 적절한 UncheckedException 으로 치환하는 행위, 로깅 등등의 로직`들이 JdbcTemplate 메서드들에 공통적으로 들어가있는 상황이었습니다.
각 메서드들마다 다른 점은 try-catch 내부의 상세 로직들이었는데요!
그렇다면 공통적으로 들어갔던 로직들을 템플릿화 시킨 후, 기존의 상세 로직을 콜백 객체로 묶어서 파라미터로 넘긴 뒤, 해당 콜백 객체를 실행시키면 코드 중복이 효과적으로 제거되지 않을까? 해서, 해당 방향으로 리팩터링 해보았습니다.
기존 `JdbcTemplate` 내부 메서드들이 가지고 있던 상세 로직들에 대한 콜백 인터페이스입니다.
함수형 인터페이스로 만들어서 람다식으로 상세 로직들을 주입해줄 수 있게 만들어주었습니다.
템플릿 콜백 패턴을 사용한 클래스입니다.
기존 `JdbcTemplate` 이 가지고 있던 try-catch 구문을 `PreparedStatementExecutor` 내부로 옮겼습니다.
`JdbcTemplate` 에서 상세 로직을 람다식으로 넘기면, `PreparedStatementExecutor` 내부에서는 해당 람다식에 대한 콜백 객체를 실행합니다.
---
마지막으로, `SQLException` 을 적절한 …

[JDBC 라이브러리 구현하기 - 2단계] 코코닥(이승용) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/ArgumentPreparedStatementSetter.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/org/springframework/jdbc/core/SimplePreparedStatementCreator.java
study/src/main/java/aop/config/DataSourceConfig.java

안녕하세요 헙크 🥳
빠르게 피드백 주신 덕분에 2단계도 빠르게 구현해보았습니다 !
`execute`, `query` 메서드의 로직이 아래와 같은 순서로 진행되는 것을 확인할 수 있었습니다.
1. PreparedStatement 생성
2. 매개변수 설정
3. PreparedStatement 실행
따라서 해당 부분을 템플릿 콜백 패턴을 사용하여 중복을 줄일 수 있도록 리팩토링 해보았습니다 :)
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/366#discussion_r1342412399
1단계 미션 리뷰에 대한 답변도 달아두었는데 확인해주시면 감사합니다 ㅎㅎ
2단계 미션도 잘 부탁드립니다 🙇🏻‍♂️

[JDBC 라이브러리 구현하기 - 2단계] 다즐(최우창) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/exception/UserFoundException.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/exception/DatabaseResourceException.java

안녕하세요 오도 저번에 리뷰 잘해주셔서 감사해요 ㅎㅎ
밑에 커멘트 남겼으니 한 번 봐주셨으면 해요 !
[이전 PR](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/289)
이번 2단계의 목표는 클린코드 작성하기로 파악했습니다. 
나름대로 clean하게 작성하려고 노력해봤는데 오도가 느끼기엔 아닐 수도 있어서 (ㅠ) 리뷰 잘 부탁드려요 !
즐거운 연휴되세요 ~

[JDBC 구현하기 - 2단계] 하디(전동혁) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/exception/UserNotFoundException.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementBinder.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreator.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetMapper.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/MultipleDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/PreparedStatementTemplateException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/ResultSetTemplateException.java

안녕하세요 오리 
추석 연휴 잘 지내고 계신가요? 
저는 뭐...집에서 코딩이나 했습니다 
---
리뷰 반영의 경우 `JdbcTemplate 메서드 네이밍 변경 & userRowMapper static 필드화`를 적용했습니다
메서드 네이밍...참 어려운 것 같습니다
---
이번 step2에서는 뭘 해야하나 좀 감이 안잡혔습니다 
그래서 고민좀 하다가 힌트랑 `transaction.stage1.jdbc` 패키지의 있는 내용을 살짝 봤는데 함수형 인터페이스를 활용해서 코드의 중복을 없애는 느낌인 것 같더라고요..?
저는 이전 step1 정도가 코드의 중복은 있을지언정 가독성은 더 좋다고 생각해서 상상도 못하고 있었는데 좀 당황스러웠습니다 
아무튼 코드의 중복(특히 try-with-resource 파트)을 없애는 것이 2단계 미션에서의 목표라고 생각해서 함수형 인터페이스와 템플릿 콜백 패턴을 사용해봤습니다
JdbcTemplate, PreparedStatementTemplate, ResultSetTemplate 이런 식으로 시리즈 느낌이 나도록 처리했습니다
JdbcTemplate은 Connection과 PreparedStatement에 대한 자원을 관리하는 PreparedStatementTemplate.execute() 메서드만 호출하도록 했습니다 
PreparedStatement에서 ResultSet에서 조회 결과를 꺼내야 하는 경우는 ResultSet에 대한 자원을 관리하는 ResultSetTemplate.execute()만 호출하도록 했습니다
각각의 템플릿 클래스에서 발생하는 예외는 별도로 분리했습니다 …

[JDBC 라이브러리 구현하기 - 2단계] 지토(김지민) 미션 제출합니다.

---

app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/QueryTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/SelectExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/UpdateExecutor.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 루카 ~! 2단계 구현해서 제출합니다 !
사실, 1단계와 크게 달라진 부분은 없는 것 같아요.. (힌트를 읽어봐도 이미 적용한 내용인 것 같아서 ㅠㅠ)
전반적인 리팩토링을 수행하면 될 것 같아서, 메서드 분리에 초점을 두었어요.
물론, 이마저도 크게 바뀐 건 없지만요 ㅎㅎㅎ
---
템플릿 메서드...를 도입해보았어요 ㅎㅎ 죄송합니다 루카 😗
한 가지 궁금한 점이 생겼어요 ㅎㅎ
```java
public <T> List<T> query(String sql, RowMapper<T> rowMapper, Object... args) {
return queryTemplate.query(sql, (pstmt -> {
try(ResultSet rs = pstmt.executeQuery()){
return mapResultToList(rs, rowMapper);
}
}), args);
}
```
위 코드를 보면, ResultSet을 try-with-resources로 반환해주고 있는데요.
ResultSet의 코드 주석(?)을 확인해보면,
> A ResultSet object is automatically closed when the Statement object that generated it is closed, re-executed, or used to retrieve the next result from a sequence of multiple results.
와 같이 나와있어요. 즉, PreparedStatement가 반환되면 ResultSet도 함께 반환되어야할 것 같은데, 실제로는 그렇지 않더라구요. …

[JDBC 라이브러리 구현하기 - 2단계] 쥬니(전정준) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
jdbc/build.gradle
jdbc/src/main/java/org/springframework/dao/JdbcException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/jdbc/support/DataSourceConfig.java
jdbc/src/test/java/nextstep/jdbc/support/DatabasePopulatorUtils.java
jdbc/src/test/java/nextstep/jdbc/support/TestData.java
jdbc/src/test/resources/schema.sql

안녕하세요 썬샷!!
2단계 미션제출합니다!
우선 썬샷이 남겨주신 코멘트들에 대한 내용입니다.
[? 갯수와 args 처리](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/326#discussion_r1341992119)
> 추가적으로 쿼리문의 `?` 갯수와 args.length가 다른 경우는 어떻게 처리해주는 건가요? 전부 SQLException에 포함이 되나요?
해당 부분은 신경쓰지못하였었는데, 확인해보니 `SQLException`에 포함이 되어있더라고요.그래서 이부분은 추가적으로 검증을 한번 더 해야할까 아니면 포함이 되어있으니 추가작업은 없어도 되는것을까 하는 고민을 해보았습니다.
결과적으로 그냥 SQLEcpetion에 포함이 되어있으니 추가적인 검증은 안하기로 하였습니다.
이유는 JDBC라는것이 라이브러리이기때문에 명시적으로 한번 더 검증을 해준다보다도 매 요청마다 String에 대한 검증을 해주는 것에 대한 리소스를 줄이는것이 더 적합하지 않을까 하는 생각에서 안하고 그냥 SQLEception으로 한번만 검증이 되로고 처리하였습니다.
[queryForObject의 결과 row수에 대한 예외처리](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/326#discussion_r1341992024)
> 반환형이나 메서드명으로 봤을 때 queryForObject가 한 개의 요소만 반환하는 것을 기대하는 것 같은데 ResultSet에 여러 요소가 들어있는 경우는 어떻게 처리하는 것이 좋을까요?
이부분도 신경을 …

[JDBC 라이브러리 구현하기 - 2단계] 필립(양재필) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/QueryTemplate.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 애쉬😀 즐거운 명절 보내고 계신가요.. 조그마한 선물 준비해봤습니다..ㅎ
이번 미션 진행하면서 Connection, PreparedStatement를 얻는 중복 코드를 제거하려고 노력했습니다. QueryTemplate 클래스를 이용해 템플릿 콜백 패턴을 흉내 내봤습니다. 
QueryTemplate 에서 실질적으로 쿼리를 수행하고 JdbcTemplate 에서는 단건 조회, 전체 조회에 맞게 rowMapper 코드를 이용한 반환 데이터 셍성 코드를 콜백으로 QueryTemplate 으로 넘기고 있습니다! 이 구조에 대해서도 리뷰해주시면 감사하겠습니다 ㅎㅎ
현재 JdbcTemplate 에 주석이 있는데 단건 조회 시 2개 이상의 데이터가 나왔을 때의 예외처리 코드인데요. 테스트 코드를 짜려고 했는데 현재 테스트에서 저장한 데이터를 롤백시킬 수가 없어서 정상적인 테스트가 안되더라고요.. 트랜잭션 적용시키면서 해당 주석을 제거하고 테스트할 수 있을 것 같아요!
지난 PR에 남겨주신 리뷰 내용도 모두 반영하려고 노력했습니다! 
그럼 남은 연휴 즐겁게 보내십셔. 리뷰는 천천히 해주셔도 됩니당. 그럼 20000~

[JDBC 라이브러리 구현하기 - 2단계] 레오(차영호) 미션 제출합니다. 

---

README.md
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecuter.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementMaker.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementQueryExecuter.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementUpdateExecuter.java
jdbc/src/main/java/org/springframework/jdbc/core/SetPreparedStatementMaker.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/org/springframework/jdbc/core/PreparedStatementQueryExecuterTest.java
jdbc/src/test/java/org/springframework/jdbc/core/PreparedStatementUpdateExecuterTest.java
jdbc/src/test/java/org/springframework/jdbc/core/SetPreparedStatementMakerTest.java

안녕하세요 주노!
오랜만에 찾아뵙습니다 😃 
바 선생님과의 불화는 안녕하신가요? 부디 잘 해결하셨기를 바랍니다 🔥 
2단계 미션을 구현해서 제출합니다.
중복코드를 제거하기 위해 변하는 것과 변하지 않는 것을 구분했어요.
제가 생각했을 때 변하는 것은 두 가지였습니다.
- PreparedStatement 를 만드는 것
- PreparedStatement 으로 execute 하는 것
따라서 두 요소를 추상화해서 중복을 줄였습니다.
중복은 줄었지만 복잡도가 올라간 것 같아, 주노가 보기에는 어떤지 궁금하네요!
[커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/416/files/1282e00473505a4c712a723f0c18e8cdbcf0fcce..b214ce02703693da92cbb258dd0eff6e755bc55b)는 여기있어요! 2단계도 잘 부탁드립니다.

[JDBC 라이브러리 구현하기 - 2단계] 후추(주찬민) 미션 제출합니다.

---

jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementFunction.java

안녕하세요 말랑!
저번 미션에서 대부분의 리팩토링을 진행한 탓에, 이번 미션에서 뭘 해야할지 몰라 고민하다 늦어졌습니다. 🥲
방향을 잡는데 오래걸렸는데, 반복되는 try-catch 문을 제거하는 것이 가장 리팩토링의 효과가 클 것 같아 해당 부분을 진행하였습니다.
처음에는 굳이 커스텀 함수형 인터페이스를 만들 필요가 없다고 생각했는데, SQL exception을 잡지 못하는 탓에 try-catch의 반복을 없앨 수 없더라구요.
그래서 결국 `PreparedStatementExecutor`와 `PreparedStatementFunction`을 추가해 주었습니다.
이번 리뷰도 잘부탁드려요!

[JDBC 라이브러리 구현하기 - 2단계] 이오(이지우) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/BaseJdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementAction.java

안녕하세요 하마드! 조이입니다 ~
연휴는 잘 보내고 계신가요? 
지난 리뷰에 대한 답변은 작성해두었으니 편하실 때 확인해주세요 ㅎ
이번 단계는.. try-with-resources  중복 부분이나 null 처리 부분을 리팩터링을 하긴 했는데, 그 이상으로 어떤 부분을 더 변경해봐야할지 생각이 잘 안나네요.. 
그래서 결론적으로 보면 코드 변경이 많이 없습니다 😅
혹시 보시면서 개선할 부분이 보이면 말해주시면 너무 감사할 것 같아요!!
이번 리뷰도 잘 부탁드립니다 ~🙇🏻‍♀️

[JDBC 라이브러리 구현하기 - 2단계] 조이(김성연) 미션 제출합니다. 

---

jdbc/src/main/java/org/springframework/jdbc/core/AutoClosableTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 오잉~👨‍🎤 다이노입니다🦖
즐거운 추석 연휴 보내고 계신가요ㅎㅎ
벌써 연휴의 절반을 넘어가고 있네요..
2단계는 리팩터링이더라구요..!
jdbcTemplate의 각 메서드마다 try-catch가 붙어있는게 맘에 안들긴 하지만
어떻게 해야 더 깔끔하게 짤 수 있을지 잘 모르겠네요..
오잉의 조언 부탁드립니다..
남은 추석 명절 즐겁게 보내시구
이번 단계도 잘 부탁드려요~~
(오잉이 1단계에서 남겨주신 리뷰 이번 단계에 적용했습니다.!)

[JDBC 라이브러리 구현하기 - 2단계] 디노(신종화) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/ConnectionContext.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/ConnectionContextException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/JdbcTemplateException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/MultipleDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/PreparedStatementTemplateException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/ResultSetTemplateException.java
jdbc/src/main/java/org/springframework/transaction/TransactionTemplate.java
jdbc/src/main/java/org/springframework/transaction/TransactionalCallbackWithReturnValue.java
jdbc/src/main/java/org/springframework/transaction/TransactionalCallbackWithoutReturnValue.java
jdbc/src/main/java/org/springframework/transaction/exception/TransactionTemplateException.java

안녕하세요 오리 
이번 3단계는 트랜잭션 관련 강의에서 언급된 Programmatic Transaction Management에서 아이디어를 얻어서 진행했습니다 
트랜잭션의 경우 기존과 유사하게 TransactionTemplate라는 클래스를 만들어 템플릿 패턴을 사용했고 하나의 트랜잭션에서 수행할 로직의 묶음은 함수형 인터페이스로 처리했습니다
이 함수형 인터페이스는 반환값이 없는 경우와 있는 경우 두 가지로 분리했습니다
각 Dao가 동일한 커넥션을 사용할 수 있도록 ConnectionContext라는 클래스를 만들고, 내부적으로는 ThreadLocal을 활용하도록 했습니다 
이로 인해 같은 커넥션을 사용할 수는 있게 되었지만, PreparedStatementTemplate과 같은 기존 코드에서는 이 커넥션이 언제 close되어야 하는지 알 수 없어서 try-with-resource에서 커넥션을 제거하고, ThreadLocal의 값을 제거하기 전에 커넥션을 꺼내서 close 해주는 식으로 진행했습니다
이번 리뷰도 잘 부탁드립니다

[JDBC 라이브러리 구현하기 - 3단계] 지토(김지민) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java

안녕하세요! 루쿠! 성하입니다! 👋🏻
이번 3단계에서는 UserService에 Transaction을 적용해봤습니다!
UserDao와 UserHistoryDao의 로직 중 하나라도 실패하면 롤백이 되도록 해야 했는데요!
그래서 UserDao와 UserHistoryDao가 동일한 Connection 객체를 사용해야 했고,
동일한 Connection 객체를 사용하기 위해 
메소드를 오버로딩하여 Connection을 파라미터로 받아서 동일한 Connection을 넣어주게 되었습니다!
현재 서비스 코드에서 Connection 객체가 사용되어 비즈니스 로직과 섞이고 있지만
이후 4단계 미션 요구사항을 지키다보면 분리될 것 같아서 3단계는 이렇게 제출하겠습니다!!
리뷰 잘 부탁드려요 루쿠! 👍🏻

[JDBC 라이브러리 구현하기 - 3단계] 성하(김성훈) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java

안녕하세요 헤나!
추석동안 열심히 쉬고 오랜만에 다시 돌아왔습니다 😎
2단계는 리팩터링인데 다른 부분들은 이미 1단계에서 진행한 것 같아서 try - catch 중복되는 부분들만 신경써봤습니다.
try - catch 중복을 어떻게 없앨지 찾아보다가 템플릿 콜백 패턴이란 게 있는 걸 보고,
`PreparedStatementCallback` 함수형 인터페이스를 만들어서 `JdbcTemplate`에서 콜백 함수를 불러서 처리하도록 리팩터링 했습니다.
이 외에는 크게 변경 사항은 없어요! (null 값 처리 정도..?)
이번 리뷰도 잘 부탁드려요~ 🙇‍♂️

[JDBC 라이브러리 구현하기 - 2단계] 망고(고재철) 미션 제출합니다.

---

app/build.gradle
app/src/main/java/com/techcourse/config/DataSourceConfig.java
app/src/main/java/com/techcourse/support/jdbc/init/DataSourceConnectionManager.java
app/src/main/java/com/techcourse/support/jdbc/init/PooledDataSourceConnectionManager.java
app/src/main/resources/logback.xml
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/build.gradle
jdbc/src/main/java/org/springframework/jdbc/SqlQueryException.java
jdbc/src/main/java/org/springframework/jdbc/core/ConnectionCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 에코!!  
연휴에도 빠르게 리뷰해주셨는데, 프로젝트 우선순위에 밀려서 2단계를 조금 늦게 제출하네요..ㅎㅎ  
지난 리뷰 #316 에 코멘트 답변들도 남겨두었습니다~!
이번 리팩터링에서는 힌트를 보지 않고 기존 JdbcTemplate의 중복 코드를 제거하는 데 집중했습니다.  
- 안정적인 리팩터링을 위해, (UserDaoTest로도 확인 가능하지만) JdbcTemplateTest를 작성하고 진행했습니다.  
- 에코가 제안해주신 덕분에 커넥션풀을 적용해보는 경험을 했어요! HikariCP 의존성을 추가한 이유는 아래와 같습니다.
- 의존성 추가 없이 하는 법을 고민했는데요. JdbcConnectionPool을 사용하면 가능하지만,  H2에서만 지원된다는 점이 아쉬웠어요. 또, 실제로 스프링부트에서 사용하는 커넥션 풀을 써보고 싶었어요. 추가로, 로그를 통해 진짜 커넥션을 기본값(10개)만큼 미리 만드는지 확인해보았습니다.
- 트랜잭션 적용은, 지금은 조금 감이 안오기도 하고 3단계 요구사항과도 겹쳐서 3단계와 함께 진행하려고 합니다.
이번에도 좋은 리뷰 부탁드려요 🙇‍♀️ 감사합니다!!

[JDBC 라이브러리 구현하기 - 2단계] 도이(유도영) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/DatabaseConnectionException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 하디!
추석 연휴 잘 보내셨나요??
이번에 리팩터링은 try-with-resource, optional, exception을 적용하고, 추가적으로 Class Type으로 변환하는 과정을 RowMapper로 변환했어요. 확실히 RowMapper로 변경하니까 코드가 많이 깔끔해졌네요
중복코드 제거하다가 검색해보니 템플릿 콜백 패턴이 있던데, 더 찾아보니까 여기에 적용하기엔 단순 코드 중복 제거를 위해 클래스가 많아져서 배보다 배꼽이 크게 느껴지는 것 같아 적용을 안했어요.
감사합니다!
아래는 1단계 코멘트 주신거에 대한 답변이에요
---
> https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html
를 참고해보시면 jdbctemplate의 메서드에 대해서 볼 수 있는데요 !
queryForObject를 비롯해서 여러 메서드들이 두 번째 인자로 Class<T> 또는 RowMapper<T>를 받고 있습니다 !
로건은 현재 Class<T>를 구현해주셨는데요 !
jdbctemplate은 RowMapper<T>와 Class<T>를 받는 메서드를 왜 모두 구현해 놨을까요 ?
로건의 생각을 듣고싶습니다.
2단계 진행하면서 대략적인 장단점을 확인할 수 있었어요
확실히 `RowMapper<T>`를 사용한다면 메서드와 `RowMapper<T>`를 왔다갔다하는 경우가 있었는데, `User.class`로 사용하니까 해당 메서드에만 집중할 수 있어서 컨텍스트 스위칭이 없다는 점이 …

[JDBC 라이브러리 구현하기 - 2단계] 로건(정다빈) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 모디! 2단계 제출까지 시간을 너무 오래 끌었네요..
변경된 건 별로 없습니다.
JdbcTemplate의 query() 메서드가 List를 반환해야 하기 때문에 `while(rs.next())`를 해야하는데 `if(rs.next())`로 되어있었더라구요! 그 부분을 해결하고, 기존 JdbcTemplate의 모든 메서드에서 `try-with-resources`를 이용해서 `Connection`과 `PreparedStatement`를 관리하던 부분이 중복 코드라 이걸 제거하고자 노력했습니다.
그런데 뭔가 이전보다 보기 더 어려워진 것 같기도 하네요. 
모든 메서드가 아래 형태의 `pstmt`를 갖고 있는데요,
```java
final Function<PreparedStatement, Integer> fuction = pstmt -> {
try {
~~~
} catch (SQLException e) {
throw new RuntimeException(e);
}
};
```
이 부분에서 `try-catch`문도 어쩔 수 없이 계속 생겨서 깔끔하지 못한 것 같습니다.
중복 코드 관련해서 모디는 어떻게 처리하셨는지 궁금하네요!

[JDBC 라이브러리 구현하기 - 2단계] 엔초(권예진) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/exception/UserNotExistException.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/dao/EmptyDataAccessException.java
jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/QueryExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java

안녕하세요 이레! 바론입니다 🙇‍♀️ 
이번 단계에서는 리팩터링 하는 과정을 거쳤는데요, 생각보다 이것저것 고민할 부분이 많아서 변경 사항이 많아진 것 같습니다. 
1. **`JdbcTemplate`에서 `queryForObject` 로 조회할 때 `Optional` 을 반환하기 VS 예외를 발생시키기**
1단계에서 이레와 이야기 할 때는 `queryForObject `라는 이름이 있으니 "단일 조회"가 아닌 모든 경우는 예외를 발생키여야 할 것 같다 라고 결론을 내렸었어요. 이번 단계를 진행하면서도 "`JdbcTemplate`은 자신의 역할에만 충실해야 하므로 단일 객체 조회라는 목적에 어긋나면 예외를 발생시키고, 이에 대한 처리는 개발자가 DAO에서 하는 것이 맞다" 라고 결론을 내려서 동일하게 구현을 했습니다! 
2. **`UserDaoTest` 격리시키기**
기존의 테스트는 `BeforeEach`에서 `insert` 작업을 하기 때문에 전체 테스트를 실행하면 중복된 `insert` 데이터가 들어가 있는 문제가 생겼습니다. (데이터를 삭제하는 로직이 없었더라구요) 
이를 해결하기 위해 `JdbcTemplate`에 DML, SELECT 문 외의 SQL문을 실행시키는 `execute`메서드를 추가하고, `UserDaoTest`에서 `AfterEach`로 테스트 후 데이터를 삭제하도록 하여 각 테스트를 격리시켰습니다.
3. **`rownum (count)` 제거** 
이 부분에 대해서는 이레와 지난 번에 이야기 한 후, 사용되지 않는 파라미터를 가지고 있을 필요가 없다고 생각해서 이 부분을 제거했습니다. …

[JDBC 라이브러리 구현하기 - 2단계] 바론(이소민) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/ExecutionCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java

오랜만이에요 채채
연휴는 잘 보내셨는지요!!
이번 단계에서는 업데이트와 조회 메서드에 중복되는 `try-with-resources` 문을 어떻게 공통 메서드로 분리할 수 있을지에대해 집중해보았어요
update, query, queryForObject 메서드 모두 아래 메서드의 `executionCallback.execute(pstmt)`를 통해 쿼리를 실행하게 되는데요,
```
private <T> T execute(final PreparedStatementCallback preparedStatementCallback,
final ExecutionCallback<T> executionCallback) {
try (final Connection connection = dataSource.getConnection();
final PreparedStatement pstmt = preparedStatementCallback.prepareStatement(connection)) {
return executionCallback.execute(pstmt);
} catch (SQLException e) {
throw new DataAccessException(e);
}
}
```
`update`의 경우에는 `pstmt.executeUpdate()`의 반환값인 `int`를 반환하도록 하고
`query, queryForObject`의 경우에는 `pstmt.executeQuery()`의 결과인 `ResultSet`을 `List<T>로 바꾸는 작업을 추가해서` 반환값이 `List<T>`로 반환되도록 해봤어요(이 부분은 …

[JDBC 라이브러리 구현하기 - 2단계] 이리내(성채연) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/core/StatementExecutor.java

포이 안녕하세요~! 제출이좀 늦어졌네요..ㅎㅎ
중복 제거를 중점으로 리팩토링 해보았는데요..! 
아직 고민이 되는 것은 queryForObject 안에서 인자가 존재하지 않을때 예외가 나지 않도록 if문으로 빈값을 반환하도록 처리를 하였는데 여기서 빈값으로 처리를 한 후 UserService 여기서 예외를 잡습니다..! 이 로직이 전 좀 어색해 보이는데 포이 생각은 어떠신지 궁금합니다..! 
이번 리뷰도 잘부탁드립니다!

JDBC 라이브러리 구현하기 - 2단계] 채채(신채원) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementFunction.java
jdbc/src/main/java/org/springframework/jdbc/exception/EmptyResultDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/exception/IncorrectResultSizeDataAccessException.java

안녕하세요 저문! 이레입니다
추석과 재택근무 기간 잘 보내셨나요?
저는 추석과 재택근무를 너무 신나게 즐긴 나머지 너무 늦은 리뷰요청을 보내게 되었습니다...
3,4단계는 빠르게 리뷰요청 보내도록 하겠습니다. 
1. try-resources-with의 중복 제거
함수형 인터페이스와 람다식의 사용으로 중복을 제거하는 데 초점을 맞추어 코드를 작성했습니다.
2. JdbcTemplate와 DAO의 책임 분리 : `queryForObject`
JdbcTemplate의 `queryForObject`의 경우 단일 객체 조회라는 책임을 가진 메서드로, 단일 객체를 조회하지 못하면 예외를 발생시켜야한다고 생각했습니다.
JdbcTemplate에서 단일 객체를 조회하지 못해서 발생하는 예외(DataAccessException)는 DAO가 처리하는 것이 JdbcTemplate와 DAO의 책임을 명확하게 분리하는 것이라고 판단해 코드륵 작성했습니다.
3. UserDaoTest의 격리성 
queryForObject의 예외를 (0개를 조회한 경우) (n>1을 조회한 경우) 로 구체화 시켜 처리하는 과정에서, UserDaoTest가 통과되지 못하는 상황이 발생하였습니다. 원인은 UserDaoTest의 각각의 테스트들이 inser문을 반복함으로써 격리성을 지키지 못했다는 것이었는데요. 따라서 매 테스트마다 truncat ddl문을 실행시킴으로써 각각의 테스트를 격리하도록 했습니다.
메서드를 추출하면서 코드를 작성하는 과정에서 이해가 안가는 점을 발견했는데.
PreparedStatementFunction<T> 함수형 인터페이스에서 …

JDBC 라이브러리 구현하기 - 2단계] 이레(이다형) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementProcessor.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 무민! 그동안 있던 연휴동안 좀 쉬셨나요?? 쉴 땐 같이 쉬어요 😂
2단계에서 새롭게 적용할 사항이 많이 없어보여서 사실상 1단계 리뷰 반영이 되었네요!
그럼 2단계에도 잘 부탁드립니다 🙇‍♂️

[JDBC구현하기 - 2단계] 도기(김동호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/build.gradle
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
jdbc/src/test/java/nextstep/jdbc/DataSourceConfig.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 연어!
이번 2단계는 전에 한 것들과 유사해서 크게 수정은 하지 않고 테스트와 PreparedStatementSetter 구현정도로 했던 것 같습니다.
연어 커멘트 달아준 것도 여기다가 적을게요!
→ 차이는 없다고 생각합니다. 다만 인덴트가 하나 더 들어간다? 정도가 있을 것 같고 만약 getConnection과 getPreparedStatement사이에 로직이 들어갈 경우에 그 사이에 넣을 수 있을 것이라 생각했습니다. 딱히 큰 차이는 없는 것 같네요!
→ 맞습니다.. 이 부분이 사실 넣은 순서대로 설정을 하니 개발자가 파라미터 순서를 무조건 맞춰서 값을 넣어야하고 그렇지 않을 경우 예외 발생하는 구조인데요, 그래서 예전 기억을 되살려 PreparedStatementSetter 인터페이스를 만들고 그걸 유저가 직접 구현하도록 변경하였습니다!
→ 공식문서를 보면서 메서드 시그니쳐를 정의했는데 공식 문서에 query라는 메서드에 List를 반환하는 메서드가 있더라구요! 그래서 그걸 보고 작성했습니다.
→ 저도 사실 실제 jdbc의 RowMapper에 rowNum이 왜 들어가는지 궁금했었는데, [행 번호로 조작할 일이 있을 수 도 있어서 빼지 않고 있다](https://github.com/spring-projects/spring-framework/issues/7796)고 하네요? 저는 기존 JDBC에 있는 rowNum도 그대로 넣고자 넣었었습니다. (물론 현재는 사용할 일이 없지만요)
> After all, RowMapper implementation might use the row number to …

[JDBC 라이브러리 구현하기 - 2단계] 에코(조은찬) 미션 제출합니다 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/SelectQueryExecutor.java
jdbc/src/main/java/org/springframework/transaction/Transaction.java
jdbc/src/main/java/org/springframework/transaction/TransactionTemplate.java

안녕하세요! 필립!
이번 3단계에서는
서비스 로직들을 하나의 트랜잭션 단위로 묶으라는 것이 포인트였는데요.
그렇다보니, 제가 실제 쿼리문을 execute하는 곳인 QueryExecutor까지  Connection을 넘겨주게 되었습니다.
`유저 서비스` &rarr; `유저 DAO, 유저 히스토리 DAO` &rarr; `JdbcTemplate` &rarr; `ConnectionTemplate` &rarr; `QueryExecutor` 
이 부분 때문에JdbcTemplate을 사용하면서 개발하는 개발자가  서비스를 개발하면서 너무 불편함이 있을 것 같았습니다. 그래서 리팩토링이 매우 하고 싶었지만, 일단 다음 단계로 미뤘습니다!!
이번엔 어떻게 유저가 트랜잭션을 잘 쓸 수 있을지만 고려해서 작성해보았습니다!!
아직 부족한 점이 많지만 다음단계에서 리팩토링 제대로 해보겠습니다!!

[JDBC 라이브러리 구현하기 - 3단계] 루카(백경환)미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecuteStrategy.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/EmptyResultDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/IncorrectResultSizeDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/exception/ResultSetOverflowException.java

안녕하세요 그레이!
빠르게 리뷰해 주셨는데 프로젝트부터 하다 보니 지금이네요... 😅
늦게나마 2단계 리뷰 요청드립니다.
또한, 지난 1단계에서 좋은 리뷰들 감사합니다!
대부분 변명이긴 하지만, 해당 pr에 답변 달아두었습니다. ([1단계 pr 바로가기](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/335))
2단계를 보지 않고 1단계를 진행했는데, 알고 보니 2단계였던 내용들이 많네요.
그래서 이번 2단계에서는 지난번 그레이가 남겨주신 피드백과 중복 코드를 제거하는 방식에 대해 고민해 보았습니다.
`qeuryForObject()`에서 결과가 한 개가 아닌 경우에 대한 예외처리를 진행했으며,
try-with-resources 중복을 제거하는 방법에 대해 많은 분들이 콜백 패턴을 적용해 보았습니다.
그런데, 해당 패턴을 처음 학습해보기도 하고 익숙하지 않아 제가 제대로 적용한 것인지 잘 모르겠네요..!
그 외에도 좀 더 고민해 볼 만한 부분 혹은 수정했으면 하는 부분들이 있다면 말씀해 주시면 감사하겠습니다.
이번 리뷰도 잘 부탁드립니다 😊

[JDBC 라이브러리 구현하기 - 2단계] 제이미(임정수) 미션 제출합니다.

---

app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/transaction/support/DataSourceTransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionCallBack.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java

안녕하세요 헙크 ㅎㅎ
프로젝트 일정을 처리하다 보니 미션을 주말에서야 진행하게 되었네요 🥲
3단계 미션은 `TransactionTemplate`을 구현해 보았습니다!
구현 세부 사항은 아래와 같아요 :)
1. `TransactionManager`에서 `ThreadLocal`을 통해 같은 `Connection`을 공유할 수 있도록 하였습니다.
2. `TranactionCallBack`을 통해 하나의 트랜잭션에서 동작해야 하는 행위를 콜백으로 전달하였습니다.
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/375
2단계 미션에서 남겨주신 커멘트에 대한 답변도 달아두었습니다 !
3단계 미션도 잘 부탁드립니다 🙇🏻‍♂️

[JDBC 라이브러리 구현하기 - 3단계] 다즐(최우창) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/ColumnConversionException.java
jdbc/src/main/java/org/springframework/jdbc/IncorrectResultSizeDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/core/ColumnTypes.java
jdbc/src/main/java/org/springframework/jdbc/core/InstantiateUtil.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/StatementExecution.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

콩하나 안녕하세요~
정말 오래 빈둥대다가.. 이제야 몰아서 미션 했습니다...ㅎㅎ;;
1단계에서 주신 질문에 대한 답변은 모두 달아두었습니다.
2단계 내용의 주요한 점은 connection 획득 및 statement 생성을 한 곳으로 몰았다는 점이고요,
3단계는 service에서 connection을 생성해서 시그니처를 하나하나 바꿔서 넣어주다가...
불편을 참지 못해 4단계에서 쓸 TransactionSynchronizationManager를 통해 ThreadLocal에서 connection을 꺼내 쓰게 해버렸습니다..
changePassword 메서드에 대해서만 TransactionSynchronizationManager를 사용하게 하여
어떠한 서비스 로직은 내부적으로 connection을 생성하고 changePassword는 외부에서 생성한 connection을 공유하는 상황입니다
이로 인해 JdbcTemplate의 connection 획득 방법이 경우에 따라 달라지게 되었는데요,
JdbcTemplate은 외부에서 connection을 생성했는지, 아니면 자신이 생성해야 하는지 (or 트랜잭션이 외부에서 관리되는지)알 수 없으므로 이러한 방향이 3단계에선 조금 더 맞지 않을까.. 싶어서 이렇게 하게 되었어요
try ~ catch를 바르게 적용했는지 잘 모르겠네요 😂
4단계를 하면 트랜잭션으로 인한 지저분한 부분들을 많이 개선할 수 있을 것 같고요.
꼼꼼한 리뷰 감사합니다~!!

[JDBC 라이브러리 구현하기 - 2, 3단계] 모디(전제희) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/ConnectionManager.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionWorker.java
study/build.gradle
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 이레~~~ 바론입니다 🙇‍♀️ 
이번에는 3단계 요구사항에 맞춰서 `UserService`의 `changePassword` 내의 로직들이 모두 같은 트랜잭션 내에서 실행되도록 구현했습니다! 여기에서 트랜잭션 작업을 처리해주는 `TransactionExecutor` 클래스가 추가되었습니다.
그리고 기존에 있던 `dao`, `jdbcTemplate` 의 코드를 모두 외부에서 `Connection`을 파라미터로 받아오는 코드로 바꾸는 것 보다, 기존에 있던 코드에 `Connection`을 받는 상황도 처리할 수 있도록 확장하여 기존 코드의 변경을 가급적 줄이기 위해서 메서드 오버로딩으로 Connection 을 받아오는 `update` 메서드를 추가했습니다.
그리고 Connection을 생성하고, close 해주는 로직을 담당하는 `ConnectionManager`를 추가했습니다!
현재 코드에 TODO로 남아있거나, 리팩터링이 덜 된 부분들 중 4단계 요구사항이라고 생각하여 반영하지 않은 부분은 다음과 같습니다.
1. `Dao`가 `Connection` 을 파라미터로 받아오는 것
2. 스레드 별로 `Connection`을 분리하는 것
이 부분들은 4단계 리팩터링 시에 적용하려 합니다.
이번 리뷰도 잘 부탁드립니다! 감사합니다 :)

[JDBC 라이브러리 구현하기 - 3단계] 바론(이소민) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/dao/CannotAcquireLockException.java
jdbc/src/main/java/org/springframework/dao/CannotGetJdbcConnectionException.java
jdbc/src/main/java/org/springframework/dao/DataAccessResourceFailureException.java
jdbc/src/main/java/org/springframework/dao/DataIntegrityViolationException.java
jdbc/src/main/java/org/springframework/dao/DuplicationKeyException.java
jdbc/src/main/java/org/springframework/dao/IncorrectResultSizeDataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/CanNotCloseResultSetException.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/jdbc/exception/BadSqlGrammarException.java
jdbc/src/main/java/org/springframework/jdbc/support/H2SQLErrorCodeToDataAccessExceptionMapper.java
jdbc/src/main/java/org/springframework/jdbc/support/SQLExceptionTranslator.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 아코! 히이로입니다.
명절에 재택까지 여러모로 다사다난한데 잘 지내고 계신가요? ㅎㅎ
이번 PR은 개인 일정에 치여서 좀 많이 늦었네요... 그래서 2단계에 3단계까지 해서 제출하게 되었습니다.
각 단계에서 초점을 맞춘 부분은 다음과 같아요.
-  JdbcTemplate을 보며 구현하다 보니 다른 부분들은 따로 더 리팩토링할 곳이 잘 보이지는 않더라구요...! 그래서 이번에는 SQLException을 DataAccessException으로 전환해주는 로직을 구현해보는데 집중해봤습니다.
- 원래 제대로 구현했다면 각 DB 벤더사별로 반환하는 SQLException 에러코드 당 DAO Exception 클래스를 정의해줬어야 했을텐데 현재 미션 단위 프로젝트에서는 그 정도 수준의 구현은 불필요하겠다고 판단했습니다.
- 그래서 현재 미션에서 사용하는 H2 DB에서 반환하는 SQLErrorCode들을 기반으로 SQLException들을 spring DAO Exception 혹은 Jdbc Exception 예외로 전환시켜주도록 구현했습니다. (사실 스플릿 PR을 보고 영감을 받은 부분이기도 해요 ㅎㅎ...)
- UserService 테스트를 통과시키는데 집중했습니다. LMS에도 나와있지만 자연스럽게 Dao 내부로 캡슐화했던 DataSource와 Connection이 튀어나올 수 밖에 없겠더라구요 ㅎㅎ... 이 부분을 당연히 해결해봐야겠지만 해당 내용이 4단계에서 수행하게 되는 것 같아 일단 테스트만 통과 시키고 리뷰를 요청하게 되었습니다.
추가적으로 다른 크루들 리뷰를 보다보면 템플릿 패턴, 템플릿 콜백 …

[JDBC 라이브러리 구현하기 - 2, 3단계] 히이로(문제웅) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/support/ConnectionCallBack.java
jdbc/src/main/java/org/springframework/jdbc/support/ConnectionHolder.java
jdbc/src/main/java/org/springframework/jdbc/support/TransactionCallBack.java
jdbc/src/main/java/org/springframework/jdbc/support/TransactionManager.java
jdbc/src/main/java/org/springframework/jdbc/support/TransactionTemplate.java
jdbc/src/main/java/org/springframework/jdbc/support/exception/CannotBeginTransactionException.java
jdbc/src/main/java/org/springframework/jdbc/support/exception/CannotCommitException.java
jdbc/src/main/java/org/springframework/jdbc/support/exception/CannotGetConnectionException.java
jdbc/src/main/java/org/springframework/jdbc/support/exception/CannotRollbackException.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/support/TransactionManagerTest.java
jdbc/src/test/java/nextstep/testUtil/TestDataSourceConfig.java
jdbc/src/test/java/nextstep/testUtil/TestDatabaseUtils.java

안녕하세요 메리! 👋
이번 STEP3 트랜잭션 경계 설정 미션 제출합니다!
이번 미션을 하면서 제일 크게 고민을 한 것은 아래와 같아요! 
> **_"기존의 코드를 최대한 변경없이 어떻게 트랜잭션 경계를 설정할 수 있을까?"_** 
해당 부분을 최대한 반영해보기 위해서 `TransactionManager` 와 `TransactionTemplate` 클래스를 구현하였습니다.
해당 클래스에서는 트랜잭션이 필요한 경우 `TransactionManager`의 `ThreadLocal` 을 통해서 `Connection` 을 생성/반환을 하고 있고,
트랜잭션이 필요없는 부분은  바로 `DataSource`를 통해서 `Connection` 을 반환하고 있습니다.
또한 기존 `jdbcTemplate` 코드 변경을 최소한으로 하다 보니 `connection` 이 자동으로 `close()` 되는 것을 방지하기 위해서
`ConnectionHolder` 클래스를 구현하였습니다. 해당 클래스에서는 트랜잭션 활성화 여부를 통해 `connection` 을 `close()` 합니다.
현재 `commit`, `rollback` 의 책임을 `TransactionManager` 클래스에서 담당하고 있습니다.
다만 이부분을 `ConnectionHolder` 가 Connection 을 가지고 있으니 해당 책임을 위임하면 하면 어떨까? 라는 의문도 드네요. 
이번 STEP3도 잘부탁드립니다! 🙇‍♂️

[JDBC 라이브러리 구현하기 - 3단계] 블랙캣(송우석) 미션 제출합니다.🚀

---

app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
study/src/main/java/transaction/DatabasePopulatorUtils.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/resources/schema.sql

베로 안녕하세요! 
앞으로 더 많은 메서드가 트랜잭션을 사용해야 할 경우 계속해서 중복코드가 생기는 것도 그렇고, 서비스 클래스에 트랜잭션 관련 로직이 보여지는 것도 적합하지 않다고 생각하여 라이브러리 안에 `TransactionManager` 클래스를 만들고,  `@Runnable` 을 인자로 받아 실행하도록 하였습니다.
이 과정에서 파라미터로 connection을 계속해서 넘겨주지 않도록 ThreadLocal을 사용하였고, JDBC Template에서 try-with-resources 로 connection을 항상 close하지 않도록 변경했습니다.
대신 finally 구문을 추가해 DataSourceUtils 클래스에서 트랜잭션 밖의 connection만 close해주도록 변경하고, 트랜잭션 안의 connection은 `TransactionManager` 클래스가 직접 close 해주도록 변경했습니다.
아직은 서비스 계층에 TransactionManager 클래스를 사용하는 코드가 남아있는데, 이 부분은 4단계에서 수정하는게 좋을 것 같아 남겨두었으니 
, 이 부분을 제외하고 리뷰해주시면 좋을 것 같습니다.
또, 날씨가 많이 추워졌는데 아무래도 기습 패딩을 시도하는게 맞는 것 같아요. 얼른 패딩 가져오시죠

[JDBC 라이브러리 구현하기 - 3단계] 포이(김보준) 미션 제출합니다.

---

app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/DataSourceTransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java

안녕하세요 헙크 ㅎㅎ 벌써 마지막 미션이네요 🥲
요즘 따라 시간이 정말 빠르다고 느껴지는데 헙크는 어떠신가요?
4단계에서는 요구사항을 바탕으로 아래 사항들을 학습하고 구현해보는 시간을 가졌습니다!
1. `DataSourceUtils`를 사용하는 `TransactionSynchronizationManager` 구현
2. 트랜잭션 서비스 추상화
3. 현재 트랜잭션이 존재하는지 여부 저장
- `JdbcTemplate`에서도 `DataSourceUtils` 메서드를 사용하게 되는데, 이때 트랜잭션 여부를 확인할 수 없으면 트랜잭션이 종료되지 않았음에도 커넥션 자원을 회수하기에 커밋 시 이미 회수된 자원에 대한 예외가 발생하게 됩니다. 따라서 트랜잭션이 걸려 있으면 자원을 회수하지 않도록 구현하였습니다.
4. `JdbcTemplate`에서 `TransactionManager` 의존성 제거
- 기존에는 커넥션 획득과 자원 회수를 위해 `TransactionManager` 의존성을 가지고 있었지만, `DataSourceUtils`를 구현함에 따라 해당 메서드를 활용하면 되기에 원래대로 `DataSource` 의존성만 가지고 있도록 수정하였습니다.
마지막 미션 리뷰도 잘 부탁드립니다 🙇🏻‍♂️

[JDBC 라이브러리 구현하기 - 4단계] 다즐(최우창) 미션 제출합니다.

---

app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java

안녕하세요 폴로!
어느덧 미션 마지막 단계까지 왔네요!
이전 단계에서 `1. Transaction synchronization 적용하기`를 미리 구현한 덕에 미션 수행에 부담이 적었던 것 같습니다ㅎㅎ
이번단계에서는 요구사항 `2. 트랜잭션 서비스 추상화하기`를 적용하고, 이전 단계에서 폴로가 남겨주신 코멘트에 대해 고민하고 반영해보았어요.
> TransactionManager 를 통해 DB와 통신하는 경우에는 TransactionManager 에서 connection 이 close() 되지만, > 그렇지 않은경우 (예를 들어 UserService#findById 또는 insert) 같은 경우는 close가 안될것 같네요.
> 꼭 트랜잭션을 걸어줘야만 connection이 close 되는게 맞을까요???
사실 저도 3단계를 구현하면서 이 부분에 대해 고민을 했었는데요, TransactionSynchronizationManager에서 커넥션을 관리해주고 있기 때문에, close()되지 않은 Connection은 close()될 때까지 재활용할 수 있으니 예기치 못한 누수는 발생하지 않을거라 생각했습니다. 그래서 괜찮을 거라고 생각했던 것 같아요.(close()되지 않은 커넥션이 무한정 늘어나진 X)
코멘트를 보고 다시 생각을 해봤는데, 커넥션을 오랫동안 붙잡고 있는 게 꼭 좋은 방법은 아닌 것 같더라구요. 그래서 JdbcTemplate의 메서드에 finally 구문을 추가하고, 현재 트랜잭션이 활성화되었는지 여부에 따라 커넥션을 해제해주는 분기를 추가해주었습니다.
그럼 잘 부탁드립니다!

[JDBC 라이브러리 구현하기 - 4단계] 아마란스(송세연) 미션 제출합니다.

---

app/src/main/java/com/techcourse/controller/LoginController.java
app/src/main/java/com/techcourse/controller/RegisterController.java
app/src/main/java/com/techcourse/controller/UserController.java
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/jdbc/TestUser.java

안녕하세요, 깃짱!✨ 홍고입니다.
주말 잘 보내고 계신가요?
2, 3단계 미션 제출합니다. 이번에도 리뷰 잘 부탁드립니다!
[2단계 커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/504/files/8aeea7f480adda97a836504710893095197f3c4a)
`PreparedStatementExecutor`, `ResultSetExtractor` 인터페이스를 생성했습니다.
* `PreparedStatementExecutor` : PreparedStatement를 사용해서 쿼리를 실행하는 로직을 추상화한 인터페이스
* `ResultSetExtractor` : ResultSet에서 반환할 값을 추출하는 로직을 추상화한 인터페이스
중복되는 로직은 `UserDao`의 `execute` 메서드와 `query`메서드로 추출하고, 위 인터페이스들을 사용해서 상세 로직을 주입했습니다.
[3단계 커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/504/files/8aeea7f480adda97a836504710893095197f3c4a..6caec1e956ead955d6681cd81ac7ffa918cd8fdc)
`UserService`에서 Connection을 생성해 Dao의 파라미터로 넣어주고 있습니다. 4단계에서 `UserService`가 Connection을 생성하지 않게 변경해보겠습니다!
\+ Controller가 InMemoryUserRepository에서 UserService와 …

[JDBC 라이브러리 구현하기 - 2, 3단계] 홍고(홍여진) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/domain/UserHistory.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/main/java/transaction/DatabasePopulatorUtils.java
study/src/test/java/transaction/stage1/Stage1Test.java

안녕하세요 하디!
4단계는 코드가 다 연관되어 있어서 커밋 분리를 어떻게 해야할지 감이 안잡히네요
단계별 커밋은 아래와 같습니다.
[3단계 커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/595/files/a5591b3de78785904f760a4e44e88e3826a68a6e..e92467e2b5c3b424ac417156fa2796e70046e2a7)
[4단계 커밋 범위](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/595/commits/199c7d025c93ec2ebb0cc852ac5cafb3ac9dad8a)
감사합니다~

[JDBC 라이브러리 구현하기 - 3, 4단계] 로건(정다빈) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/BaseJdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementAction.java
jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
jdbc/src/main/java/org/springframework/transaction/ConnectionAction.java
jdbc/src/main/java/org/springframework/transaction/TransactionAction.java
jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 하마드!
요구사항에 맞게 기능 추가 및 리팩터링 진행했습니다 ~~
4단계 리뷰도 잘 부탁드립니다 🚀

[JDBC 라이브러리 구현하기 - 4단계] 조이(김성연) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/TransactionExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/TransactionManager.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 에코!! 4단계로 돌아왔습니당  
이번 미션에서는 최대한 기존 코드를 유지하며 요구사항을 만족해보려고 했습니다.  
1. 트랜잭션 중첩 문제
첫번째 요구사항인 트랜잭션 동기화 적용의 경우,  제 코드에서는  
Service, DAO에서 모두 제가 만든 `TransactionExecutor`(이전 네이밍 `TransactionManager`)를 사용하고 있었기에
해당 클래스에서 DataSourceUtils 를 사용하도록 수정했습니다.
- 그런데 이 과정에서, 
`UserService.changePassword`와 같이 여러 개의 DAO 메서드를 호출하면 **DAO 단에서 계속해서 `unbindResource`를 다시 해주는** 문제가 발생했습니다. (그래서 같은 connection을 공유할 수 없음)  
그래서 DAO에서는 `TransactionExecutor`를 거치지 않고 JdbcTemplate을 호출하도록 수정했어요.  
그렇게 했더니, 원래 문제는 해결되었지만  
**별도의 트랜잭션을 지원하지 않고 JdbcTemplate을 바로 호출하는 경우 Connection을 닫아주지 못하는 문제**가 생겼습니다.  
2. 논리적 트랜잭션에 대한 상태 추가
그래서 이 부분은 **`TransactionSynchronizationManager`에 `isActualTransactionActive`이라는 상태를 추가**하는 것으로 해결했습니다.  
해당 내용은 실제 Spring [코드](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/sp …

[JDBC 라이브러리 구현하기 - 4단계] 도이(유도영) 미션 제출합니다. 

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/support/transaction/ServiceLogicExecutor.java
app/src/main/java/com/techcourse/support/transaction/TransactionExecutor.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/preparestatement/PrepareStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/jdbc/exception/DataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/exception/RollbackFailException.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 테오! 
이제 어느덧 jdbc 미션도 마지막이 되었네요..
4단계를 요구사항을 진행하면서 추가적으로 반복되는 코드가 보여서 그 부분도 함께 리팩토링을 진행했습니다.
1. jdbcTemplate에서 connection을 가져오고 SqlException을 catch하는 부분이 반복되어서 이 부분을 수정해보았습니다.
2. 4단계 미션 중에 TxUserService에서도 transaction의 autocommit을 false로 하고 자원을 반환하는 부분이 반복되어서 이 부분도 여러 Service에서 이용할 수 있게 분리해보았습니다.
마지막 리뷰도 잘 부탁드립니다!🙇‍♂️🙇‍♂️

[JDBC 라이브러리 구현하기 - 4단계] 아코(안석환) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TransactionCallback.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/jdbc/support/SQLExceptionTranslator.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
study/build.gradle
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/SecondUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 아코, 히이로입니다!
4단계에서 LMS에 나온 내용은 구현했으나 학습테스트에서 AOP 개념 까지 학습해서 Transactional 어노테이션을 구현해보고 싶었는데 시간 상 문제로 일단 제출하게 되었습니다. 오늘 안에 해보고 싶기는 한데... 한 번 노력해보겠습니다!
항상 정성스런 리뷰 감사합니다! 🙇

[JDBC 라이브러리 구현하기 - 4단계] 히이로(문제웅) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcExecutor.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 모디!
4단계 구현 완료했습니다~
3단계 리뷰에서 질문 주신 부분에 대해서는 해당 pr에 답을 달아놓았습니다. 아래 토글에 사진도 첨부해 놓았으니 답변 확인만 하실 거라면 사진으로 보셔도 될 것 같습니다. [pr 바로가기](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/528)
<details>
<summary>사진</summary>
<div markdown="1">
</div>
</details>
마지막 리뷰도 잘 부탁드립니다~

[JDBC 라이브러리 구현하기 - 4단계] 엔초(권예진) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

땡칠 안녕하세요!
미션을 아까 10시쯤에 마무리지었는데 자기전에 PR 제출을 안했다는게 생각나써 늦은 새벽에 PR을 조심스래 올려봅니다...
마지막 미션도 잘부탁드립니다 🙏

[JDBC 라이브러리 구현하기 - 4단계] 주노(최준호) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TransactionUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/Transaction.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 필립!
이번 미션 드디어 마지막 단계네요!!
이번 단계에서는 트랜잭션을 꼭 유저가 생성하지 않아도 데이터 소스를 주입해주면 특정 범위 안에서는 하나의 트랜잭션만 사용하도록 하는 과정을 구현해보았는데요.
ThreadLocal의 개념이 조금 어려워서 갈피를 못잡았는데, 어떻게 다하긴 했네요 ㅎㅎ
리뷰 잘 부탁드립니다!!

[JDBC 라이브러리 구현하기 - 4단계] 루카(백경환) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TransactionUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/TransactionExecuter.java
jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/org/springframework/jdbc/datasource/DataSourceUtilsTest.java
jdbc/src/test/java/org/springframework/transaction/TransactionManagerTest.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java

안녕하세요 주노 😃 
어느덧 벌써 4단계네요.
시간이 정말 빠른 것 같아요.
이제는 아침, 저녁으로 기온이 쌀쌀하던데, 감기 조심하세요!
지난 [PR](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/491)에 커멘트 남겼어요.
4단계도 잘 부탁드립니다!

[JDBC 라이브러리 구현하기 - 4단계] 후추(주찬민) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/controller/LoginController.java
app/src/main/java/com/techcourse/controller/RegisterController.java
app/src/main/java/com/techcourse/controller/UserController.java
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionServiceExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요, 깃짱!
마지막 4단계입니다ㅠㅠ 
이번에도 리뷰 잘 부탁드립니다! 🙇‍♂️🙇‍♀️

[JDBC 라이브러리 구현하기 - 4단계] 홍고(홍여진) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java

안녕하세요 홍고🍊
람다랑 함수형 인터페이스한테 또 혼나고 온 가비입니다
DataSourceUtils를 이용해서 Connection을 관리하도록 했고
TranasactionManager라는 친구를 만들어서, Service에 있던 트랜잭션 관리하는 넘을 안으로 밀어넣어줬습니다
날씨 추워졌는데 감기 조심하세요...!
4단계 미션 제출하신다음 리뷰해주셔도 됩니다...! 
기간내 리뷰하신다고 스포당하진 않으셨으면🥲

[JDBC 라이브러리 구현하기 - 4단계] 가비 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/TxUserServiceTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
app/src/test/java/com/techcourse/transaction/NestedTransactionTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionCallback.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
jdbc/src/test/java/nextstep/jdbc/TransactionSynchronizationManagerTest.java

홍박사님 안녕하세요.
생각보다 오래 걸렸네요. 이전 코드에서 추가된 것 위주로 말씀드릴게요.
- TransactionSynchronizedManager
이 객체는 트랜잭션들을 바인딩, 언바인딩, 혹은 트랜잭션의 리소스를 들고오는 역할을 합니다. 원래 이렇게 3가지 기능만 하다가 트랜잭션 시작 유무를 확인하기 위해서 actualTransactionActive를 만들었습니다.
- TransactionTemplate
트랜잭션을 시작과 끝을 관리해주는 객체입니다.
- TransactionCallback
트랜잭션으로 어떤 작업을 하는지 함수형 인터페이스로 전달해줍니다.

[JDBC 라이브러리 구현하기 - 4단계] 디투(박정훈) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TransactionalDaoExecutor.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/org/springframework/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java

안녕하세요 주드! 콩하나입니다.
마지막 미션이네용
원래 어제 다 마무리해서 제출까지 하려고 했으나,
어제 갑작스러운 인텔리제이 라이센스 만료 이슈로 인해...
갖가지 방법을 찾아보다가 결국 트라이얼 모드로 30일 무료 이용해서 하고 있네요.
아직 학교 졸업 안했는데 인증이 안된대요.. ㅠㅠ 
깃허브로 인증받는 것도 위와 동일한 이슈로 안되고... 이클립스를 하려하니까 생산성도 떨어지고 빌드가 안돼서
돌고 돌아서 인텔리제이네요 ㅋㅋㅋㅋ
아무튼 그래도 오늘 무사히 미션 완료해서 제출합니다.
이번에도 특별히 집중했던 부분을 공유드릴게요.
원래는 다음과 같이 생각했었습니다.
```
커넥션을 직접 생성하는 대신, `DataSourceUtils`를 사용해 대신 커넥션을 생성해주는 기능을 만들다보니
JdbcTemplate 클래스도 수정을 할지 말지 고민이 많았습니다.
JdbcTemplate에서 `커넥션을 전달받는 메소드는 트랜잭션 관리 책임을 외부`에 맡기고 있지만,
`커넥션을 전달받지 않는 메소드는 트랜잭션 관리를 내부`에서 하고 있기 때문이죠.
그래서 이 부분을 통일해주는게 좋을까말까 고민하다가 일단 한번 해보자!라는 마음으로 JdbcTemplate을 수정했었는데요.
결국 다시 롤백하고, JdbcTemplate은 건들지 않기로 결정했습니다. 그 이유는
1. 4단계 미션은 트랜잭션 추상화에 목표를 둔다. 현재 JdbcTemplate을 관리하는 것은 미션의 목표에는 다소 동떨어져있다
2. 라이브러리는 ocp원칙을 잘 지켜야한다. 그리고 저는 이 원칙을 지키려고 현재의 코드 구조가 나왔다고 판단했습니다.
3. 외부에서 …
```

[JDBC 라이브러리 구현하기 - 4단계] 콩하나(최한빈) 미션 제출합니다.

---

app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java
study/src/test/java/aop/stage2/TransactionPointcut.java

안녕하세요 스플릿!
트랜잭션 동기화는 이전 단계에서 이미 수행해서 트랜잭션 서비스 추상화만 구현했습니다!
jdbc 모듈에 TransactionTemplate을 만들어서 트랜잭션 관련 템플릿을 구현하고 콜백을 받아 트랜잭션을 수행하도록 했습니다.
이번 리뷰도 잘 부탁드립니다~

[JDBC 라이브러리 구현하기 - 4단계] 마코(이규성) 미션 제출합니다.

---

app/build.gradle
app/src/main/java/com/techcourse/dao/JdbcUserHistoryDao.java
app/src/main/java/com/techcourse/domain/UserHistory.java
app/src/main/java/com/techcourse/repository/UserRepository.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/jdbc/transaction/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java

안녕하세요 후추.. 어제 밤에 구현해놓고 제출을 안하고 있었네요 ㅋㅋㅋㅋㅋㅋ 늦은 제출 정말 죄송합니다 ㅠ 마지막 리뷰 잘 부탁드려요!

[JDBC 라이브러리 구현하기 - 4단계] 베베(최원용) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PrepareStatementExecutor.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java

안녕하세요 무민! 건강상 이슈로 이제야 4단계 제출합니다..!
무민은 건강하세요 😢
요구사항에 충실하게 구현해보았습니다.
그럼 이번에도 잘 부탁드려요 :)

[JDBC 구현하기 - 4단계] 도기(김동호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDaoWithJdbcTemplate.java
app/src/main/java/com/techcourse/dao/UserDaoWithNamedParameterJdbcTemplate.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/repository/UserRepository.java
app/src/main/java/com/techcourse/service/TransactionProxyHandler.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/service/UserServiceImpl.java
app/src/test/java/com/techcourse/dao/UserDaoWithJdbcTemplateTest.java
app/src/test/java/com/techcourse/dao/UserDaoWithNamedParameterJdbcTemplateTest.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
app/src/test/java/com/techcourse/jdbc/datasource/DataSourceUtilsTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 엔초! 벌써 마지막 단계네요 🥹
4단계에서 제공해준 DataSourceUtils 덕분에 서비스의 각 계층이 Connection을 계속 파라미터로 넘기는 고리를 끊고 훨씬 깔끔한 코드를 만들 수 있었어요.
하지만 서비스 계층에서 여전히 DataSource와 Connection을 사용해 트랜잭션을 뚱땅뚱땅 조작하는 코드가 섞여있어서, 정말로 집중해야 할 비즈니스 로직이 한눈에 들어오지 않는다는 문제가 여전히 남아있었습니다.
그래서 자바에서 제공해주는 jdk dynamic proxy를 사용해서, 트랜잭션 관련 처리는 프록시 레이어에서 수행하고 실제 서비스 객체는 비즈니스 로직에만 집중할 수 있도록 해내는 데에 성공했어요!
뭔가 뿌듯합니다.
2단계 때 엔초가 피드백 남겨주신 
'jdbcTemplate에서 try-with resource 중복 코드를 제거하는 방법' 도 여러 시도를 해보면서 고민했는데 ,, 모르겠어요! 더 고민해봐야 할 것 같습니다.
마지막 리뷰 잘 부탁드려요!

[JDBC 라이브러리 구현하기 - 4단계] 여우(조승현) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/resources/schema.sql
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/StatementCreator.java
jdbc/src/main/java/org/springframework/transaction/support/ConnectionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionHandler.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 리오!
3,4단계 같이 리뷰요청 드립니다.
말했던 account관련한 것은 unique제약을 걸고, 테스트에서는 deleteAll로 초기화를 해주고, insert후 해당 user 조회를 위해 updateAndReturnKey를 구현해 id를 반환받는 식으로 해결해보았어요

[JDBC 라이브러리 구현하기 - 3,4단계] 도치(김동흠) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStateExecutor.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 민트...
어제도 심신이 옳지 못한 관계로 오늘 제출합니다....ㅜㅜ
편의 봐주셔서 감사합니다...ㅜㅜ
지난 리뷰에서 마음 깊이 이해했지만 시간관계상 반영하지 못한 부분이 몇 있습니다...
[2단계 답변](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/452)
[3단계](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/606/files/b500ea2928cea79719961372a5dd94c2b3de6851..e98b1e6d3e3c83710fc7289ae4e620ce5a84af25)
[4단계](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/606/files/e98b1e6d3e3c83710fc7289ae4e620ce5a84af25..399018494ddb19fc72f2b33a8203ae615074a9d7)

[JDBC 라이브러리 구현하기 - 3,4단계] 케로(김지현) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/TxUserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/jdbc/exception/CannotGetJdbcConnectionException.java
jdbc/src/main/java/org/springframework/jdbc/exception/DataAccessException.java
jdbc/src/main/java/org/springframework/jdbc/exception/PreparedStatementExecuteException.java
jdbc/src/main/java/org/springframework/jdbc/exception/ResultSetMappingException.java
jdbc/src/main/java/org/springframework/jdbc/exception/TransactionException.java
jdbc/src/main/java/org/springframework/transaction/support/ConnectionHolder.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/main/java/aop/config/DataSourceConfig.java
study/src/main/resources/application.yml

안녕하세요 푸우
4단계 정말 쉽지 않네요??
템플릿 콜백으로 중복 코드를 제거하고 app userservice와 txuserservice를 나눠서 비즈니스 - db 로직을 구분하는 것까진 수월했지만..
Required 형태의 트랜잭션 전파를 구현해야한다는 점이 어려워서 다른 코드를 좀 많이 참고 했습니다
특히 DataSourceUtils의 releaseConnection의 분기문들..
리뷰 잘부탁드립니다

jdbc step4 주드 미션 제출합니다

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/SecondUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

🐸케로케로케로케🐸 안녕하세요 🦁키아라키아라키아라키ㅇ🦁입니다
이번엔 3,4 단계를 한번에 제출하게됐어요.허허
3단계에서 트랜잭션 경계 설정을 하고 넘어갔다 생각하고 4단계를 진행하던 중 한 고민에 빠져버렸읍니더
UserService엔 changePassword() 말고도 findById() 가 있죠. 
changePassword()는 트랜잭션을 시작하고 findById()로 id를 갖고 온 후에 log까지 찍고 트랜잭션을 종료합니다. 하나의 트랜잭션에서 진행하기 위함이죠. 그런데 findById()도 마찬가지로 어떤 이유에서 이 메서드 하나만 사용할 때 트랜잭션을 적용하고 싶다면 findById()에서도 마지막에 트랜잭션을 종료(commit, rollback)해야하죠. 그럼 changePassword()에서 호출하고 돌아갈 때 트랜잭션이 종료되버리면 안되는데 이 이걸 어떻게 해결해야 할지 도통 모르겠습니다. 
그래서 살짝 이게 맞나 싶은 방법이긴 한데 커넥션이 있는지 확인한 후(지금 생각해보면 열려있는지도 확인했어야 했는데) 있으면 거기에 참여하고 없으면 새 커넥션을 받아 트랜잭션 시작하도록했습니다.. 
제가 요구사항을 잘 만족했는지 좔 모르겠네욥ㅎㅅㅎㅠㅠ 이번에도 리뷰 잘 부탁드립니다!

[JDBC 3,4단계] 키아라 미션 제출합니다 

---

app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TransactionService.java
app/src/main/java/com/techcourse/service/TransactionUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/SqlRuntimeExceptionTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplateBase.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplateExecutionBase.java
jdbc/src/main/java/org/springframework/jdbc/core/error/SqlExceptionType.java
jdbc/src/main/java/org/springframework/jdbc/core/error/exception/TableNotFoundSqlRuntimeException.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
study/src/main/java/aop/service/UserService.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java

안녕하세요 레오!!😊
구현이 조금 오래걸려서 3,4 단계 같이해서 리뷰요청 드립니다!!👍
정말 요구사항보다 더 좋은 방향으로 설계해보고자 많은 노력을 했으나 실패해버렸습니다ㅠㅠ
우선 이번단계에 대한 리뷰 시간이 많지 않으실 것 같아서 PR 보내고 이전 리뷰에 대한 코멘트 답변에 대한 부분 완성하고 DM 혹은 오프라인으로 찾아가서 말씀드리겠습니다!! 😄
그리고 최근에 컨디션 조절 못했더니 몸상태가 잘 안올라오더라구요ㅠㅠ 오늘 밤새신다고 하셨는데 너무 무리하지 마시구 화이팅입니다!! 💪

[JDBC 라이브러리 구현하기 - 3,4단계] 스플릿(박상현) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/transaction/TransactionException.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionManagerTest.java
jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java

오래기다리셨습니다 에밀...
살아서 돌아왔습니다...
- rowNumber를 구현한 이유
- 학습 목적 상 최대한 원본과 비슷하게 구현하기 위해 도전해봤습니다.
- rowNumber는 디버깅과 로깅용이고, 그에 적합하게 구현한 건 아니라는 생각이 드네요 ㅠㅠ
- finally 블록에서 예외 발생 시 catch 블록에서 던진 예외에 덮어씌워지는데, 그렇다면 과연 finally 블록에서 예외를 던지는 것이 맞을까요? 
- finally에서 발생한 정보는 로깅 처리하므로써, 예외가 덮어지지 않도록 처리하였습니다.
잘 부탁드립니다 에밀~!!

[JDBC 라이브러리 구현하기 - 4단계] 준팍(박준현) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/org/springframework/transaction/support/JdbcTransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSupplier.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

이번 미션도 벌써 마지막 단계네요 (저는 하루 늦게 제출하지만ㅠㅠ)
다시 한 번 죄송합니다
특정 스레드마다 dataSource에 대한 Connection을 등록해두고 같은 트랜잭션 내에서 진행되어야 한다면 같은 Connection을 쓰도록 하는 게 감탄이 나오네요.
그런데 4단계 미션을 위해 리팩토링 하면서 또 다른 심각한 의문점이 생겨서 질문 하나만 드릴게요.
현재 `DAO`에 있는 메서드들도 public으로 열려 있어서 다른 객체에서 사용할텐데 획득한 Connection을 닫아주지 못하고 있는 상태가 되었습니다. 그렇다고 메서드가 호출될 때마다 닫히면 여러 개의 쿼리를 한 트랜잭션으로 묶는 게 되질 않습니다.
결국 Connection을 닫고 싶으면 `TxUserService`와 같은 구현체를 만들어주어야 하는데 이런 행위가 스프링에서 @Transactional을 달아주는 것과 비슷하다고 생각하면 되는 걸까요?
p.s. 질문드리고 나서 해결책을 몇 가지 배워서 DAO에서 호출된 메서드도 `Connection`을 닫아주도록 개선해주었습니다!!

[JDBC 라이브러리 구현하기 - 4단계] 썬샷(오진택) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java

안녕하세요 말랑, 이오입니다 :)
벌써 마지막 미션이네요! 4단계 리뷰도 잘부탁드립니다.
좋은 하루 보내세요!

[JDBC 라이브러리 구현하기 - 4단계] 이오(이지우) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/domain/UserHistory.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java

안녕하세요 우주 🚀
지난 미션에서는 제가 리뷰어였는데 이번에는 반대로 만나게 됐네요ㅋㅋㅋ
1단계는 요구사항이 많지 않아 간단히 구현해 봤어요.
리뷰 잘 부탁드립니다!

[JDBC 라이브러리 구현하기 - 1단계] 페드로(류형욱) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementBinder.java
jdbc/src/main/java/com/interface21/jdbc/core/QueryFunction.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementBinderTest.java
jdbc/src/test/java/com/interface21/jdbc/core/ResultMapperTest.java

안녕하세요 호기 ~~
오랜만입니다 잘 지내시죠 🙌
벌써 우테코 마지막 미션이네요 🥲
> 중복을 제거하기 위한 라이브러리는 JdbcTemplate 클래스에 구현한다.
중복을 제거하기 위한 JdbcTemplate이지만,,, JdbcTemplate의 중복 코드도 불편하더라구요,,,,ㅋㅋㅋㅋ
함수형 인터페이스로 중복을 최대한 제거하려고 했어요.
사용이 어색한 부분이나 질문 있다면 편하게 말씀 부탁드립니다. 
재미있게 마지막 미션 같이 해봐요 🔥

[1단계 - JDBC 라이브러리 구현하기] - 몰리(김지민) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/MappedResultSet.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/TypedPreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/exception/JdbcAccessException.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/MappedResultSetTest.java
jdbc/src/test/java/com/interface21/jdbc/core/TypedPreparedStatementSetterTest.java

안녕하세요 트레 🐶🐾 감자입니다 🥔
애플리케이션 코드에서 `PreparedStatementSetter` 인터페이스를 매번 구현하는 대신, 가변 인자를 통해 전달할 수 있도록 `TypedPreparedStatementSetter` 구현체를 추가해 봤어요. 아무래도 제가 직접 작성한 코드이다 보니, 복잡성이나 역할 분리에 대한 객관적인 판단이 잘 안 되는 것 같아요 🥲 이 부분에 대한 트레의 의견이 있다면 편하게 말씀해 주세요 :)
2단계 리뷰도 잘 부탁드립니다 😊

[2단계 - JDBC 라이브러리 구현하기] 감자(김주하) 미션 제출합니다. 

---

jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java

안녕하세요 무빈! 구름 ⛅️입니다.
step1에서 step2 부분을 해버린 것 같아서 죄송합니다.
step2 설명에는 JdbcTemplate이 추상클래스인 것 같은데 왜 그런지 잘 모르겠습니다. 
JdbcTemplateTest를 작성해봤는데 mock을 사용해서 좋은 테스트인지 모르겠네요.
step2에서 JDBC라이브러리에서 다음의 동작을 수행해야할 것 같습니다.
여기서 트랜잭션 부분은 다음 step이라 제외하고 구현했습니다.
- Connection 생성 ✅
- Statement 준비 및 실행 ✅
- ResultSet 생성 ✅
- 예외 처리 ✅
- 트랜잭션 관리 ❌
- Connection, Statement, ResultSet 객체 close ✅
- SQLException은 Checked Exception이다. 커스텀 Exception을 추가해서 사용자는 Unchecked Exception이 되도록 변경하자.
-> DataAccessException으로 변경
- RowMapper 인터페이스는 Object를 반환하고 있어서 캐스팅이 사용된다. 제네릭을 사용하도록 개선해보자.
-> RowMapper<T>, T mapRow 사용
- 매번 PreparedStatementSetter 인터페이스를 구현하려니 번거롭다. 가변인자를 사용해서 좀더 편리하게 만들 수 없을까?
-> query, queryForObject, update에서 가변인자 사용
```java
public <T> List<T> query(String sql, @Nullable PreparedStatementSetter pss, RowMapper<T> …
```

[2단계 - JDBC 라이브러리 구현하기] 구름(김민수) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/RowMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/resources/schema.sql
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 클로버~
이렇게 미션에서 만나니 감회가 새롭네요 ㅎㅎ
부담없이 남겨주시면 열심히 반영하고 의견 남겨보겠습니다.
이번 미션에서는 `JdbcTemplate`의 테스트를 짜는 부분에서 고민을 좀 했는데요.
실제로 `JdbcTemplate`의 동작만을 테스트할 수 있도록 Mock을 사용했는데 이 때문에 실제로 db에 잘 반영되는지는 확인하기가 어렵게 되더라구요. 이에 대한 클로버의 생각이나 클로버는 어떤 식으로 구현했는지 궁금합니다!
잘 부탁드립니다.

[1단계 - JDBC 라이브러리 구현하기] - 알파카(최휘용) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/domain/User.java
app/src/main/resources/logback.xml
docs/README.md
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/resources/schema.sql
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 초코칩!! 
리뷰어로 만나서 반갑습니다 :)
리뷰 잘 부탁드립니다!

[1단계 - JDBC 라이브러리 구현하기] 레디(최동근) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
jdbc/src/test/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetterTest.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementSetterTest.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/stage1/Stage1Test.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/SecondUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 호기~
이번 단계 진행 사항은 크게 변경된 게 없는 것 같아요.
이전 PR에서 시도해보고 싶었던 쿼리 타입 체크 관련해서는, 당시에 생각했던 것보다 만만치 않은 일인 것 같아 요구사항에만 집중하기로 했어요 😅
참고하면 좋을 부분은 다음과 같아요.
- PreparedStatement에 인자를 넣어주던 책임을 PreparedStatementSetter로 추상화하고 기존 구현체인 PreparedStatementBinder를 ArgumentPreparedStatementSetter라는 구현체로 변경했습니다.
- LMS에 있는 JdbcTemplate의 executeQuery 메서드는 필요성을 크게 느끼지 못해 추가하지 않았습니다.
이번 단계도 잘 부탁드립니다~!

[2단계 - JDBC 라이브러리 구현하기] 몰리(김지민) 미션 제출합니다.

---

.gitignore
jdbc/src/main/java/com/interface21/jdbc/PreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 클로버 🍀 
이번 미션의 요구사항은 어쩌다 보니 이전 미션에서 많이 고민했던 부분이라 어느 정도 반영이 되어 있었어서 크게 변경점은 없습니다.
추가된 부분이 적어서 정리해보자면 크게
1. 학습 테스트 주석 추가
2. `ResultSet`을 close하도록 코드 수정 및 테스트 추가
3. 쿼리에 argument 넣어주는 로직 인터페이스로 분리
이렇게 되는데요.
3번은 미션 요구사항을 참고해서 적용하게 되었습니다.
근데 이 부분을 **인터페이스와 람다함수**로 리팩토링하게 되면서 여러 고민을 하게 되었고, 이에 따라 현재와 같은 구조가 되었습니다.
이전의 구조처럼 가변인자로 `args`를 받고 내부적으로 정의된 `PreparedStatementSetter`의 로직에 따라서만 동작하게 된다면 인터페이스와 람다함수의 장점을 전혀 살리지 못할 뿐더러 이전 구조보다 더 깔끔하지 못하다는 생각이 들어서 어떻게 해야 장점을 살릴 수 있을까 생각을 좀 해봤습니다.
그래서 현재는 `PreparedStatementSetter`를 매개변수로 받는 `update`와 `query` 메서드가 기본적으로 존재하고, 다른 매개변수를 받아야 하는 다른 메서드들에서는 해당 메서드를 호출하는 체이닝 방식으로 구현을 하게 되었습니다.
가변인자인 `args`를 받게 되면 내부적으로 정의된 `PreparedStatementSetter`를 사용해서 다른 메서드를 호출하게 되고, `PreparedStatementSetter`를 매개변수로 받는 메서드도 public으로 열어놓음으로써 외부에서도 직접 인터페이스를 정의해 사용할 수 있도록 …

[2단계 - JDBC 라이브러리 구현하기] 알파카(최휘용) 미션 제출합니다.

---

jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java

안녕하세요 리건~
제가 STEP1때 고민했던 부분이 STEP2와 연관이 되어있어서 크게 많은 처리가 발생하진 않았네요
변경 사항은 PreparedStatementSetter가 인터페이스로 분리되어서 JdbcTemplate에서 PreparedStatement에서 Args를 Pstmt에 세팅하는 책임을 분리했다는 점이구요
PreparedStatementSetter는 제가 구현한 ArgumentPreparedStatementSetter 를 사용하긴 했지만, 확장 및 사용의 편의를 위해서 FunctionalInterface로도 선언해두었습니다.
쿼리는 서버 운영의 정보보다는 디버그를 위한 정보에 가깝다고 생각합니다.
실제로 개발을 하다보면 쿼리는 Debug레벨로 찍히기도 하구요
때문에 info 레벨로 찍어주던 쿼리를 Debug 레벨로 변경하였습니다
리건이 저번에 리뷰 남겨주신 부분에 대해서 이걸 좀 더 간소화할 수 없을까 고민하다가 알게 되었는데요
Statement 객체는 close 시에 ResultSet도 함께 close해주기 때문에 ResultSet Close 로직을 제거해도 괜찮다는 것을 알게 되었습니다.
모르셨다면 리건도 참고하세요:)

[2단계 - JDBC 라이브러리 구현하기] 이든(최승준) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/resources/schema.sql
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/com/interface21/jdbc/core/ConsumerWrapper.java
jdbc/src/main/java/com/interface21/jdbc/core/FunctionWrapper.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/java/connectionpool/DataSourceConfig.java
study/src/main/java/transaction/DatabasePopulatorUtils.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
study/src/test/java/connectionpool/stage2/Stage2Test.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

몰리 안녕하세요 ~
2단계 리팩터링 진행 후 리뷰 요청 드립니다 :)
LMS에서 제시하는 리팩터링 요소들을 1단계에서 많이 충족시켜서,
이번 단계에서는 중복 로직을 최대한 추출하려고 노력했어요.
추가로 리팩터링 요소 보이시면 마구 말씀해주세요!
이번 단계도 잘 부탁드립니다. 감사해요 😊

[JDBC 라이브러리 구현하기 - 2단계] 에버(손채영) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementArgumentsSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementArgumentsSetterTest.java
study/src/main/java/aop/repository/UserHistoryDao.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/stage2/Stage2Test.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage1/UserDao.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 우주! 오랜만에 다시 요청드리는 것 같네요😁
이번 단계에서는 `RowMapper`를 인터페이스로 추출하고, `PreparedStatementSetter`를 도입하여 DAO단에서는 쿼리 문자열을 생성하고 파라미터의 순서에 맞게 메서드 인자 순서를 맞춰 호출만 하면 동작할 수 있도록 리팩토링 해 봤어요.
사실 학습 테스트의 양이 더 많네요ㅎㅎ 이번 리뷰도 잘 부탁드려요!

[2단계 - JDBC 라이브러리 구현하기] 페드로(류형욱) 미션 제출합니다.

---

jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/stage0/Stage0Test.java
study/src/test/java/connectionpool/stage1/Stage1Test.java
study/src/test/java/connectionpool/stage2/Stage2Test.java
study/src/test/java/transaction/stage1/Stage1Test.java

안녕하세요 폴라! 2단계로 돌아왔습니다.
의도하지 않았는데, 1단계에서 기존 JdbcTemplate의 구조를 많이 따라하다보니, 2단계 리팩터링에서 요구하는 요구사항들이 거의 다 만족되어 있더라구요. 그래서 기존에 SQLException을 잡아서 RuntimeException으로 날리던 부분을 DataAccessException이라는 커스텀 예외를 날리는 정도로 변경한 것 외에는 코드 상으로 변경된 점이 없습니다! (그래도 LMS 내용을 꼼꼼히 보고 학습해보았습니다..!)
추가로 DM에서 이야기 나눴던 것처럼, 학습테스트에 주석으로 학습한 내용을 추가했습니다! phantomReading 테스트에서 schema.sql 쪽에 에러가 나던 부분은 schema.sql의 주석에 적힌 설명대로, 아래와 같이 멀티쿼리 옵션을 수행하도록 변경해서 해결했습니다! 
```java
config.setJdbcUrl(container.getJdbcUrl() + "?allowMultiQueries=true");
```
참고로 schema.sql에 적혀있던 주석 내용은 다음과 같습니다.
```
-- mysql 8.0.30부터는 statement.execute()으로 여러 쿼리를 한 번에 실행할 수 없다.
-- 멀티 쿼리 옵션을 url로 전달하도록 수정하는 방법을 찾아서 적용하자.
```
리뷰할 내용이 거의 없을 것 같긴 하지만, 잘 부탁드립니다!!

[2단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementUtils.java
jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/resources/schema.sql
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 로빈!! 
2단계 pr이 조금 늦어졌네요🥲 2단계 리뷰도 잘 부탁드립니다!
아래는 1단계에서 남겨주신 피드백에 대한 답변입니다.
---
> 가변인자가 포함되지 않은 메서드가 필요할까요? 가변인자의 동작 방식에대해 조금 더 학습해보시고 다음 단계에서 학습 내용을 반영해보면 좋을 것 같아요.
로빈의 피드백을 보고 가변인자가 없는 메서드를 지워주었는데, 컴파일 에러가 발생하지 않더라구요.
그래서 가변인자에 대해 찾아보았는데, 인자를 **0개 이상** 전달할 수 있다고 합니다!
인자가 없을 경우도 허용하기 때문에 가변인자가 포함되지 않은 메서드는 삭제해 주었습니다.
로빈이 가변인자의 동작 방식에 대해 강조하신 이유를 이제 알았네요😀
> setObject 를 이용하면 모든 상황에서 안전하게 지정할 수 있을까요? 다음 두 가지 상황은 항상 동일하게 동작하나요?
statement.setInt(1, 1);
statement.setObject(1, 1);
제가 찾아본 결과 jdbc 드라이버에 따라 다르다고 합니다!
MySQL의 경우 특정 데이터 타입을 setObject로 받으면, 자동으로 해당 데이터 타입으로 변환해 준다고 합니다.
[스택오버플로우](https://stackoverflow.com/questions/35531621/can-preparedstatements-setobject-method-be-used-for-any-datatype)
[mysql connector의 PreparedStatement …

[2단계 - JDBC 라이브러리 구현하기] 레모네(이지현) 미션 제출합니다.

---

jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/SqlParameterBinder.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/ResultMapperTest.java
jdbc/src/test/java/com/interface21/jdbc/core/SqlParameterBinderTest.java

안녕하세요 안나!
저번 1단계 마지막에 남겨주신 리뷰 반영과 함께 돌아왔습니다 🙇‍♂️
이번에도 잘 부탁드립니다 🔥
아직까지 단계에서는 `가변인자를 사용하여 인자를 받는 것보다 배열을 통해 인자를 받는 것`을 선택하였습니다.
- 가변인자를 사용하게 된다면 배열 생성을 신경 쓸 필요 없이 간단하게 인자를 전달할 수 있지만 (편리성을 제공), 이에 따라 사용자 측에서 인자를 올바르게 전달해야 하는 책임이 더 커지게 됩니다.
- 배열을 사용하게 된다면 배열을 명시적으로 생성해야 하는 불편함이 있지만, 명시적으로 넘어갈 인자를 표현하게 되어 의도치 않은 동작이 일어나는 것을 `최소한`으로 줄일 수 있다고 생각되었습니다. (-> 물론 배열을 사용하더라도 휴먼에러는 발생할 것 같습니다)
아래와 같이 배열을 인자로 받는 경우에는 컴파일 오류를 통해 인자가 입력되지 않았다는 것을 명시하지만, 
가변인수를 인자로 받는 경우에는 컴파일 오류를 띄워주지 않아 추후에 의도치 않은 동작이 이루어질 가능성이 존재
> 배열을 인자로 받는 경우
> 가변인자를 인자로 받는 경우

[2단계 - JDBC 라이브러리 구현하기] 호티(윤주호) 미션 제출합니다. 

---

jdbc/src/main/java/com/interface21/dao/DataAccessException.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultSetExtractor.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultSetHandler.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java

안녕하세요 이상 👋
LMS의 미션 설명에 해당하는 요구사항은 1단계에서 대부분 구현해서, 변경내역이 많지는 않습니다. 
다만 미션 하면서 고민했던 내용을 이야기 나눠보면 좋겠어요 🙇‍♂️
- `PreparedStatementSetter` 인터페이스 추가
- `JdbcTemplate.setParameters()` 구현 변경
- `JdbcTemplate.execute()`의 접근제어자를 `public`으로 변경
- `JdbcTemplate.execute()`의 `catch`문에서 `SqlException`을 `DataAccessException`으로 전환
- `ResultSetHandler` → `ResultSetExtractor` 이름 변경 및 접근제어자 `public`으로 변경
LMS의 설명처럼 `PreparedStatementSetter` 인터페이스를 추가했어요. [01fcd9d](https://github.com/woowacourse/java-jdbc/pull/724/commits/01fcd9dd9a4412e944a35a6a0dced17cf1b1d68d)에서 메서드 오버로딩을 통해 개발자가 `PreparedStatementSetter`와 를 직접 만들어 메서드의 파라미터로 전달할 수 있게 하려고 시도해봤어요. 그런데, `JdbcTemplate.setParameters()` 메서드처럼 파라미터를 바인딩하는 상황 외에 다른 사용 방식이 있는지는 잘 모르겠어요. 
또, 1단계 요구사항이 `개발자는 SQL 쿼리 작성, 쿼리에 전달할 인자, SELECT 구문일 경우 조회 결과를 추출하는 것만 집중할 수 있도록 …

[2단계 - JDBC 라이브러리 구현하기] 제우스(신재우) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java

안녕하세요 🚢🗝️!
발등에 불🔥 떨어져서 빠르게 미션을 진행해 보았습니다!
- 비밀번호 변경 및 로그 쿼리 실행
- 2개의 쿼리 실행 중 문제 발생 시 전체 롤백
- 해당 쿼리는 서로 다른 DAO 에서 실행
- `UserHistoryDao` 또한 `JdbcTemplate` 을 사용하도록 하여 `Connection` 과 `PreparedStatement` 를 직접 만들던 코드를 축약하여 실행하도록 하였습니다.
- `UserService` 에서는 아래 코드로 해당 쿼리를 동시에 실행합니다.
```
userDao.update(user, connection);
userHistoryDao.log(new UserHistory(user, createBy), connection);
```
- 해당 부분을 실행하기 위해 우선은 비지니스 로직 위치인 `UserService` 에서 `Connection` 을 만든 뒤 `DAO > JdbcTemplate` 까지 넘어가도록 구현하였습니다.
- 이러한 상황은 4단계에서 필요한 관점을 분리하여 해결할 수 있을 것으로 보여요! 👀
<br>
그럼 이번 리뷰도 잘 부탁 드릴게요! 🤗

[3단계 - JDBC 라이브러리 구현하기] 새양(양경호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/stage1/Stage1Test.java
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage1/User.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

제제 안녕하세요! 또다시 아토입니다.
저번 피드백에서 `PreparedStatement` 값 세팅 관련해 이야기해주셨는데,
일단은 lms를 참고해 가변인자를 사용하도록 변경해보았습니다!
또한 객체 하나를 만들어야 하는데 두개 이상 나올 경우에 대한 예외를 처리해주었고,
없을 경우 바로 null을 리턴하는 것이 아닌 Optional.empty()를 리턴하도록 변경했습니다.
그리고 람다를 사용하려 했는데...
`preparedStatement`의 `executeUpdate()` 와 `executeQuery()` 때문에
공통되는 부분들을 분리하면 람다 안에서 또 try-catch를 사용해야 하더라고요.
```java
public void executeQuery(String sql, Object... params) {
execute(sql, params, preparedStatement -> {
try {
preparedStatement.executeUpdate();
return null;
} catch (SQLException e) {
throw new RuntimeException(e);
}
});
}
private <T> T execute(String sql, Object[] params, Function<PreparedStatement, T> action) {
try (Connection connection = dataSource.getConnection();
PreparedStatement preparedStatement = connection.prepareStatement(sql)) { …
```

[JDBC 라이브러리 구현하기 - 2단계] 아토(이혜린) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementExecutor.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementParameterBinder.java
jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/PreparedStatementParameterBinderTest.java
jdbc/src/test/java/com/interface21/jdbc/core/SqlExecutorTest.java
study/src/main/resources/schema.sql
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 비토! 
이번 미션은 '리팩토링'이라 제 주관이 좀 들어갔는데요 😁 LMS에 나와 있는 PreparedStatementSetter 인터페이스는 사용하지 않고 JdbcTemplate에서 모두 사용하고 있는 파라미터 바인딩 기능(JdbcTemplate의 private 메소드)을 유틸 클래스로 추출했습니다. 공통 기능이어서 함수형 인터페이스로 추출하고 람다식을 써야 할 필요를 느끼지 못했습니다.
기존에 JdbcTemplateTest에서 PreparedStatement의 파라미터 바인딩까지 테스트하고 있었는데 PreparedStatementParameterBinderTest로 옮겼습니다.
큰 변경사항은 없네요! 저번 마지막 리뷰들도 반영했습니다 :) 이번 단계도 잘 부탁드립니다 🙇🏻‍♀️

[2단계 - JDBC 라이브러리 구현하기] 미아(이종미) 미션 제출합니다.

---

app/src/test/java/com/techcourse/dao/UserDaoTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/stage1/Stage1Test.java
study/src/test/java/connectionpool/stage1/hikari.properties
study/src/test/java/transaction/stage1/Stage1Test.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 이든!
2단계는 리팩토링이었는데요. 
이미 1단계 코드에서 제가 생각할 수 있는 최선의 리팩토링을 적용한 채로 코드를 제출했다 보니 어떤 것을 해야할지 생각이 나지 않았어요.
아래는 제가 롤백한 시도들입니다.
1. `PreparedStatementSetter`
가이드에 제공된 것 처럼 `PreparedStatementSetter` 를 분리해 볼까 했었는데, 해당 책임이 클래스로 분리될 이유를 찾지 못했어요.
이 기능을 다르게 변경하여 사용하는 시나리오도 머릿속에 떠오르는 상황이 없었고요.
이정도로 작고 현재 클래스와 강결합된 역할이라면 `private` 메서드로 유지하는 것이 오히려 옳은 선택이라 생각했습니다.
2. 데코레이터 패턴 
다음으로 고려했던 것은 비즈니스 코드 분리를 위한 추상클래스 도입이었어요.
이 경우 사실상 중복코드 제거가 불가능하고, 관심사의 분리를 위한 작업이 되었어요.
추상 클래스의 메서드에서 `try-catch` 부분을 구현한 뒤 `internalXXX` 메서드로 포워딩 하는 방식이었는데요.
해당 작업에서 관심사 분리를 할 수 있었지만, 추상화를 위한 추상 클래스 사용이 아니었기 때문에 굉장히 어색해 반영하지 않았어요.
3. 메서드 템플릿 패턴
위와 동일한 이유로 템플릿 메서드 패턴을 고려하기도 하였습니다.
그러나 조회와 생성/수정에 대해 필요한 파라미터 타입이 조금씩 다르더라고요.
조회시에는 `ObjectMapper` 클래스로 `ResultSet` -> 객체 변환이 필요하지만 수정시엔 해당 작업이 필요가 없었어요.
이런 상황에서 함수형 인터페이스를 사용한 템플릿 메서드 …

[2단계 - 리팩터링] 짱수(장혁수) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/domain/UserHistory.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
jdbc/src/test/java/com/interface21/transaction/TransactionManagerTest.java
study/src/test/java/transaction/stage2/SecondUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 호기 ~
이번 단계도 잘 부탁드립니다!
트랜잭션은 외부에서 autoCommit이 false인 Connection을 주입하도록 변경했습니다. 
그 과정에서 JdbcTemplate의 DataSource가 불변이 아니게 되버렸네요 🥲
관련해서 다른 좋은 아이디어 있으시면 조언 부탁드려요.
이번 단계도 파이팅해봐요 🔥

[3단계 - Transaction 적용하기] 몰리(김지민) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/TransactionRollbackException.java
jdbc/src/main/java/com/interface21/transaction/TransactionRollbackException.java

안녕하세요. 재즈~!
3단계로 다시 돌아왔습니다😎
미션 마감일이 좀 빠듯한 것 같아서 일단 구현에 초점을 맞춰 진행했습니다.
현재 동일한 트랜잭션에서 동일한 connection을 매개변수로 넘기는 방식인데, 기존의  모든 메서드에 변경이 일어난다는 점이 아쉽네요🥲
아마, 4단계 때 요구사항에 맞춰서 리팩토링을 진행하지 않을까 싶어요!
잘 부탁드립니다 🙇‍♀️

[3단계 - Transaction 적용하기] 배키(백은희) 미션 제출합니다. 

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/dao/IncorrectResultSizeDataAccessException.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultSetDataExtractor.java
jdbc/src/main/java/com/interface21/jdbc/core/utils/DefaultDataExtractor.java
jdbc/src/main/java/com/interface21/jdbc/core/utils/DefaultPreparedStatementSetterFactory.java
jdbc/src/main/java/com/interface21/jdbc/core/utils/DefaultResultSetDataExtractor.java
jdbc/src/main/java/com/interface21/jdbc/core/utils/SQLExceptionHandler.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
jdbc/src/test/java/com/interface21/jdbc/core/utils/DefaultPreparedStatementSetterFactoryTest.java
study/src/main/resources/schema.sql
study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
study/src/test/java/transaction/stage2/User.java

안녕하세요 조조~ 2단계로 찾아뵈었어요!
말씀드린 것처럼 부족한 학습 테스트는 아마 4단계쯤... 함께 해서 보내드리지 않을까 싶습니다!
이번 미션에서는 이런 것들에 집중했어요.
- 단일 역할 클래스 분리
- 메서드 책임 분리
- 기존 테스트들이 깨지지 않고 돌아가도록 리팩터링에 충실
조금 과한 분리인가 싶기도 한데... 🤔
조조의 의견이 궁금하네요!
아래로는 간단한 코드 설명과 고민했던 점, 지난 피드백에서 답하지 못한 질문에 대한 답들을 적어둘게요 💗
---
```java
public <T> List<T> query(String sql, PreparedStatementSetter setter, ResultSetDataExtractor<T> extractor) {
return executePreparedStatement(sql, setter,
extractor::extractData);
}
public <T> List<T> query(String sql, RowMapper<T> rowMapper, Object... parameters) {
return query(sql, createDefaultPreparedStatementSetter(parameters), new DefaultResultSetDataExtractor<>(rowMapper));
}
public <T> List<T> query(String sql, RowMapper<T> rowMapper, PreparedStatementSetter setter) {
return query(sql, setter, new …
```

[2단계] 애쉬 미션 제출합니다~!

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/QueryConnectionHolder.java
jdbc/src/main/java/com/interface21/jdbc/transaction/ThrowingConsumer.java
jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionManager.java
jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionalFunction.java
jdbc/src/test/java/com/interface21/jdbc/transaction/TransactionManagerTest.java

우주 안녕하세요! 3단계 미션 구현 완료해서 리뷰 요청 드려요🙂
바뀐 점은 크게 없고, `Connection`을 템플릿 외부에서 주입 가능하도록 `QueryConnectionHolder`를 하나 두고, 필요할 때 `PrepareStatement`로 변환해서 사용하는 형태로 구현했습니다.
오버로딩을 많이 활용하게 되는데, 사용자가 오버로딩된 메서드 중 어떤 것을 사용할 때 어느 정도까지 직접 커넥션을 관리해 줘야 하는지 메서드 시그니처만 보고서는 쉽게 파악할 수 없을 것 같다는 고민이 있긴 했지만... 아직까지는 뚜렷한 해결책을 찾지 못해서 이대로 요청 드리게 되었어요🥲
이번 단계도 잘 부탁합니다!

[3단계 - JDBC 라이브러리 구현하기] 페드로(류형욱) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/com/interface21/jdbc/transaction/TransactionManager.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/com/interface21/jdbc/transaction/TransactionManagerTest.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java

안녕하세요 우주! 드디어 마지막 미션의 마지막 단계까지 오게 됐네요🔥
끝까지 같이 파이팅해봐요😁

[JDBC 라이브러리 구현하기 - 4단계] 페드로(류형욱) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java
study/src/test/java/aop/stage2/Stage2Test.java

안녕하세요 폴라! 벌써 마지막 미션이네요 🥹
이번 단계를 진행하면서 고민했던 포인트 하나를 공유하고자 합니다!
Q: JdbcTemplate의 queryForObject()와 같이 조회를 위한 메서드도 Connection을 DataSourceUtils로부터 얻어오는게 좋을까? 즉, 트랜잭션 관리가 필요할까? 데이터를 변경하지 않으니까 조회가 실패해도 rollback을 할 필요가 없으므로 굳이 트랜잭션으로 관리할 필요가 없지 않을까?
그리고 직접 내린 답변은 다음과 같습니다.
A: 트랜잭션1에서 데이터를 변경하고 커밋하기 전에, 트랜잭션2에서 데이터를 조회하면 트랜잭션 격리 수준에 따라 데이터의 일관성을 유지하기 위해 트랜잭션1의 변경 사항이 반영되지 않고 조회될 수 있습니다. 하지만 하나의 트랜잭션 내에서 데이터를 변경 후 조회하는 과정이 있다면, 해당 조회에서는 변경된 사항이 반영되어야 합니다. 이를 위해선 변경과 조회가 하나의 트랜잭션으로 묶여야겠지요. 그래서 조회에서도 트랜잭션이 필요하다는 결론을 내렸습니다!
이에 대한 폴라의 의견이 궁금해요!
이번에도 리뷰 잘 부탁드립니다 🙇‍♂️

[4단계 - JDBC 라이브러리 구현하기] 카고(정민호) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/dao/DataAccessException.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionManager.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java
study/src/test/java/aop/stage2/Stage2Test.java

드디어 마지막 단계네요! 이번 단계 구현의 핵심은 ThreadLocal과 Proxy (데코레이터 패턴)을 이용한 관심사 분리였어요.
각 스레드에서만 접근 가능한 저장공간을 제공하는 API 입니다. 
내부적으로 ThreadLocalMap 이라는 일종의 해시 맵 자료구조를 이용해 동작합니다.
모든 Thread에는 내부적으로 `ThreadLocal.ThreadLocalMap threadLocals;` 이런 필드를 가지고 있습니다.
`ThreadLocal.get()` 은 내부적으로 `Thread.currentThread()` 호출을 통해 현재 실행중인 스레드의 저 필드에 접근하여 데이터를 가져옵니다.
설정하는  것 역시 비슷한 방식으로 이루어집니다.
참고로 로그가 어디서 발생했는지 추적하기 위해 사용되는 MDC의 LogBack 구현체가 내부적으로 ThreadLocal을 사용하더군요. (플젝에서 써서 알아봤어요.)
프록시는 대리라는 의미 처럼 어떤 동작을 대신 처리하는 객체를 말합니다. 대리작업의 앞 뒤에 부가적인 작업을 하도록 구현하기 쉽기 때문에 이런 방식을 사용합니다. 그리고 이런 용도로 프록시를 사용하면 데코레이터 패턴에 해당합니다.
프록시를 사용한 다른 예시는 JPA 의 엔티티를 예로 들 수 있습니다. 단, 이때는 데코레이터 패턴보다는 프록시 패턴에 더 가깝습니다. 부가 기능을 제공하는 것 보단, 접근을 제어하는 것에 가깝기 때문입니다. 즉시 로딩과 레이지 로딩은 객체의 필드에 접근하는 방식을 제어하는 것이기 때문입니다.

[4단계 - JDBC 라이브러리 구현하기] 로빈(임수빈) 미션 제출합니다.

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
app/src/test/java/com/techcourse/dao/UserDaoTest.java
app/src/test/java/com/techcourse/dao/UserHistoryDaoTest.java
app/src/test/java/com/techcourse/service/AppUserServiceTest.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/core/ResultSetMapper.java
jdbc/src/main/java/com/interface21/jdbc/core/TransactionManager.java
jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java

이든 마지막 PR 이네요!
그동안 고생하셨습니다!
확실히 이전 단계에서 `ThreadLocal` 을 사용하는 방법을 고민하고 나니 4단계 구현이 어렵지 않았네요!
AOP 학습 이후에는 더 코드를 정리할 수 있을 것 같기도 합니다!!
이든의 코멘트에 동의하였습니다. 다만 굳이 실제 spring.jdbc 에서 제공하는 인터페이스의 이름을 따라갈 필요는 없다고 느꼈어요.
이에 `ResultSetMapper` 라는 이름으로 변경하였습니다.

[4단계 - JDBC 라이브러리 구현하기] 짱수(장혁수) 미션 제출합니다.

---

README.md
app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/jdbc/datasource/DataSourceUtils.java
jdbc/src/main/java/com/interface21/transaction/TransactionManager.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
jdbc/src/test/java/com/interface21/transaction/support/TransactionSynchronizationManagerTest.java
study/src/main/java/aop/repository/UserHistoryDao.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java
study/src/test/java/transaction/stage2/FirstUserService.java
study/src/test/java/transaction/stage2/Stage2Test.java

안녕하세요 카키! 마지막 미션이라니.. 아쉽네요..
✅  connection의 autoCommit 값을 활용해 트랜잭션을 건 로직과 아닌 로직의 connection close를 jdbcTemplate이 책임지게 해주었습니다.
처음 구조에서 dao가 connection을 받아 사용한단 점이 아쉬웠습니다.  connection 닫는 부분 제어를 jdbcTemplate이 책임지게 해줌으로써, connection 제어를 위해 dao까지 connection을 알고 있어야 했던 기존 구조를 리팩토링해줄 수 있었습니다.
✅ AppUserService가 온전히 비즈니스 로직만 담고, 외부의 세부사항에 의존하지 않게 리팩토링해주었습니다.
✅ 학습테스트는 빠르게 추가해두겠습니다:)

[4단계 - JDBC 라이브러리 구현하기] 도라(추서연) 미션 제출합니다. 

---

app/src/main/java/com/techcourse/dao/UserDao.java
app/src/main/java/com/techcourse/dao/UserHistoryDao.java
app/src/main/java/com/techcourse/service/AppUserService.java
app/src/main/java/com/techcourse/service/TxUserService.java
app/src/main/java/com/techcourse/service/UserService.java
app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
app/src/test/java/com/techcourse/service/UserServiceTest.java
jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
jdbc/src/main/java/com/interface21/transaction/support/TransactionSynchronizationManager.java
study/src/test/java/aop/stage0/Stage0Test.java
study/src/test/java/aop/stage0/TransactionHandler.java
study/src/test/java/aop/stage1/Stage1Test.java
study/src/test/java/aop/stage1/TransactionAdvice.java
study/src/test/java/aop/stage1/TransactionAdvisor.java
study/src/test/java/aop/stage1/TransactionPointcut.java
study/src/test/java/aop/stage2/AopConfig.java

안녕하세요 뽀오오오온드
벌써 마지막 리뷰 요청이군요!
이번 리뷰에서는 마지막 리뷰인만큼 여유를 가지고 여러 얘기 나눠보면 좋을 것 같습니다 :>
리뷰 잘부탁드린다구요😘😘

[4단계 - JDBC 라이브러리 구현하기] 도비(김도엽) 미션 제출합니다.
